// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["CALLOUT", {"literal":".","pos":6}]},
    {"name": "_", "symbols": [{"literal":" ","pos":12}]},
    {"name": "CALLOUT$string$1", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CALLOUT", "symbols": [{"literal":"I","pos":18}, "_", "DAMAGEVERB", "_", "AGENT", "_", "CALLOUT$string$1", "_", "DAMAGE"]},
    {"name": "CALLOUT", "symbols": [{"literal":"I","pos":38}, "_", "SEEVERB", "_", "AGENT", "_", "LOCATION"]},
    {"name": "CALLOUT$string$2", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CALLOUT$string$3", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CALLOUT", "symbols": ["AGENT", "_", "CALLOUT$string$2", "_", "DAMAGEVERB", "_", "CALLOUT$string$3", "_", "DAMAGE"]},
    {"name": "CALLOUT", "symbols": [{"literal":"I","pos":74}, "_", "SEEVERB", "_", "AGENT", "_", "PREP", "_", "LOCATION", "CONJ", "_", "CALLOUT"]},
    {"name": "CALLOUT$string$4", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CALLOUT", "symbols": ["AGENT", "_", "DAMAGEVERB", "_", "CALLOUT$string$4", "_", "DAMAGE"]},
    {"name": "CALLOUT$string$5", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CALLOUT", "symbols": ["AGENT", "_", "CALLOUT$string$5", "_", "MOD"]},
    {"name": "CALLOUT$string$6", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CALLOUT", "symbols": ["AGENT", "_", "CALLOUT$string$6", "_", "MOD", "_", "PREP", "_", "LOCATION"]},
    {"name": "CALLOUT", "symbols": [{"literal":"I","pos":148}, "_", "DAMAGEVERB", "_", "AGENT", "_", "LOCATION"]},
    {"name": "CALLOUT$string$7", "symbols": [{"literal":"."}, {"literal":" "}, {"literal":" "}, {"literal":"L"}, {"literal":"e"}, {"literal":"t"}, {"literal":"'"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CALLOUT", "symbols": ["AGENT", "_", "DAMAGEVERB", "_", "DAMAGE", "CALLOUT$string$7", "COMMAND"]},
    {"name": "AGENT$string$1", "symbols": [{"literal":"A"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$1"]},
    {"name": "AGENT$string$2", "symbols": [{"literal":"B"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$2"]},
    {"name": "AGENT$string$3", "symbols": [{"literal":"B"}, {"literal":"r"}, {"literal":"i"}, {"literal":"m"}, {"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$3"]},
    {"name": "AGENT$string$4", "symbols": [{"literal":"C"}, {"literal":"h"}, {"literal":"a"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$4"]},
    {"name": "AGENT$string$5", "symbols": [{"literal":"C"}, {"literal":"y"}, {"literal":"p"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$5"]},
    {"name": "AGENT$string$6", "symbols": [{"literal":"J"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$6"]},
    {"name": "AGENT$string$7", "symbols": [{"literal":"K"}, {"literal":"a"}, {"literal":"y"}, {"literal":"/"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$7"]},
    {"name": "AGENT$string$8", "symbols": [{"literal":"K"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"j"}, {"literal":"o"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$8"]},
    {"name": "AGENT$string$9", "symbols": [{"literal":"N"}, {"literal":"e"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$9"]},
    {"name": "AGENT$string$10", "symbols": [{"literal":"O"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$10"]},
    {"name": "AGENT$string$11", "symbols": [{"literal":"P"}, {"literal":"h"}, {"literal":"o"}, {"literal":"e"}, {"literal":"n"}, {"literal":"i"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$11"]},
    {"name": "AGENT$string$12", "symbols": [{"literal":"R"}, {"literal":"a"}, {"literal":"z"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$12"]},
    {"name": "AGENT$string$13", "symbols": [{"literal":"R"}, {"literal":"e"}, {"literal":"y"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$13"]},
    {"name": "AGENT$string$14", "symbols": [{"literal":"S"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$14"]},
    {"name": "AGENT$string$15", "symbols": [{"literal":"S"}, {"literal":"k"}, {"literal":"y"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$15"]},
    {"name": "AGENT$string$16", "symbols": [{"literal":"S"}, {"literal":"o"}, {"literal":"v"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$16"]},
    {"name": "AGENT$string$17", "symbols": [{"literal":"V"}, {"literal":"i"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$17"]},
    {"name": "AGENT$string$18", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"r"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AGENT", "symbols": ["AGENT$string$18"]},
    {"name": "DAMAGEVERB$string$1", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DAMAGEVERB", "symbols": ["DAMAGEVERB$string$1"]},
    {"name": "DAMAGEVERB$string$2", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DAMAGEVERB", "symbols": ["DAMAGEVERB$string$2"]},
    {"name": "SEEVERB$string$1", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SEEVERB", "symbols": ["SEEVERB$string$1"]},
    {"name": "SEEVERB$string$2", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"o"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SEEVERB", "symbols": ["SEEVERB$string$2"]},
    {"name": "SEEVERB$string$3", "symbols": [{"literal":"p"}, {"literal":"e"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SEEVERB", "symbols": ["SEEVERB$string$3"]},
    {"name": "SEEVERB$string$4", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SEEVERB", "symbols": ["SEEVERB$string$4"]},
    {"name": "PREP$string$1", "symbols": [{"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREP", "symbols": ["PREP$string$1"]},
    {"name": "PREP$string$2", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREP", "symbols": ["PREP$string$2"]},
    {"name": "PREP$string$3", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREP", "symbols": ["PREP$string$3"]},
    {"name": "PREP$string$4", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}, {"literal":" "}, {"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREP", "symbols": ["PREP$string$4"]},
    {"name": "LOCATION$string$1", "symbols": [{"literal":"A"}, {"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$1"]},
    {"name": "LOCATION$string$2", "symbols": [{"literal":"B"}, {"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$2"]},
    {"name": "LOCATION$string$3", "symbols": [{"literal":"C"}, {"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$3"]},
    {"name": "LOCATION$string$4", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"a"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$4"]},
    {"name": "LOCATION$string$5", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$5"]},
    {"name": "LOCATION$string$6", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$6"]},
    {"name": "LOCATION$string$7", "symbols": [{"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"p"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$7"]},
    {"name": "LOCATION$string$8", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$8"]},
    {"name": "LOCATION$string$9", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$9"]},
    {"name": "LOCATION$string$10", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"a"}, {"literal":"w"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$10"]},
    {"name": "LOCATION$string$11", "symbols": [{"literal":"C"}, {"literal":"."}, {"literal":"T"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$11"]},
    {"name": "LOCATION$string$12", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"f"}, {"literal":"a"}, {"literal":"u"}, {"literal":"l"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$12"]},
    {"name": "LOCATION$string$13", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$13"]},
    {"name": "LOCATION$string$14", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$14"]},
    {"name": "LOCATION$string$15", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$15"]},
    {"name": "LOCATION$string$16", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$16"]},
    {"name": "LOCATION$string$17", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$17"]},
    {"name": "LOCATION$string$18", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$18"]},
    {"name": "LOCATION$string$19", "symbols": [{"literal":"g"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$19"]},
    {"name": "LOCATION$string$20", "symbols": [{"literal":"r"}, {"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$20"]},
    {"name": "LOCATION$string$21", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$21"]},
    {"name": "MOD$string$1", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$1"]},
    {"name": "MOD$string$2", "symbols": [{"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"-"}, {"literal":"h"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$2"]},
    {"name": "MOD$string$3", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$3"]},
    {"name": "MOD$string$4", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"l"}, {"literal":"o"}, {"literal":"a"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$4"]},
    {"name": "MOD$string$5", "symbols": [{"literal":"p"}, {"literal":"e"}, {"literal":"a"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$5"]},
    {"name": "DAMAGE$string$1", "symbols": [{"literal":"4"}, {"literal":"9"}, {"literal":" "}, {"literal":"h"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DAMAGE", "symbols": ["DAMAGE$string$1"]},
    {"name": "DAMAGE$string$2", "symbols": [{"literal":"1"}, {"literal":"4"}, {"literal":"9"}, {"literal":" "}, {"literal":"h"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DAMAGE", "symbols": ["DAMAGE$string$2"]},
    {"name": "DAMAGE$string$3", "symbols": [{"literal":"1"}, {"literal":"2"}, {"literal":"0"}, {"literal":" "}, {"literal":"h"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DAMAGE", "symbols": ["DAMAGE$string$3"]},
    {"name": "DAMAGE$string$4", "symbols": [{"literal":"6"}, {"literal":"0"}, {"literal":" "}, {"literal":"h"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DAMAGE", "symbols": ["DAMAGE$string$4"]},
    {"name": "COMMAND$string$1", "symbols": [{"literal":"F"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND", "symbols": ["COMMAND$string$1"]},
    {"name": "COMMAND$string$2", "symbols": [{"literal":"R"}, {"literal":"o"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND", "symbols": ["COMMAND$string$2"]},
    {"name": "COMMAND$string$3", "symbols": [{"literal":"P"}, {"literal":"u"}, {"literal":"s"}, {"literal":"h"}, {"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND", "symbols": ["COMMAND$string$3"]},
    {"name": "COMMAND$string$4", "symbols": [{"literal":"E"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND", "symbols": ["COMMAND$string$4"]},
    {"name": "CONJ$string$1", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONJ", "symbols": ["CONJ$string$1"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
