// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["INSTRUCTIONS"]},
    {"name": "_", "symbols": [{"literal":" ","pos":10}]},
    {"name": "INSTRUCTIONS", "symbols": ["INITIAL", "MIDDLE", "_", "FINAL", "_", "LOCATION"]},
    {"name": "INITIAL$string$1", "symbols": [{"literal":"F"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INITIAL", "symbols": ["INITIAL$string$1", "_", "COMMAND"]},
    {"name": "MIDDLE$subexpression$1$string$1", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MIDDLE$subexpression$1", "symbols": [{"literal":".","pos":43}, "_", "MIDDLE$subexpression$1$string$1"]},
    {"name": "MIDDLE$subexpression$1$string$2", "symbols": [{"literal":"N"}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MIDDLE$subexpression$1", "symbols": [{"literal":".","pos":51}, "_", "MIDDLE$subexpression$1$string$2"]},
    {"name": "MIDDLE$subexpression$2", "symbols": ["MIDDLE"]},
    {"name": "MIDDLE$subexpression$2", "symbols": [{"literal":".","pos":67}]},
    {"name": "MIDDLE", "symbols": ["MIDDLE$subexpression$1", "_", "COMMAND", "MIDDLE$subexpression$2"]},
    {"name": "FINAL$string$1", "symbols": [{"literal":"F"}, {"literal":"i"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FINAL", "symbols": ["FINAL$string$1", "_", "COMMAND", {"literal":".","pos":81}]},
    {"name": "LOCATION$string$1", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION$string$2", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$1", "_", "PLACE", "_", "LOCATION$string$2", "_", "PREPOSITION", {"literal":".","pos":101}]},
    {"name": "COMMAND$string$1", "symbols": [{"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND", "symbols": ["COMMAND$string$1", "_", "DIRECTION"]},
    {"name": "COMMAND$string$2", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND$string$3", "symbols": [{"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND", "symbols": ["COMMAND$string$2", "_", "DIRECTION", "_", "COMMAND$string$3"]},
    {"name": "COMMAND$string$4", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND", "symbols": ["COMMAND$string$4", "_", "STREET"]},
    {"name": "COMMAND$string$5", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":" "}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"l"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND$subexpression$1", "symbols": ["STREET"]},
    {"name": "COMMAND$subexpression$1$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND$subexpression$1", "symbols": ["COMMAND$subexpression$1$string$1", "_", "PLACE"]},
    {"name": "COMMAND$subexpression$1$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND$subexpression$1", "symbols": ["COMMAND$subexpression$1$string$2"]},
    {"name": "COMMAND", "symbols": ["COMMAND$string$5", "_", "COMMAND$subexpression$1"]},
    {"name": "DIRECTION$string$1", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DIRECTION", "symbols": ["DIRECTION$string$1"]},
    {"name": "DIRECTION$string$2", "symbols": [{"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DIRECTION", "symbols": ["DIRECTION$string$2"]},
    {"name": "PREPOSITION$string$1", "symbols": [{"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$1", "_", "DIRECTION"]},
    {"name": "PREPOSITION$subexpression$1$string$1", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION$subexpression$1", "symbols": ["PREPOSITION$subexpression$1$string$1"]},
    {"name": "PREPOSITION$subexpression$1$string$2", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"c"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION$subexpression$1", "symbols": ["PREPOSITION$subexpression$1$string$2"]},
    {"name": "PREPOSITION$subexpression$1$string$3", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}, {"literal":" "}, {"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION$subexpression$1", "symbols": ["PREPOSITION$subexpression$1$string$3"]},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$subexpression$1", "_", "PLACE"]},
    {"name": "PREPOSITION$string$2", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"t"}, {"literal":"w"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION$string$3", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$2", "_", "PLACE", "_", "PREPOSITION$string$3", "_", "PLACE"]},
    {"name": "PREPOSITION$string$4", "symbols": [{"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION$string$5", "symbols": [{"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$4", "_", "DIRECTION", "_", "PREPOSITION$string$5", "_", "PLACE"]},
    {"name": "STREET$subexpression$1$string$1", "symbols": [{"literal":"F"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STREET$subexpression$1", "symbols": ["STREET$subexpression$1$string$1"]},
    {"name": "STREET$subexpression$1$string$2", "symbols": [{"literal":"S"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STREET$subexpression$1", "symbols": ["STREET$subexpression$1$string$2"]},
    {"name": "STREET$subexpression$1$string$3", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"i"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STREET$subexpression$1", "symbols": ["STREET$subexpression$1$string$3"]},
    {"name": "STREET$subexpression$1$string$4", "symbols": [{"literal":"F"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STREET$subexpression$1", "symbols": ["STREET$subexpression$1$string$4"]},
    {"name": "STREET$subexpression$1$string$5", "symbols": [{"literal":"F"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STREET$subexpression$1", "symbols": ["STREET$subexpression$1$string$5"]},
    {"name": "STREET$subexpression$1$string$6", "symbols": [{"literal":"M"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STREET$subexpression$1", "symbols": ["STREET$subexpression$1$string$6"]},
    {"name": "STREET$string$1", "symbols": [{"literal":"S"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STREET", "symbols": ["STREET$subexpression$1", "_", "STREET$string$1"]},
    {"name": "STREET", "symbols": ["NAME", "_", "TYPE"]},
    {"name": "NAME$string$1", "symbols": [{"literal":"P"}, {"literal":"a"}, {"literal":"r"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$1"]},
    {"name": "NAME$string$2", "symbols": [{"literal":"O"}, {"literal":"a"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$2"]},
    {"name": "NAME$string$3", "symbols": [{"literal":"M"}, {"literal":"a"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$3"]},
    {"name": "NAME$string$4", "symbols": [{"literal":"P"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$4"]},
    {"name": "NAME$string$5", "symbols": [{"literal":"W"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"t"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$5"]},
    {"name": "NAME$string$6", "symbols": [{"literal":"C"}, {"literal":"e"}, {"literal":"d"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$6"]},
    {"name": "NAME$string$7", "symbols": [{"literal":"E"}, {"literal":"l"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$7"]},
    {"name": "NAME$string$8", "symbols": [{"literal":"W"}, {"literal":"a"}, {"literal":"l"}, {"literal":"n"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$8"]},
    {"name": "NAME$string$9", "symbols": [{"literal":"L"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$9"]},
    {"name": "NAME$string$10", "symbols": [{"literal":"S"}, {"literal":"u"}, {"literal":"n"}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$10"]},
    {"name": "NAME$string$11", "symbols": [{"literal":"L"}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$11"]},
    {"name": "NAME$string$12", "symbols": [{"literal":"J"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$12"]},
    {"name": "NAME$string$13", "symbols": [{"literal":"C"}, {"literal":"h"}, {"literal":"u"}, {"literal":"r"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$13"]},
    {"name": "NAME$string$14", "symbols": [{"literal":"R"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$14"]},
    {"name": "NAME$string$15", "symbols": [{"literal":"W"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$15"]},
    {"name": "NAME$string$16", "symbols": [{"literal":"J"}, {"literal":"e"}, {"literal":"f"}, {"literal":"f"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$16"]},
    {"name": "NAME$string$17", "symbols": [{"literal":"C"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$17"]},
    {"name": "NAME$string$18", "symbols": [{"literal":"N"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$18"]},
    {"name": "NAME$string$19", "symbols": [{"literal":"R"}, {"literal":"i"}, {"literal":"d"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$19"]},
    {"name": "NAME$string$20", "symbols": [{"literal":"H"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"o"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$20"]},
    {"name": "NAME$string$21", "symbols": [{"literal":"A"}, {"literal":"d"}, {"literal":"a"}, {"literal":"m"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$21"]},
    {"name": "NAME$string$22", "symbols": [{"literal":"C"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$22"]},
    {"name": "NAME$string$23", "symbols": [{"literal":"H"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$23"]},
    {"name": "NAME$string$24", "symbols": [{"literal":"J"}, {"literal":"o"}, {"literal":"h"}, {"literal":"n"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$24"]},
    {"name": "NAME$string$25", "symbols": [{"literal":"S"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$25"]},
    {"name": "TYPE$string$1", "symbols": [{"literal":"A"}, {"literal":"v"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$1"]},
    {"name": "TYPE$string$2", "symbols": [{"literal":"B"}, {"literal":"l"}, {"literal":"v"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$2"]},
    {"name": "TYPE$string$3", "symbols": [{"literal":"D"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$3"]},
    {"name": "TYPE$string$4", "symbols": [{"literal":"L"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$4"]},
    {"name": "TYPE$string$5", "symbols": [{"literal":"R"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$5"]},
    {"name": "TYPE$string$6", "symbols": [{"literal":"S"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$6"]},
    {"name": "PLACE$string$1", "symbols": [{"literal":"m"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":"u"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$1"]},
    {"name": "PLACE$string$2", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$2"]},
    {"name": "PLACE$string$3", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$3"]},
    {"name": "PLACE$string$4", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"s"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$4"]},
    {"name": "PLACE$string$5", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"o"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$5"]},
    {"name": "PLACE$string$6", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"t"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$6"]},
    {"name": "PLACE$string$7", "symbols": [{"literal":"a"}, {"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$7"]},
    {"name": "PLACE$string$8", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"b"}, {"literal":"w"}, {"literal":"a"}, {"literal":"y"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$8"]},
    {"name": "PLACE$string$9", "symbols": [{"literal":"z"}, {"literal":"o"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$9"]},
    {"name": "PLACE$string$10", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$10"]},
    {"name": "PLACE$string$11", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$11"]},
    {"name": "PLACE$string$12", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"b"}, {"literal":"r"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$12"]},
    {"name": "PLACE$string$13", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":"f"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$13"]},
    {"name": "PLACE$string$14", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"o"}, {"literal":"c"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$14"]},
    {"name": "PLACE$string$15", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"u"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$15"]},
    {"name": "PLACE$string$16", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$16"]},
    {"name": "PLACE$string$17", "symbols": [{"literal":"g"}, {"literal":"y"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$17"]},
    {"name": "PLACE$string$18", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"u"}, {"literal":"r"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$18"]},
    {"name": "PLACE$string$19", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"i"}, {"literal":"r"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"l"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$19"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
