// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["DECLARATION", {"literal":"!","pos":6}]},
    {"name": "MAIN", "symbols": ["QUESTION", {"literal":"?","pos":11}]},
    {"name": "_", "symbols": [{"literal":" ","pos":17}]},
    {"name": "QUESTION", "symbols": ["QPHRASE", "_", "PERSON", "_", "DNOUN"]},
    {"name": "DECLARATION$string$1", "symbols": [{"literal":","}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DECLARATION", "symbols": ["PERSON", "_", "ADJ", "DECLARATION$string$1", "_", "ADJ", "_", "SPECIFIEDSUB"]},
    {"name": "DECLARATION$string$2", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DECLARATION$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DECLARATION", "symbols": ["PERSON", "_", "DECLARATION$string$2", "_", "SUPERLATIVE", "_", "SPECIFIEDSUB", "_", "DECLARATION$string$3", "_", "ACTION"]},
    {"name": "DECLARATION", "symbols": ["POSESSIVE", "_", "ORGAN", "_", "ASSESSMENT", "_", "GERUND"]},
    {"name": "DECLARATION", "symbols": ["COMMAND", "_", "DNOUN"]},
    {"name": "DECLARATION", "symbols": ["COMMAND", "_", "DECLARATION", "_"]},
    {"name": "PERSON$string$1", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$1"]},
    {"name": "PERSON$string$2", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$2"]},
    {"name": "ORGAN$string$1", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGAN", "symbols": ["ORGAN$string$1"]},
    {"name": "ORGAN$string$2", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGAN", "symbols": ["ORGAN$string$2"]},
    {"name": "ORGAN$string$3", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGAN", "symbols": ["ORGAN$string$3"]},
    {"name": "ORGAN$string$4", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGAN", "symbols": ["ORGAN$string$4"]},
    {"name": "POSESSIVE$string$1", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSESSIVE", "symbols": ["POSESSIVE$string$1"]},
    {"name": "POSESSIVE$string$2", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSESSIVE", "symbols": ["POSESSIVE$string$2"]},
    {"name": "ADJ$string$1", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$1"]},
    {"name": "ADJ$string$2", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"g"}, {"literal":"e"}, {"literal":"o"}, {"literal":"n"}, {"literal":"-"}, {"literal":"l"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$2"]},
    {"name": "ADJ$string$3", "symbols": [{"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"o"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$3"]},
    {"name": "ADJ$string$4", "symbols": [{"literal":"u"}, {"literal":"g"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$4"]},
    {"name": "ADJ$string$5", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"l"}, {"literal":"o"}, {"literal":"y"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$5"]},
    {"name": "ADJ$string$6", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$6"]},
    {"name": "ADJ$string$7", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"j"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$7"]},
    {"name": "ADJ$string$8", "symbols": [{"literal":"v"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$8"]},
    {"name": "SPECIFIEDSUB$string$1", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SPECIFIEDSUB", "symbols": ["SPECIFIEDSUB$string$1"]},
    {"name": "SPECIFIEDSUB$string$2", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SPECIFIEDSUB", "symbols": ["SPECIFIEDSUB$string$2"]},
    {"name": "SPECIFIEDSUB$string$3", "symbols": [{"literal":"t"}, {"literal":"o"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SPECIFIEDSUB", "symbols": ["SPECIFIEDSUB$string$3"]},
    {"name": "SPECIFIEDSUB$string$4", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SPECIFIEDSUB", "symbols": ["SPECIFIEDSUB$string$4"]},
    {"name": "SPECIFIEDSUB$string$5", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"o"}, {"literal":"t"}, {"literal":"b"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SPECIFIEDSUB", "symbols": ["SPECIFIEDSUB$string$5"]},
    {"name": "SUPERLATIVE$string$1", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUPERLATIVE", "symbols": ["SUPERLATIVE$string$1"]},
    {"name": "SUPERLATIVE$string$2", "symbols": [{"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUPERLATIVE", "symbols": ["SUPERLATIVE$string$2"]},
    {"name": "SUPERLATIVE$string$3", "symbols": [{"literal":"u"}, {"literal":"g"}, {"literal":"l"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUPERLATIVE", "symbols": ["SUPERLATIVE$string$3"]},
    {"name": "ACTION$string$1", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$1"]},
    {"name": "ACTION$string$2", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"l"}, {"literal":"k"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"E"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$2"]},
    {"name": "ACTION$string$3", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"f"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"e"}, {"literal":"y"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$3"]},
    {"name": "ACTION$string$4", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"o"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$4"]},
    {"name": "ASSESSMENT$string$1", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ASSESSMENT", "symbols": ["ASSESSMENT$string$1"]},
    {"name": "ASSESSMENT$string$2", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ASSESSMENT", "symbols": ["ASSESSMENT$string$2"]},
    {"name": "DNOUN$string$1", "symbols": [{"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"c"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DNOUN", "symbols": ["DNOUN$string$1"]},
    {"name": "DNOUN$string$2", "symbols": [{"literal":"e"}, {"literal":"g"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DNOUN", "symbols": ["DNOUN$string$2"]},
    {"name": "DNOUN$string$3", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"i"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DNOUN", "symbols": ["DNOUN$string$3"]},
    {"name": "DNOUN$string$4", "symbols": [{"literal":"e"}, {"literal":"m"}, {"literal":"b"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"b"}, {"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DNOUN", "symbols": ["DNOUN$string$4"]},
    {"name": "GERUND$string$1", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"n"}, {"literal":"b"}, {"literal":"u"}, {"literal":"r"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GERUND", "symbols": ["GERUND$string$1"]},
    {"name": "GERUND$string$2", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"e"}, {"literal":"a"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GERUND", "symbols": ["GERUND$string$2"]},
    {"name": "GERUND$string$3", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GERUND", "symbols": ["GERUND$string$3"]},
    {"name": "GERUND$string$4", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GERUND", "symbols": ["GERUND$string$4"]},
    {"name": "COMMAND$string$1", "symbols": [{"literal":"G"}, {"literal":"o"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND", "symbols": ["COMMAND$string$1"]},
    {"name": "COMMAND$string$2", "symbols": [{"literal":"O"}, {"literal":"u"}, {"literal":"t"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMMAND", "symbols": ["COMMAND$string$2"]},
    {"name": "QPHRASE$string$1", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QPHRASE", "symbols": ["QPHRASE$string$1"]},
    {"name": "QPHRASE$string$2", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"w"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QPHRASE", "symbols": ["QPHRASE$string$2"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
