// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["SENTENCEONE", {"literal":".","pos":6}, "_", "SENTENCETWO", {"literal":".","pos":12}, "_", "SENTENCETHREE", {"literal":".","pos":18}, "_", "HASHTAG", "HASHTAG", "HASHTAG"]},
    {"name": "_", "symbols": [{"literal":" ","pos":32}]},
    {"name": "SENTENCEONE$string$1", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"h"}, {"literal":"u"}, {"literal":"m"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"h"}, {"literal":"o"}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"n"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCEONE", "symbols": ["SENTENCEONE$string$1", "MOD"]},
    {"name": "SENTENCEONE$string$2", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"e"}, {"literal":"x"}, {"literal":"c"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"n"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCEONE", "symbols": ["SENTENCEONE$string$2", "MOD"]},
    {"name": "SENTENCEONE$string$3", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"j"}, {"literal":"o"}, {"literal":"y"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"n"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCEONE", "symbols": ["SENTENCEONE$string$3", "MOD"]},
    {"name": "SENTENCEONE$string$4", "symbols": [{"literal":"I"}, {"literal":"t"}, {"literal":"’"}, {"literal":"s"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"r"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"g"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"y"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":":"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCEONE", "symbols": ["SENTENCEONE$string$4", "MOD"]},
    {"name": "MOD$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD$string$2", "symbols": [{"literal":"e"}, {"literal":"d"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD$string$3", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":"f"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD$string$4", "symbols": [{"literal":"a"}, {"literal":"t"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$1", "VERB", "MOD$string$2", "MOD$string$3", "POSITION", "MOD$string$4", "COMPANY"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"e"}, {"literal":"p"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$2"]},
    {"name": "VERB$string$3", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"c"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$3"]},
    {"name": "VERB$string$4", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$4"]},
    {"name": "POSITION", "symbols": ["OBJ", "_", "VERBER"]},
    {"name": "OBJ$string$1", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"s"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$1"]},
    {"name": "OBJ$string$2", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$2"]},
    {"name": "OBJ$string$3", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$3"]},
    {"name": "OBJ$string$4", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"u"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$4"]},
    {"name": "OBJ$string$5", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"d"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$5"]},
    {"name": "OBJ$string$6", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$6"]},
    {"name": "OBJ$string$7", "symbols": [{"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"f"}, {"literal":"u"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$7"]},
    {"name": "OBJ$string$8", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":" "}, {"literal":"A"}, {"literal":"i"}, {"literal":"r"}, {"literal":"P"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$8"]},
    {"name": "OBJ$string$9", "symbols": [{"literal":"A"}, {"literal":"l"}, {"literal":"e"}, {"literal":"x"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$9"]},
    {"name": "OBJ$string$10", "symbols": [{"literal":"r"}, {"literal":"o"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$10"]},
    {"name": "OBJ$string$11", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}, {"literal":"-"}, {"literal":"d"}, {"literal":"r"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$11"]},
    {"name": "OBJ$string$12", "symbols": [{"literal":"i"}, {"literal":"P"}, {"literal":"h"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$12"]},
    {"name": "OBJ$string$13", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$13"]},
    {"name": "OBJ$string$14", "symbols": [{"literal":"v"}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$14"]},
    {"name": "OBJ$string$15", "symbols": [{"literal":"a"}, {"literal":"p"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$15"]},
    {"name": "VERBER$string$1", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"r"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBER", "symbols": ["VERBER$string$1"]},
    {"name": "VERBER$string$2", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBER", "symbols": ["VERBER$string$2"]},
    {"name": "VERBER$string$3", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"n"}, {"literal":"o"}, {"literal":"i"}, {"literal":"s"}, {"literal":"s"}, {"literal":"e"}, {"literal":"u"}, {"literal":"r"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBER", "symbols": ["VERBER$string$3"]},
    {"name": "VERBER$string$4", "symbols": [{"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBER", "symbols": ["VERBER$string$4"]},
    {"name": "VERBER$string$5", "symbols": [{"literal":"c"}, {"literal":"u"}, {"literal":"r"}, {"literal":"l"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBER", "symbols": ["VERBER$string$5"]},
    {"name": "VERBER$string$6", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"r"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBER", "symbols": ["VERBER$string$6"]},
    {"name": "VERBER$string$7", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBER", "symbols": ["VERBER$string$7"]},
    {"name": "COMPANY$string$1", "symbols": [{"literal":"C"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"-"}, {"literal":"f"}, {"literal":"i"}, {"literal":"l"}, {"literal":"-"}, {"literal":"A"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$1"]},
    {"name": "COMPANY$string$2", "symbols": [{"literal":"W"}, {"literal":"a"}, {"literal":"l"}, {"literal":"m"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$2"]},
    {"name": "COMPANY$string$3", "symbols": [{"literal":"P"}, {"literal":"i"}, {"literal":"z"}, {"literal":"z"}, {"literal":"a"}, {"literal":" "}, {"literal":"H"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$3"]},
    {"name": "COMPANY$string$4", "symbols": [{"literal":"D"}, {"literal":"o"}, {"literal":"o"}, {"literal":"r"}, {"literal":"d"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$4"]},
    {"name": "COMPANY$string$5", "symbols": [{"literal":"M"}, {"literal":"e"}, {"literal":"t"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$5"]},
    {"name": "COMPANY$string$6", "symbols": [{"literal":"A"}, {"literal":"p"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$6"]},
    {"name": "COMPANY$string$7", "symbols": [{"literal":"M"}, {"literal":"c"}, {"literal":"K"}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"e"}, {"literal":"y"}, {"literal":" "}, {"literal":"&"}, {"literal":" "}, {"literal":"C"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$7"]},
    {"name": "COMPANY$string$8", "symbols": [{"literal":"U"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$8"]},
    {"name": "COMPANY$string$9", "symbols": [{"literal":"M"}, {"literal":"i"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"s"}, {"literal":"o"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$9"]},
    {"name": "COMPANY$string$10", "symbols": [{"literal":"P"}, {"literal":"a"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$10"]},
    {"name": "COMPANY$string$11", "symbols": [{"literal":"G"}, {"literal":"o"}, {"literal":"o"}, {"literal":"g"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$11"]},
    {"name": "COMPANY$string$12", "symbols": [{"literal":"A"}, {"literal":"m"}, {"literal":"a"}, {"literal":"z"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$12"]},
    {"name": "COMPANY$string$13", "symbols": [{"literal":"T"}, {"literal":"e"}, {"literal":"s"}, {"literal":"l"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMPANY", "symbols": ["COMPANY$string$13"]},
    {"name": "SENTENCETWO$string$1", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCETWO$string$2", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"p"}, {"literal":"o"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"c"}, {"literal":"a"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"h"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCETWO$string$3", "symbols": [{"literal":"s"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCETWO", "symbols": ["SENTENCETWO$string$1", "VERB", "SENTENCETWO$string$2", "_", "VERBPRESENT", "_", "OBJ", "SENTENCETWO$string$3", "_", "MODTWO"]},
    {"name": "MODTWO$string$1", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"b"}, {"literal":"y"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MODTWO", "symbols": ["MODTWO$string$1", "VERBING", "_", "OBJ", {"literal":"s","pos":288}, "_", "MODTWO"]},
    {"name": "MODTWO$string$2", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"b"}, {"literal":"y"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MODTWO", "symbols": ["MODTWO$string$2", "VERBING", "_", "OBJ", {"literal":"s","pos":304}]},
    {"name": "VERBPRESENT$string$1", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBPRESENT", "symbols": ["VERBPRESENT$string$1"]},
    {"name": "VERBPRESENT$string$2", "symbols": [{"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBPRESENT", "symbols": ["VERBPRESENT$string$2"]},
    {"name": "VERBPRESENT$string$3", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"m"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBPRESENT", "symbols": ["VERBPRESENT$string$3"]},
    {"name": "VERBPRESENT$string$4", "symbols": [{"literal":"c"}, {"literal":"u"}, {"literal":"r"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBPRESENT", "symbols": ["VERBPRESENT$string$4"]},
    {"name": "VERBPRESENT$string$5", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"o"}, {"literal":"p"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBPRESENT", "symbols": ["VERBPRESENT$string$5"]},
    {"name": "VERBPRESENT$string$6", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"a"}, {"literal":"p"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBPRESENT", "symbols": ["VERBPRESENT$string$6"]},
    {"name": "VERBPRESENT$string$7", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"c"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBPRESENT", "symbols": ["VERBPRESENT$string$7"]},
    {"name": "VERBING$string$1", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBING", "symbols": ["VERBING$string$1"]},
    {"name": "VERBING$string$2", "symbols": [{"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBING", "symbols": ["VERBING$string$2"]},
    {"name": "VERBING$string$3", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"m"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBING", "symbols": ["VERBING$string$3"]},
    {"name": "VERBING$string$4", "symbols": [{"literal":"c"}, {"literal":"u"}, {"literal":"r"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBING", "symbols": ["VERBING$string$4"]},
    {"name": "VERBING$string$5", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"o"}, {"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBING", "symbols": ["VERBING$string$5"]},
    {"name": "VERBING$string$6", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBING", "symbols": ["VERBING$string$6"]},
    {"name": "VERBING$string$7", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"c"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERBING", "symbols": ["VERBING$string$7"]},
    {"name": "SENTENCETHREE$string$1", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCETHREE", "symbols": ["SENTENCETHREE$string$1", "_", "MODTHREE"]},
    {"name": "SENTENCETHREE$string$2", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":"n"}, {"literal":"’"}, {"literal":"t"}, {"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCETHREE", "symbols": ["SENTENCETHREE$string$2", "_", "MODTHREE"]},
    {"name": "SENTENCETHREE$string$3", "symbols": [{"literal":"I"}, {"literal":"’"}, {"literal":"d"}, {"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"e"}, {"literal":"p"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"g"}, {"literal":"r"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"t"}, {"literal":"u"}, {"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCETHREE", "symbols": ["SENTENCETHREE$string$3", "_", "MODTHREE"]},
    {"name": "SENTENCETHREE$string$4", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}, {"literal":"u"}, {"literal":"b"}, {"literal":"i"}, {"literal":"t"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCETHREE", "symbols": ["SENTENCETHREE$string$4", "_", "MODTHREE"]},
    {"name": "MODTHREE$string$1", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"e"}, {"literal":"s"}, {"literal":"p"}, {"literal":"e"}, {"literal":"c"}, {"literal":"i"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"n"}, {"literal":"u"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"p"}, {"literal":"p"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":","}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MODTHREE", "symbols": ["MODTHREE$string$1", "OBJ"]},
    {"name": "HASHTAG$string$1", "symbols": [{"literal":"#"}, {"literal":"i"}, {"literal":"m"}, {"literal":"a"}, {"literal":"d"}, {"literal":"e"}, {"literal":"i"}, {"literal":"t"}, {"literal":"m"}, {"literal":"o"}, {"literal":"m"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$1"]},
    {"name": "HASHTAG$string$2", "symbols": [{"literal":"#"}, {"literal":"g"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":"g"}, {"literal":"r"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$2"]},
    {"name": "HASHTAG$string$3", "symbols": [{"literal":"#"}, {"literal":"h"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}, {"literal":"b"}, {"literal":"e"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$3"]},
    {"name": "HASHTAG$string$4", "symbols": [{"literal":"#"}, {"literal":"f"}, {"literal":"t"}, {"literal":"w"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$4"]},
    {"name": "HASHTAG$string$5", "symbols": [{"literal":"#"}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"p"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$5"]},
    {"name": "HASHTAG$string$6", "symbols": [{"literal":"#"}, {"literal":"g"}, {"literal":"r"}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$6"]},
    {"name": "HASHTAG$string$7", "symbols": [{"literal":"#"}, {"literal":"b"}, {"literal":"u"}, {"literal":"i"}, {"literal":"l"}, {"literal":"t"}, {"literal":"d"}, {"literal":"i"}, {"literal":"f"}, {"literal":"f"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HASHTAG", "symbols": ["HASHTAG$string$7"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
