// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["IMPERATIVE"]},
    {"name": "MAIN", "symbols": ["QUESTION"]},
    {"name": "MAIN", "symbols": ["ANNOUNCEMENT"]},
    {"name": "_", "symbols": [{"literal":" ","pos":18}]},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "QUESTIONSUB", "_", "VERB", "_", "OBJ", {"literal":"?","pos":38}]},
    {"name": "IMPERATIVE", "symbols": ["IMPVERB", "_", "OBJ", {"literal":"!","pos":50}]},
    {"name": "ANNOUNCEMENT", "symbols": ["ANNOUNCEMENTPHRASE", {"literal":"!","pos":58}, "_", "IMPERATIVE"]},
    {"name": "QUESTIONWORD$string$1", "symbols": [{"literal":"D"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONWORD", "symbols": ["QUESTIONWORD$string$1"]},
    {"name": "QUESTIONSUB$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONSUB", "symbols": ["QUESTIONSUB$string$1"]},
    {"name": "QUESTIONSUB$string$2", "symbols": [{"literal":"y"}, {"literal":"'"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONSUB", "symbols": ["QUESTIONSUB$string$2"]},
    {"name": "QUESTIONSUB$string$3", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"g"}, {"literal":"u"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONSUB", "symbols": ["QUESTIONSUB$string$3"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":" "}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$2"]},
    {"name": "VERB$string$3", "symbols": [{"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$3"]},
    {"name": "VERB$string$4", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$4"]},
    {"name": "IMPVERB$string$1", "symbols": [{"literal":"C"}, {"literal":"h"}, {"literal":"e"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "IMPVERB", "symbols": ["IMPVERB$string$1"]},
    {"name": "IMPVERB$string$2", "symbols": [{"literal":"L"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":" "}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "IMPVERB", "symbols": ["IMPVERB$string$2"]},
    {"name": "IMPVERB$string$3", "symbols": [{"literal":"V"}, {"literal":"i"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "IMPVERB", "symbols": ["IMPVERB$string$3"]},
    {"name": "ANNOUNCEMENTPHRASE$string$1", "symbols": [{"literal":"J"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"d"}, {"literal":"r"}, {"literal":"o"}, {"literal":"p"}, {"literal":"p"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENTPHRASE", "symbols": ["ANNOUNCEMENTPHRASE$string$1"]},
    {"name": "ANNOUNCEMENTPHRASE$string$2", "symbols": [{"literal":"R"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENTPHRASE", "symbols": ["ANNOUNCEMENTPHRASE$string$2"]},
    {"name": "ANNOUNCEMENTPHRASE$string$3", "symbols": [{"literal":"L"}, {"literal":"i"}, {"literal":"m"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"e"}, {"literal":"d"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENTPHRASE", "symbols": ["ANNOUNCEMENTPHRASE$string$3"]},
    {"name": "ANNOUNCEMENTPHRASE$string$4", "symbols": [{"literal":"O"}, {"literal":"n"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"2"}, {"literal":"0"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":"k"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENTPHRASE", "symbols": ["ANNOUNCEMENTPHRASE$string$4"]},
    {"name": "ANNOUNCEMENTPHRASE$string$5", "symbols": [{"literal":"A"}, {"literal":"m"}, {"literal":"a"}, {"literal":"z"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENTPHRASE", "symbols": ["ANNOUNCEMENTPHRASE$string$5"]},
    {"name": "ANNOUNCEMENTPHRASE$string$6", "symbols": [{"literal":"W"}, {"literal":"A"}, {"literal":"T"}, {"literal":"C"}, {"literal":"H"}, {"literal":" "}, {"literal":"O"}, {"literal":"U"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENTPHRASE", "symbols": ["ANNOUNCEMENTPHRASE$string$6"]},
    {"name": "ANNOUNCEMENTPHRASE$string$7", "symbols": [{"literal":"B"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENTPHRASE", "symbols": ["ANNOUNCEMENTPHRASE$string$7"]},
    {"name": "ANNOUNCEMENTPHRASE$string$8", "symbols": [{"literal":"N"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENTPHRASE", "symbols": ["ANNOUNCEMENTPHRASE$string$8"]},
    {"name": "ANNOUNCEMENTPHRASE$string$9", "symbols": [{"literal":"T"}, {"literal":"o"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENTPHRASE", "symbols": ["ANNOUNCEMENTPHRASE$string$9"]},
    {"name": "NFTNAME$string$1", "symbols": [{"literal":"C"}, {"literal":"r"}, {"literal":"y"}, {"literal":"p"}, {"literal":"t"}, {"literal":"o"}, {"literal":"P"}, {"literal":"u"}, {"literal":"n"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NFTNAME", "symbols": ["NFTNAME$string$1"]},
    {"name": "NFTNAME$string$2", "symbols": [{"literal":"B"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"A"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NFTNAME", "symbols": ["NFTNAME$string$2"]},
    {"name": "NFTNAME$string$3", "symbols": [{"literal":"M"}, {"literal":"o"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"B"}, {"literal":"o"}, {"literal":"y"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NFTNAME", "symbols": ["NFTNAME$string$3"]},
    {"name": "NFTNAME$string$4", "symbols": [{"literal":"F"}, {"literal":"u"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"S"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"M"}, {"literal":"e"}, {"literal":"t"}, {"literal":"a"}, {"literal":"C"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NFTNAME", "symbols": ["NFTNAME$string$4"]},
    {"name": "NFTNAME$string$5", "symbols": [{"literal":"S"}, {"literal":"u"}, {"literal":"p"}, {"literal":"D"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NFTNAME", "symbols": ["NFTNAME$string$5"]},
    {"name": "NFTNAME$string$6", "symbols": [{"literal":"M"}, {"literal":"e"}, {"literal":"e"}, {"literal":"b"}, {"literal":"i"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NFTNAME", "symbols": ["NFTNAME$string$6"]},
    {"name": "NFTNAME$string$7", "symbols": [{"literal":"P"}, {"literal":"u"}, {"literal":"n"}, {"literal":"k"}, {"literal":"s"}, {"literal":" "}, {"literal":"C"}, {"literal":"o"}, {"literal":"m"}, {"literal":"i"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NFTNAME", "symbols": ["NFTNAME$string$7"]},
    {"name": "ADJ$string$1", "symbols": [{"literal":"-"}, {"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["BLOCKCHAIN", "ADJ$string$1"]},
    {"name": "ADJ$string$2", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"e"}, {"literal":"x"}, {"literal":"c"}, {"literal":"l"}, {"literal":"u"}, {"literal":"s"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$2"]},
    {"name": "ADJ$string$3", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"z"}, {"literal":"y"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$3", "_", "ADJ"]},
    {"name": "ADJ$string$4", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"v"}, {"literal":"o"}, {"literal":"l"}, {"literal":"u"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$4"]},
    {"name": "ADJ$string$5", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"-"}, {"literal":"n"}, {"literal":"e"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$5"]},
    {"name": "OBJ$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ$string$2", "symbols": [{"literal":"d"}, {"literal":"r"}, {"literal":"o"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$1", "_", "ADJ", "_", "NFTNAME", "_", "OBJ$string$2"]},
    {"name": "OBJ$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ$string$4", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"m"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$3", "_", "ADJ", "_", "NFTNAME", "_", "OBJ$string$4"]},
    {"name": "OBJ$string$5", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ$string$6", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$5", "_", "ADJ", "_", "NFTNAME", "_", "OBJ$string$6"]},
    {"name": "OBJ$string$7", "symbols": [{"literal":"m"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ$string$8", "symbols": [{"literal":"N"}, {"literal":"F"}, {"literal":"T"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"j"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$7", "_", "ADJ", "_", "NFTNAME", "_", "OBJ$string$8"]},
    {"name": "BLOCKCHAIN$string$1", "symbols": [{"literal":"e"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"u"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BLOCKCHAIN", "symbols": ["BLOCKCHAIN$string$1"]},
    {"name": "BLOCKCHAIN$string$2", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BLOCKCHAIN", "symbols": ["BLOCKCHAIN$string$2"]},
    {"name": "BLOCKCHAIN$string$3", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"z"}, {"literal":"o"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BLOCKCHAIN", "symbols": ["BLOCKCHAIN$string$3"]},
    {"name": "BLOCKCHAIN$string$4", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":"a"}, {"literal":"n"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BLOCKCHAIN", "symbols": ["BLOCKCHAIN$string$4"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
