// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN$subexpression$1", "symbols": ["OPINIONTHING"]},
    {"name": "MAIN$subexpression$1", "symbols": ["OPINIONPERSON"]},
    {"name": "MAIN", "symbols": ["MAIN$subexpression$1"]},
    {"name": "MAIN$subexpression$2$subexpression$1", "symbols": ["TEXT"]},
    {"name": "MAIN$subexpression$2$subexpression$1", "symbols": ["OPINIONTHING"]},
    {"name": "MAIN$subexpression$2", "symbols": ["MAIN$subexpression$2$subexpression$1"]},
    {"name": "MAIN$subexpression$2", "symbols": ["STATEMENT"]},
    {"name": "MAIN", "symbols": ["MAIN$subexpression$2"]},
    {"name": "MAIN", "symbols": ["SENTENCE"]},
    {"name": "MAIN", "symbols": ["QUESTION"]},
    {"name": "MAIN", "symbols": ["LONG"]},
    {"name": "_", "symbols": [{"literal":" ","pos":44}]},
    {"name": "QUESTION$subexpression$1", "symbols": ["EXCLAIM"]},
    {"name": "QUESTION$subexpression$1", "symbols": ["EXCLAIM", "_", "ADDRESS"]},
    {"name": "QUESTION$subexpression$1", "symbols": ["ADDRESS"]},
    {"name": "QUESTION$subexpression$2$string$1", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION$subexpression$2$subexpression$1$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION$subexpression$2$subexpression$1", "symbols": ["QUESTION$subexpression$2$subexpression$1$string$1"]},
    {"name": "QUESTION$subexpression$2$subexpression$1$string$2", "symbols": [{"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION$subexpression$2$subexpression$1", "symbols": ["QUESTION$subexpression$2$subexpression$1$string$2"]},
    {"name": "QUESTION$subexpression$2$subexpression$1$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION$subexpression$2$subexpression$1", "symbols": ["QUESTION$subexpression$2$subexpression$1$string$3"]},
    {"name": "QUESTION$subexpression$2", "symbols": ["QUESTION$subexpression$2$string$1", "_", "QUESTION$subexpression$2$subexpression$1", "_", "THINGS"]},
    {"name": "QUESTION$subexpression$2$string$2", "symbols": [{"literal":"W"}, {"literal":"H"}, {"literal":"A"}, {"literal":"T"}, {"literal":" "}, {"literal":"I"}, {"literal":"S"}, {"literal":" "}, {"literal":"T"}, {"literal":"H"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION$subexpression$2$string$3", "symbols": [{"literal":"?"}, {"literal":"?"}, {"literal":"?"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION$subexpression$2", "symbols": ["QUESTION$subexpression$2$string$2", "_", "THINGSCAPS", "QUESTION$subexpression$2$string$3"]},
    {"name": "QUESTION", "symbols": ["QUESTION$subexpression$1", "_", "QUESTION$subexpression$2", "_", "TEXT"]},
    {"name": "LONG", "symbols": ["QUESTION", {"literal":",","pos":110}, "_", "OPINIONPERSON"]},
    {"name": "OPINIONTHING$subexpression$1$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONTHING$subexpression$1$subexpression$1$subexpression$1", "symbols": ["OPINIONTHING$subexpression$1$subexpression$1$subexpression$1$string$1"]},
    {"name": "OPINIONTHING$subexpression$1$subexpression$1$subexpression$1$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONTHING$subexpression$1$subexpression$1$subexpression$1", "symbols": ["OPINIONTHING$subexpression$1$subexpression$1$subexpression$1$string$2"]},
    {"name": "OPINIONTHING$subexpression$1$subexpression$1", "symbols": ["OPINIONTHING$subexpression$1$subexpression$1$subexpression$1", "_", "THINGS"]},
    {"name": "OPINIONTHING$subexpression$1", "symbols": ["OPINIONTHING$subexpression$1$subexpression$1"]},
    {"name": "OPINIONTHING$subexpression$1", "symbols": ["GAMES"]},
    {"name": "OPINIONTHING$string$1", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONTHING$subexpression$2", "symbols": ["EXCLAIM"]},
    {"name": "OPINIONTHING$subexpression$2", "symbols": ["LAUGH"]},
    {"name": "OPINIONTHING$subexpression$2", "symbols": ["EXCLAIM", "_", "LAUGH"]},
    {"name": "OPINIONTHING", "symbols": ["OPINIONTHING$subexpression$1", "_", "OPINIONTHING$string$1", "_", "ADJ", "_", "OPINIONTHING$subexpression$2"]},
    {"name": "OPINIONPERSON$subexpression$1", "symbols": ["EXCLAIM"]},
    {"name": "OPINIONPERSON$subexpression$1", "symbols": ["ADDRESS"]},
    {"name": "OPINIONPERSON$subexpression$2$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":"'"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONPERSON$subexpression$2", "symbols": ["OPINIONPERSON$subexpression$2$string$1"]},
    {"name": "OPINIONPERSON$subexpression$2$string$2", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"'"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONPERSON$subexpression$2", "symbols": ["OPINIONPERSON$subexpression$2$string$2"]},
    {"name": "OPINIONPERSON$subexpression$2$string$3", "symbols": [{"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONPERSON$subexpression$2", "symbols": ["OPINIONPERSON$subexpression$2$string$3"]},
    {"name": "OPINIONPERSON$subexpression$2$string$4", "symbols": [{"literal":"u"}, {"literal":"r"}, {"literal":"r"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONPERSON$subexpression$2", "symbols": ["OPINIONPERSON$subexpression$2$string$4"]},
    {"name": "OPINIONPERSON$subexpression$2$string$5", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"'"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONPERSON$subexpression$2", "symbols": ["OPINIONPERSON$subexpression$2$string$5"]},
    {"name": "OPINIONPERSON$subexpression$2$string$6", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"e"}, {"literal":"'"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONPERSON$subexpression$2", "symbols": ["OPINIONPERSON$subexpression$2$string$6"]},
    {"name": "OPINIONPERSON$subexpression$2$string$7", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}, {"literal":"'"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONPERSON$subexpression$2", "symbols": ["OPINIONPERSON$subexpression$2$string$7"]},
    {"name": "OPINIONPERSON$subexpression$2$string$8", "symbols": [{"literal":"i"}, {"literal":"'"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONPERSON$subexpression$2", "symbols": ["OPINIONPERSON$subexpression$2$string$8"]},
    {"name": "OPINIONPERSON$subexpression$2$string$9", "symbols": [{"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPINIONPERSON$subexpression$2", "symbols": ["OPINIONPERSON$subexpression$2$string$9"]},
    {"name": "OPINIONPERSON$subexpression$3$subexpression$1", "symbols": ["ADJ"]},
    {"name": "OPINIONPERSON$subexpression$3$subexpression$1", "symbols": ["ADJPPL"]},
    {"name": "OPINIONPERSON$subexpression$3", "symbols": ["_", "ADVERB", "_", "OPINIONPERSON$subexpression$3$subexpression$1", "_", "TEXT"]},
    {"name": "OPINIONPERSON$subexpression$3$subexpression$2", "symbols": ["ADJ"]},
    {"name": "OPINIONPERSON$subexpression$3$subexpression$2", "symbols": ["ADJPPL"]},
    {"name": "OPINIONPERSON$subexpression$3", "symbols": ["_", "OPINIONPERSON$subexpression$3$subexpression$2", "_", "TEXT"]},
    {"name": "OPINIONPERSON", "symbols": ["OPINIONPERSON$subexpression$1", "_", "OPINIONPERSON$subexpression$2", "OPINIONPERSON$subexpression$3"]},
    {"name": "STATEMENT$string$1", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATEMENT", "symbols": ["TEXT", "_", "STATEMENT$string$1", "_", "VERB", "_", "LAUGH"]},
    {"name": "STATEMENT$string$2", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATEMENT", "symbols": ["STATEMENT$string$2", "_", "VERB", "_", "LAUGH"]},
    {"name": "STATEMENT$string$3", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATEMENT", "symbols": ["STATEMENT$string$3", "_", "VERB", "_", "TEXT"]},
    {"name": "SENTENCE$subexpression$1", "symbols": ["EXCLAIM"]},
    {"name": "SENTENCE$subexpression$1", "symbols": ["LAUGH"]},
    {"name": "SENTENCE", "symbols": ["SUBJ", "_", "VERB", "_", "PERSON", "_", "SENTENCE$subexpression$1"]},
    {"name": "ADVERB$string$1", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$1"]},
    {"name": "ADVERB$string$2", "symbols": [{"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$2"]},
    {"name": "ADVERB$string$3", "symbols": [{"literal":"s"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$3"]},
    {"name": "ADVERB$string$4", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"o"}, {"literal":"o"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$4"]},
    {"name": "ADJ$string$1", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"g"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$1"]},
    {"name": "ADJ$string$2", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$2"]},
    {"name": "ADJ$string$3", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$3"]},
    {"name": "ADJ$string$4", "symbols": [{"literal":"P"}, {"literal":"O"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$4"]},
    {"name": "ADJ$string$5", "symbols": [{"literal":"h"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$5"]},
    {"name": "ADJ$string$6", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$6"]},
    {"name": "ADJ$string$7", "symbols": [{"literal":"n"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$7"]},
    {"name": "ADJ$string$8", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"z"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$8"]},
    {"name": "ADJ$string$9", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$9"]},
    {"name": "ADJ$string$10", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":"o"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$10"]},
    {"name": "ADJ$string$11", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"g"}, {"literal":"g"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$11"]},
    {"name": "ADJ$string$12", "symbols": [{"literal":"e"}, {"literal":"p"}, {"literal":"i"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$12"]},
    {"name": "ADJ$string$13", "symbols": [{"literal":"n"}, {"literal":"u"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$13"]},
    {"name": "ADJ$string$14", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$14"]},
    {"name": "ADJ$string$15", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"g"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$15"]},
    {"name": "ADJ$string$16", "symbols": [{"literal":"n"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$16"]},
    {"name": "ADJ$string$17", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"u"}, {"literal":"f"}, {"literal":"f"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$17"]},
    {"name": "ADJ$string$18", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$18"]},
    {"name": "ADJ$string$19", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"f"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$19"]},
    {"name": "ADJ$string$20", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"f"}, {"literal":"f"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$20"]},
    {"name": "ADJPPL$string$1", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJPPL", "symbols": ["ADJPPL$string$1"]},
    {"name": "ADJPPL$string$2", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJPPL", "symbols": ["ADJPPL$string$2"]},
    {"name": "ADJPPL$string$3", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJPPL", "symbols": ["ADJPPL$string$3"]},
    {"name": "ADJPPL$string$4", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"i"}, {"literal":"l"}, {"literal":"t"}, {"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"f"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJPPL", "symbols": ["ADJPPL$string$4"]},
    {"name": "ADJPPL$string$5", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"i"}, {"literal":"l"}, {"literal":"t"}, {"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"f"}, {"literal":"f"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJPPL", "symbols": ["ADJPPL$string$5"]},
    {"name": "PERSON$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"g"}, {"literal":"u"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$1"]},
    {"name": "PERSON$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"d"}, {"literal":"u"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$2"]},
    {"name": "PERSON$string$3", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$3"]},
    {"name": "PERSON$string$4", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$4"]},
    {"name": "PERSON$string$5", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$5"]},
    {"name": "PERSON$string$6", "symbols": [{"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$6"]},
    {"name": "SUBJ", "symbols": [{"literal":"i","pos":471}]},
    {"name": "SUBJ$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJ", "symbols": ["SUBJ$string$1"]},
    {"name": "SUBJ$string$2", "symbols": [{"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJ", "symbols": ["SUBJ$string$2"]},
    {"name": "SUBJ$string$3", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJ", "symbols": ["SUBJ$string$3"]},
    {"name": "SUBJ$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJ", "symbols": ["SUBJ$string$4"]},
    {"name": "SUBJ", "symbols": [{"literal":"u","pos":491}]},
    {"name": "ADDRESS$string$1", "symbols": [{"literal":"d"}, {"literal":"a"}, {"literal":"w"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$1"]},
    {"name": "ADDRESS$string$2", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$2"]},
    {"name": "ADDRESS$string$3", "symbols": [{"literal":"d"}, {"literal":"u"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$3"]},
    {"name": "ADDRESS$string$4", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"u"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$4"]},
    {"name": "ADDRESS$string$5", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$5"]},
    {"name": "ADDRESS$string$6", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"m"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$6"]},
    {"name": "ADDRESS$string$7", "symbols": [{"literal":"j"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$7"]},
    {"name": "ADDRESS$string$8", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"y"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$8"]},
    {"name": "ADDRESS$string$9", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$9"]},
    {"name": "ADDRESS$string$10", "symbols": [{"literal":"m"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$10"]},
    {"name": "ADDRESS$string$11", "symbols": [{"literal":"D"}, {"literal":"U"}, {"literal":"D"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$11"]},
    {"name": "ADDRESS$string$12", "symbols": [{"literal":"B"}, {"literal":"R"}, {"literal":"U"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$12"]},
    {"name": "ADDRESS$string$13", "symbols": [{"literal":"B"}, {"literal":"R"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADDRESS", "symbols": ["ADDRESS$string$13"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"-"}, {"literal":"t"}, {"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$2"]},
    {"name": "VERB$string$3", "symbols": [{"literal":"f"}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$3"]},
    {"name": "VERB$string$4", "symbols": [{"literal":"f"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$4"]},
    {"name": "VERB$string$5", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"s"}, {"literal":"c"}, {"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$5"]},
    {"name": "VERB$string$6", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"y"}, {"literal":"l"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$6"]},
    {"name": "VERB$string$7", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"a"}, {"literal":"g"}, {"literal":"g"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$7"]},
    {"name": "VERB$string$8", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$8"]},
    {"name": "VERB$string$9", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"s"}, {"literal":"h"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$9"]},
    {"name": "VERB$string$10", "symbols": [{"literal":"3"}, {"literal":"6"}, {"literal":"0"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$10"]},
    {"name": "VERB$string$11", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"o"}, {"literal":"y"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$11"]},
    {"name": "GAMES$string$1", "symbols": [{"literal":"V"}, {"literal":"a"}, {"literal":"l"}, {"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GAMES", "symbols": ["GAMES$string$1"]},
    {"name": "GAMES$string$2", "symbols": [{"literal":"V"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GAMES", "symbols": ["GAMES$string$2"]},
    {"name": "GAMES$string$3", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GAMES", "symbols": ["GAMES$string$3"]},
    {"name": "GAMES$string$4", "symbols": [{"literal":"L"}, {"literal":"e"}, {"literal":"a"}, {"literal":"g"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GAMES", "symbols": ["GAMES$string$4"]},
    {"name": "GAMES$string$5", "symbols": [{"literal":"L"}, {"literal":"O"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GAMES", "symbols": ["GAMES$string$5"]},
    {"name": "GAMES$string$6", "symbols": [{"literal":"C"}, {"literal":"S"}, {"literal":"G"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GAMES", "symbols": ["GAMES$string$6"]},
    {"name": "GAMES$string$7", "symbols": [{"literal":"F"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"n"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GAMES", "symbols": ["GAMES$string$7"]},
    {"name": "THINGS$string$1", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$1"]},
    {"name": "THINGS$string$2", "symbols": [{"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$2"]},
    {"name": "THINGS$string$3", "symbols": [{"literal":"P"}, {"literal":"C"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$3"]},
    {"name": "THINGS$string$4", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$4"]},
    {"name": "THINGS$string$5", "symbols": [{"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":"b"}, {"literal":"o"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$5"]},
    {"name": "THINGS$string$6", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"t"}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$6"]},
    {"name": "THINGS$string$7", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$7"]},
    {"name": "THINGS$string$8", "symbols": [{"literal":"f"}, {"literal":"p"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$8"]},
    {"name": "THINGS$string$9", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"i"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$9"]},
    {"name": "THINGS$string$10", "symbols": [{"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$10"]},
    {"name": "THINGS$string$11", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"c"}, {"literal":"o"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$11"]},
    {"name": "THINGS$string$12", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}, {"literal":"h"}, {"literal":"a"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$12"]},
    {"name": "THINGS$string$13", "symbols": [{"literal":"a"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$13"]},
    {"name": "THINGS$string$14", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$14"]},
    {"name": "THINGS$string$15", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$15"]},
    {"name": "THINGSCAPS$string$1", "symbols": [{"literal":"S"}, {"literal":"H"}, {"literal":"O"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGSCAPS", "symbols": ["THINGSCAPS$string$1"]},
    {"name": "THINGSCAPS$string$2", "symbols": [{"literal":"K"}, {"literal":"I"}, {"literal":"L"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGSCAPS", "symbols": ["THINGSCAPS$string$2"]},
    {"name": "THINGSCAPS$string$3", "symbols": [{"literal":"P"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGSCAPS", "symbols": ["THINGSCAPS$string$3"]},
    {"name": "THINGSCAPS$string$4", "symbols": [{"literal":"A"}, {"literal":"I"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGSCAPS", "symbols": ["THINGSCAPS$string$4"]},
    {"name": "THINGSCAPS$string$5", "symbols": [{"literal":"P"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGSCAPS", "symbols": ["THINGSCAPS$string$5"]},
    {"name": "TEXT", "symbols": ["EXCLAIM"]},
    {"name": "TEXT", "symbols": ["LAUGH"]},
    {"name": "TEXT", "symbols": ["SLANG"]},
    {"name": "TEXT", "symbols": ["EMOTE"]},
    {"name": "TEXT", "symbols": ["TEXT", "_", "TEXT"]},
    {"name": "EXCLAIM$string$1", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"e"}, {"literal":"e"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$1"]},
    {"name": "EXCLAIM$string$2", "symbols": [{"literal":"S"}, {"literal":"H"}, {"literal":"E"}, {"literal":"E"}, {"literal":"E"}, {"literal":"E"}, {"literal":"E"}, {"literal":"E"}, {"literal":"S"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$2"]},
    {"name": "EXCLAIM$string$3", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"e"}, {"literal":"e"}, {"literal":"e"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$3"]},
    {"name": "EXCLAIM$string$4", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"g"}, {"literal":"g"}, {"literal":"y"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$4"]},
    {"name": "EXCLAIM$string$5", "symbols": [{"literal":"a"}, {"literal":"f"}, {"literal":"s"}, {"literal":"d"}, {"literal":"h"}, {"literal":"d"}, {"literal":"s"}, {"literal":"j"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$5"]},
    {"name": "EXCLAIM$string$6", "symbols": [{"literal":"A"}, {"literal":"F"}, {"literal":"K"}, {"literal":"S"}, {"literal":"D"}, {"literal":"A"}, {"literal":"J"}, {"literal":"H"}, {"literal":"D"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$6"]},
    {"name": "EXCLAIM$string$7", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"o"}, {"literal":"o"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$7"]},
    {"name": "EXCLAIM$string$8", "symbols": [{"literal":"y"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$8"]},
    {"name": "EXCLAIM$string$9", "symbols": [{"literal":"w"}, {"literal":"t"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$9"]},
    {"name": "EXCLAIM$string$10", "symbols": [{"literal":"W"}, {"literal":"T"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$10"]},
    {"name": "EXCLAIM$string$11", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"u"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$11"]},
    {"name": "EXCLAIM$string$12", "symbols": [{"literal":"A"}, {"literal":"Y"}, {"literal":"O"}, {"literal":"O"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$12"]},
    {"name": "EXCLAIM$string$13", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$13"]},
    {"name": "EXCLAIM$string$14", "symbols": [{"literal":"L"}, {"literal":"E"}, {"literal":"T"}, {"literal":"S"}, {"literal":" "}, {"literal":"G"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$14"]},
    {"name": "EXCLAIM$string$15", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"d"}, {"literal":"d"}, {"literal":"a"}, {"literal":"m"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$15"]},
    {"name": "EXCLAIM$string$16", "symbols": [{"literal":"t"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCLAIM", "symbols": ["EXCLAIM$string$16"]},
    {"name": "LAUGH$string$1", "symbols": [{"literal":"L"}, {"literal":"M"}, {"literal":"A"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LAUGH", "symbols": ["LAUGH$string$1"]},
    {"name": "LAUGH$string$2", "symbols": [{"literal":"L"}, {"literal":"O"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LAUGH", "symbols": ["LAUGH$string$2"]},
    {"name": "LAUGH$string$3", "symbols": [{"literal":"l"}, {"literal":"m"}, {"literal":"a"}, {"literal":"o"}, {"literal":"o"}, {"literal":"o"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LAUGH", "symbols": ["LAUGH$string$3"]},
    {"name": "LAUGH$string$4", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"h"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LAUGH", "symbols": ["LAUGH$string$4"]},
    {"name": "LAUGH$string$5", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"o"}, {"literal":"o"}, {"literal":"o"}, {"literal":"o"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LAUGH", "symbols": ["LAUGH$string$5"]},
    {"name": "LAUGH$string$6", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"l"}, {"literal":"o"}, {"literal":"l"}, {"literal":"o"}, {"literal":"l"}, {"literal":"o"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LAUGH", "symbols": ["LAUGH$string$6"]},
    {"name": "LAUGH$string$7", "symbols": [{"literal":"l"}, {"literal":"m"}, {"literal":"f"}, {"literal":"a"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LAUGH", "symbols": ["LAUGH$string$7"]},
    {"name": "LAUGH$string$8", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LAUGH", "symbols": ["LAUGH$string$8"]},
    {"name": "LAUGH$string$9", "symbols": [{"literal":"H"}, {"literal":"A"}, {"literal":"H"}, {"literal":"A"}, {"literal":"H"}, {"literal":"A"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LAUGH", "symbols": ["LAUGH$string$9"]},
    {"name": "LAUGH$string$10", "symbols": [{"literal":"L"}, {"literal":"O"}, {"literal":"O"}, {"literal":"O"}, {"literal":"O"}, {"literal":"O"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LAUGH", "symbols": ["LAUGH$string$10"]},
    {"name": "SLANG$string$1", "symbols": [{"literal":"g"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$1"]},
    {"name": "SLANG$string$2", "symbols": [{"literal":"g"}, {"literal":"g"}, {"literal":"e"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$2"]},
    {"name": "SLANG$string$3", "symbols": [{"literal":"e"}, {"literal":"z"}, {"literal":" "}, {"literal":"c"}, {"literal":"l"}, {"literal":"a"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$3"]},
    {"name": "SLANG$subexpression$1$string$1", "symbols": [{"literal":"s"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG$subexpression$1", "symbols": ["SLANG$subexpression$1$string$1"]},
    {"name": "SLANG$subexpression$1$string$2", "symbols": [{"literal":"S"}, {"literal":"O"}, {"literal":"R"}, {"literal":"R"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG$subexpression$1", "symbols": ["SLANG$subexpression$1$string$2"]},
    {"name": "SLANG", "symbols": ["SLANG$subexpression$1"]},
    {"name": "SLANG$string$4", "symbols": [{"literal":"f"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$4"]},
    {"name": "SLANG$string$5", "symbols": [{"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$5"]},
    {"name": "SLANG$string$6", "symbols": [{"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$6"]},
    {"name": "SLANG$string$7", "symbols": [{"literal":"u"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$7"]},
    {"name": "SLANG$string$8", "symbols": [{"literal":"f"}, {"literal":" "}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$8"]},
    {"name": "SLANG$string$9", "symbols": [{"literal":"i"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$9"]},
    {"name": "SLANG$string$10", "symbols": [{"literal":"n"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"j"}, {"literal":"o"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$10"]},
    {"name": "SLANG$string$11", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":"u"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"g"}, {"literal":"r"}, {"literal":"a"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SLANG", "symbols": ["SLANG$string$11"]},
    {"name": "EMOTE$string$1", "symbols": [{"literal":":"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOTE", "symbols": ["EMOTE$string$1"]},
    {"name": "EMOTE$string$2", "symbols": [{"literal":":"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOTE", "symbols": ["EMOTE$string$2"]},
    {"name": "EMOTE$string$3", "symbols": [{"literal":":"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOTE", "symbols": ["EMOTE$string$3"]},
    {"name": "EMOTE$string$4", "symbols": [{"literal":":"}, {"literal":")"}, {"literal":")"}, {"literal":")"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOTE", "symbols": ["EMOTE$string$4"]},
    {"name": "EMOTE$string$5", "symbols": [{"literal":"?"}, {"literal":"?"}, {"literal":"?"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOTE", "symbols": ["EMOTE$string$5"]},
    {"name": "EMOTE", "symbols": [{"literal":"?","pos":921}]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
