// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["PHRASE"]},
    {"name": "MAIN", "symbols": ["DEMAND", {"literal":"!","pos":10}]},
    {"name": "MAIN", "symbols": ["INQUIRY"]},
    {"name": "_", "symbols": [{"literal":" ","pos":19}]},
    {"name": "PHRASE$string$1", "symbols": [{"literal":"N"}, {"literal":"o"}, {"literal":" "}, {"literal":"C"}, {"literal":"a"}, {"literal":"p"}, {"literal":"e"}, {"literal":"s"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PHRASE", "symbols": ["CHARACTER", "_", "ACTION", "_", "AUG", {"literal":".","pos":35}, "_", "PHRASE$string$1", "_", "MAIN"]},
    {"name": "DEMAND", "symbols": ["CHARACTER", {"literal":",","pos":51}, "_", "ORDER", "_", "RECURSIVE", "ADV1"]},
    {"name": "INQUIRY$string$1", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INQUIRY", "symbols": ["INQUIRYWORD", "_", "INQUIRY$string$1", "_", "NOUN", {"literal":"?","pos":77}, "_", "QUIP"]},
    {"name": "INQUIRY$string$2", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INQUIRY$string$3", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"i"}, {"literal":"t"}, {"literal":"?"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INQUIRY", "symbols": ["INQUIRY$string$2", "_", "NOUN", "_", "INQUIRY$string$3", "_", "QUIP"]},
    {"name": "RECURSIVE", "symbols": ["ADV2", "_", "RECURSIVE"]},
    {"name": "RECURSIVE", "symbols": ["C"]},
    {"name": "C", "symbols": ["ADV2", "_", "C"]},
    {"name": "C", "symbols": []},
    {"name": "INQUIRYWORD$string$1", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INQUIRYWORD", "symbols": ["INQUIRYWORD$string$1"]},
    {"name": "INQUIRYWORD$string$2", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INQUIRYWORD", "symbols": ["INQUIRYWORD$string$2"]},
    {"name": "INQUIRYWORD$string$3", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INQUIRYWORD", "symbols": ["INQUIRYWORD$string$3"]},
    {"name": "INQUIRYWORD$string$4", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INQUIRYWORD", "symbols": ["INQUIRYWORD$string$4"]},
    {"name": "CHARACTER$string$1", "symbols": [{"literal":"M"}, {"literal":"r"}, {"literal":"."}, {"literal":"I"}, {"literal":"n"}, {"literal":"c"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":"i"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$1"]},
    {"name": "CHARACTER$string$2", "symbols": [{"literal":"V"}, {"literal":"i"}, {"literal":"o"}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$2"]},
    {"name": "CHARACTER$string$3", "symbols": [{"literal":"K"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$3"]},
    {"name": "CHARACTER$string$4", "symbols": [{"literal":"D"}, {"literal":"a"}, {"literal":"r"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$4"]},
    {"name": "CHARACTER$string$5", "symbols": [{"literal":"E"}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"g"}, {"literal":"i"}, {"literal":"r"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$5"]},
    {"name": "CHARACTER$string$6", "symbols": [{"literal":"D"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$6"]},
    {"name": "ACTION$string$1", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"e"}, {"literal":"e"}, {"literal":"p"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$1"]},
    {"name": "ACTION$string$2", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$2"]},
    {"name": "ACTION$string$3", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$3"]},
    {"name": "ACTION$string$4", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$4"]},
    {"name": "ACTION$string$5", "symbols": [{"literal":"p"}, {"literal":"u"}, {"literal":"t"}, {"literal":"s"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"h"}, {"literal":"o"}, {"literal":"b"}, {"literal":"o"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"i"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$5"]},
    {"name": "ORDER$string$1", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORDER", "symbols": ["ORDER$string$1"]},
    {"name": "ORDER$string$2", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORDER", "symbols": ["ORDER$string$2"]},
    {"name": "ORDER$string$3", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORDER", "symbols": ["ORDER$string$3"]},
    {"name": "ORDER$string$4", "symbols": [{"literal":"p"}, {"literal":"u"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":"g"}, {"literal":"e"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORDER", "symbols": ["ORDER$string$4"]},
    {"name": "AUG$string$1", "symbols": [{"literal":"u"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUG", "symbols": ["AUG$string$1", "_", "NOUN"]},
    {"name": "AUG$string$2", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUG", "symbols": ["AUG$string$2", "_", "NOUN"]},
    {"name": "AUG$string$3", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUG", "symbols": ["AUG$string$3", "_", "NOUN"]},
    {"name": "AUG$string$4", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":"t"}, {"literal":"t"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUG", "symbols": ["AUG$string$4", "_", "NOUN"]},
    {"name": "ADV1$string$1", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV1", "symbols": ["ADV1$string$1"]},
    {"name": "ADV1$string$2", "symbols": [{"literal":"q"}, {"literal":"u"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV1", "symbols": ["ADV1$string$2"]},
    {"name": "ADV1$string$3", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV1", "symbols": ["ADV1$string$3"]},
    {"name": "ADV1$string$4", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"u"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV1", "symbols": ["ADV1$string$4"]},
    {"name": "NOUN$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"r"}, {"literal":"o"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOUN", "symbols": ["NOUN$string$1"]},
    {"name": "NOUN$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"u"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOUN", "symbols": ["NOUN$string$2"]},
    {"name": "NOUN$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOUN", "symbols": ["NOUN$string$3"]},
    {"name": "NOUN$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"i"}, {"literal":"s"}, {"literal":"s"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOUN", "symbols": ["NOUN$string$4"]},
    {"name": "ADV2$string$1", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV2", "symbols": ["ADV2$string$1"]},
    {"name": "ADV2$string$2", "symbols": [{"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":"m"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV2", "symbols": ["ADV2$string$2"]},
    {"name": "ADV2$string$3", "symbols": [{"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV2", "symbols": ["ADV2$string$3"]},
    {"name": "ADV2$string$4", "symbols": [{"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV2", "symbols": ["ADV2$string$4"]},
    {"name": "QUIP$string$1", "symbols": [{"literal":"L"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"v"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUIP", "symbols": ["QUIP$string$1"]},
    {"name": "QUIP$string$2", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"e"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUIP", "symbols": ["QUIP$string$2"]},
    {"name": "QUIP$string$3", "symbols": [{"literal":"G"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"w"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUIP", "symbols": ["QUIP$string$3"]},
    {"name": "QUIP$string$4", "symbols": [{"literal":"E"}, {"literal":"x"}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUIP", "symbols": ["QUIP$string$4"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
