// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN$ebnf$1$subexpression$1", "symbols": ["INTERJECTION", "_"]},
    {"name": "MAIN$ebnf$1", "symbols": ["MAIN$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "MAIN$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "MAIN", "symbols": ["MAIN$ebnf$1", "STATEMENT", {"literal":".","pos":13}]},
    {"name": "MAIN$string$1", "symbols": [{"literal":"Q"}, {"literal":"u"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN", "symbols": ["MAIN$string$1", "_", "QUESTION_PHRASE", {"literal":"?","pos":23}]},
    {"name": "STATEMENT$string$1", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATEMENT", "symbols": ["STATEMENT", "STATEMENT$string$1", "_", "STATEMENT"]},
    {"name": "STATEMENT$ebnf$1$subexpression$1", "symbols": ["_", "PREP_PHRASE"]},
    {"name": "STATEMENT$ebnf$1", "symbols": ["STATEMENT$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "STATEMENT$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "STATEMENT", "symbols": ["SUPERLATIVE_PHRASE", "STATEMENT$ebnf$1"]},
    {"name": "SUPERLATIVE_PHRASE$subexpression$1$ebnf$1$subexpression$1", "symbols": ["ADV", "_"]},
    {"name": "SUPERLATIVE_PHRASE$subexpression$1$ebnf$1", "symbols": ["SUPERLATIVE_PHRASE$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "SUPERLATIVE_PHRASE$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "SUPERLATIVE_PHRASE$subexpression$1$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUPERLATIVE_PHRASE$subexpression$1", "symbols": ["POSITIVE_DESC", "_", "SUPERLATIVE_PHRASE$subexpression$1$ebnf$1", "SUPERLATIVE_PHRASE$subexpression$1$string$1", "_", "POSITIVE_SUPERLATIVE"]},
    {"name": "SUPERLATIVE_PHRASE$subexpression$1$ebnf$2$subexpression$1", "symbols": ["ADV", "_"]},
    {"name": "SUPERLATIVE_PHRASE$subexpression$1$ebnf$2", "symbols": ["SUPERLATIVE_PHRASE$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "SUPERLATIVE_PHRASE$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "SUPERLATIVE_PHRASE$subexpression$1$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUPERLATIVE_PHRASE$subexpression$1", "symbols": ["NEGATIVE_DESC", "_", "SUPERLATIVE_PHRASE$subexpression$1$ebnf$2", "SUPERLATIVE_PHRASE$subexpression$1$string$2", "_", "NEGATIVE_SUPERLATIVE"]},
    {"name": "SUPERLATIVE_PHRASE$subexpression$2", "symbols": ["THING"]},
    {"name": "SUPERLATIVE_PHRASE$subexpression$2$string$1", "symbols": [{"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUPERLATIVE_PHRASE$subexpression$2", "symbols": ["SUPERLATIVE_PHRASE$subexpression$2$string$1", "_", "ACTIVITY"]},
    {"name": "SUPERLATIVE_PHRASE", "symbols": ["SUPERLATIVE_PHRASE$subexpression$1", "_", "SUPERLATIVE_PHRASE$subexpression$2"]},
    {"name": "POSITIVE_DESC$string$1", "symbols": [{"literal":"I"}, {"literal":"'"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITIVE_DESC", "symbols": ["POSITIVE_DESC$string$1"]},
    {"name": "POSITIVE_DESC$string$2", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITIVE_DESC", "symbols": ["FRIEND", "_", "POSITIVE_DESC$string$2"]},
    {"name": "NEGATIVE_DESC$string$1", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NEGATIVE_DESC", "symbols": ["ENEMY", "_", "NEGATIVE_DESC$string$1"]},
    {"name": "QUESTION_PHRASE$ebnf$1$subexpression$1", "symbols": ["INTERROGATIVE", "_"]},
    {"name": "QUESTION_PHRASE$ebnf$1", "symbols": ["QUESTION_PHRASE$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "QUESTION_PHRASE$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "QUESTION_PHRASE", "symbols": ["QUESTION_PHRASE$ebnf$1", "PERMISSION_QUESTION"]},
    {"name": "QUESTION_PHRASE$string$1", "symbols": [{"literal":"I"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION_PHRASE", "symbols": ["QUESTION_PHRASE$string$1", "_", "STATEMENT", {"literal":",","pos":151}, "_", "PERMISSION_QUESTION"]},
    {"name": "PERMISSION_QUESTION", "symbols": ["PERMISSION_VERB", "_", {"literal":"I","pos":165}, "_", "VERB_PHRASE"]},
    {"name": "VERB_PHRASE", "symbols": ["VERB", "_", "DET", "_", "OBJECT"]},
    {"name": "VERB_PHRASE$string$1", "symbols": [{"literal":"b"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB_PHRASE$subexpression$1", "symbols": ["DET", "_", "THING"]},
    {"name": "VERB_PHRASE$subexpression$1", "symbols": ["STATE"]},
    {"name": "VERB_PHRASE", "symbols": ["VERB_PHRASE$string$1", "_", "VERB_PHRASE$subexpression$1"]},
    {"name": "PREP_PHRASE", "symbols": ["PREP_PLACE_PHRASE"]},
    {"name": "PREP_PHRASE", "symbols": ["PREP_GROUP_PHRASE"]},
    {"name": "PREP_PHRASE", "symbols": ["PREP_GROUP_PHRASE", "_", "PREP_PLACE_PHRASE"]},
    {"name": "PREP_PLACE_PHRASE$string$1", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREP_PLACE_PHRASE", "symbols": ["PREP_PLACE_PHRASE$string$1", "_", "PLACE"]},
    {"name": "PREP_GROUP_PHRASE$string$1", "symbols": [{"literal":"o"}, {"literal":"u"}, {"literal":"t"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREP_GROUP_PHRASE", "symbols": ["PREP_GROUP_PHRASE$string$1", "_", "GROUP"]},
    {"name": "POSITIVE_SUPERLATIVE$string$1", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITIVE_SUPERLATIVE", "symbols": ["POSITIVE_SUPERLATIVE$string$1"]},
    {"name": "POSITIVE_SUPERLATIVE$string$2", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITIVE_SUPERLATIVE", "symbols": ["POSITIVE_SUPERLATIVE$string$2"]},
    {"name": "POSITIVE_SUPERLATIVE$string$3", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITIVE_SUPERLATIVE", "symbols": ["POSITIVE_SUPERLATIVE$string$3"]},
    {"name": "POSITIVE_SUPERLATIVE$string$4", "symbols": [{"literal":"e"}, {"literal":"x"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITIVE_SUPERLATIVE", "symbols": ["POSITIVE_SUPERLATIVE$string$4"]},
    {"name": "POSITIVE_SUPERLATIVE$string$5", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"y"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITIVE_SUPERLATIVE", "symbols": ["POSITIVE_SUPERLATIVE$string$5"]},
    {"name": "NEGATIVE_SUPERLATIVE$string$1", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NEGATIVE_SUPERLATIVE", "symbols": ["NEGATIVE_SUPERLATIVE$string$1"]},
    {"name": "NEGATIVE_SUPERLATIVE$string$2", "symbols": [{"literal":"d"}, {"literal":"u"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NEGATIVE_SUPERLATIVE", "symbols": ["NEGATIVE_SUPERLATIVE$string$2"]},
    {"name": "NEGATIVE_SUPERLATIVE$string$3", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NEGATIVE_SUPERLATIVE", "symbols": ["NEGATIVE_SUPERLATIVE$string$3"]},
    {"name": "INTERJECTION$string$1", "symbols": [{"literal":"p"}, {"literal":"f"}, {"literal":"f"}, {"literal":"t"}, {"literal":"."}, {"literal":"."}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTERJECTION", "symbols": ["INTERJECTION$string$1"]},
    {"name": "INTERJECTION$string$2", "symbols": [{"literal":"F"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTERJECTION", "symbols": ["INTERJECTION$string$2"]},
    {"name": "DET$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DET", "symbols": ["DET$string$1"]},
    {"name": "DET", "symbols": ["POSSESSIVE"]},
    {"name": "POSSESSIVE$string$1", "symbols": [{"literal":"'"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSSESSIVE", "symbols": ["PERSON", "POSSESSIVE$string$1"]},
    {"name": "STATE$string$1", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE", "symbols": ["STATE$string$1"]},
    {"name": "STATE", "symbols": ["POSSESSIVE", "_", "THING"]},
    {"name": "THING$string$1", "symbols": [{"literal":"w"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"l"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THING", "symbols": ["THING$string$1"]},
    {"name": "THING$string$2", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"r"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THING", "symbols": ["THING$string$2"]},
    {"name": "THING$string$3", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THING", "symbols": ["THING$string$3"]},
    {"name": "THING$string$4", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THING", "symbols": ["THING$string$4"]},
    {"name": "THING$string$5", "symbols": [{"literal":"B"}, {"literal":"e"}, {"literal":"l"}, {"literal":"s"}, {"literal":"n"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THING", "symbols": ["THING$string$5"]},
    {"name": "THING$string$6", "symbols": [{"literal":"A"}, {"literal":"s"}, {"literal":"s"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"R"}, {"literal":"e"}, {"literal":"g"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"M"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THING", "symbols": ["THING$string$6"]},
    {"name": "PLACE$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":"f"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$1"]},
    {"name": "PLACE$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"b"}, {"literal":"u"}, {"literal":"i"}, {"literal":"l"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$2"]},
    {"name": "PLACE$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"r"}, {"literal":"o"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$3"]},
    {"name": "PLACE$string$4", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"S"}, {"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$4"]},
    {"name": "PLACE$string$5", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$5"]},
    {"name": "GROUP$string$1", "symbols": [{"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GROUP", "symbols": ["GROUP$string$1"]},
    {"name": "GROUP$string$2", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GROUP", "symbols": ["GROUP$string$2"]},
    {"name": "GROUP$string$3", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GROUP", "symbols": ["GROUP$string$3"]},
    {"name": "GROUP$string$4", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GROUP", "symbols": ["GROUP$string$4"]},
    {"name": "OBJECT$string$1", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$1"]},
    {"name": "OBJECT$string$2", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$2"]},
    {"name": "OBJECT$string$3", "symbols": [{"literal":"p"}, {"literal":"h"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$3"]},
    {"name": "OBJECT$string$4", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"o"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$4"]},
    {"name": "ACTIVITY$string$1", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"e"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTIVITY", "symbols": ["ACTIVITY$string$1"]},
    {"name": "ACTIVITY$string$2", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTIVITY", "symbols": ["ACTIVITY$string$2"]},
    {"name": "PERSON", "symbols": ["FRIEND"]},
    {"name": "PERSON", "symbols": ["ENEMY"]},
    {"name": "FRIEND$string$1", "symbols": [{"literal":"M"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FRIEND", "symbols": ["FRIEND$string$1"]},
    {"name": "FRIEND$string$2", "symbols": [{"literal":"M"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FRIEND", "symbols": ["FRIEND$string$2"]},
    {"name": "FRIEND$string$3", "symbols": [{"literal":"A"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"l"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FRIEND", "symbols": ["FRIEND$string$3"]},
    {"name": "ENEMY$string$1", "symbols": [{"literal":"K"}, {"literal":"e"}, {"literal":"v"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENEMY", "symbols": ["ENEMY$string$1"]},
    {"name": "ENEMY$string$2", "symbols": [{"literal":"O"}, {"literal":"s"}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENEMY", "symbols": ["ENEMY$string$2"]},
    {"name": "ENEMY$string$3", "symbols": [{"literal":"A"}, {"literal":"n"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENEMY", "symbols": ["ENEMY$string$3"]},
    {"name": "ENEMY$string$4", "symbols": [{"literal":"J"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENEMY", "symbols": ["ENEMY$string$4"]},
    {"name": "ENEMY$string$5", "symbols": [{"literal":"P"}, {"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENEMY", "symbols": ["ENEMY$string$5"]},
    {"name": "ADV$string$1", "symbols": [{"literal":"c"}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV", "symbols": ["ADV$string$1"]},
    {"name": "ADV$string$2", "symbols": [{"literal":"e"}, {"literal":"a"}, {"literal":"s"}, {"literal":"i"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV", "symbols": ["ADV$string$2"]},
    {"name": "ADV$string$3", "symbols": [{"literal":"o"}, {"literal":"b"}, {"literal":"v"}, {"literal":"i"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV", "symbols": ["ADV$string$3"]},
    {"name": "ADV$string$4", "symbols": [{"literal":"b"}, {"literal":"y"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADV", "symbols": ["ADV$string$4"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"v"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"g"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"c"}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$2"]},
    {"name": "VERB$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$3"]},
    {"name": "VERB$string$4", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$4"]},
    {"name": "VERB$string$5", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$5"]},
    {"name": "PERMISSION_VERB$string$1", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERMISSION_VERB", "symbols": ["PERMISSION_VERB$string$1"]},
    {"name": "PERMISSION_VERB$string$2", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERMISSION_VERB", "symbols": ["PERMISSION_VERB$string$2"]},
    {"name": "PERMISSION_VERB$string$3", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERMISSION_VERB", "symbols": ["PERMISSION_VERB$string$3"]},
    {"name": "PERMISSION_VERB$string$4", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERMISSION_VERB", "symbols": ["PERMISSION_VERB$string$4"]},
    {"name": "INTERROGATIVE$string$1", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTERROGATIVE", "symbols": ["INTERROGATIVE$string$1"]},
    {"name": "INTERROGATIVE$string$2", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTERROGATIVE", "symbols": ["INTERROGATIVE$string$2"]},
    {"name": "INTERROGATIVE$string$3", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTERROGATIVE", "symbols": ["INTERROGATIVE$string$3"]},
    {"name": "INTERROGATIVE$string$4", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTERROGATIVE", "symbols": ["INTERROGATIVE$string$4"]},
    {"name": "_", "symbols": [{"literal":" ","pos":536}]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
