// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["STATEMENT", {"literal":".","pos":6}]},
    {"name": "MAIN", "symbols": ["QUESTION", {"literal":"?","pos":12}]},
    {"name": "MAIN", "symbols": ["EXCLAMATION", {"literal":"!","pos":18}]},
    {"name": "_", "symbols": [{"literal":" ","pos":24}]},
    {"name": "STATEMENT", "symbols": ["SUBJECT", "_", "ACTION"]},
    {"name": "STATEMENT$string$1", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATEMENT", "symbols": ["SUBJECT", "_", "ACTION", "_", "STATEMENT$string$1", "_", "CHARACTER"]},
    {"name": "STATEMENT", "symbols": ["SUBJECT", "_", "ACTION", "_", "CONJUNCTION", "_", "STATEMENT"]},
    {"name": "QUESTION$string$1", "symbols": [{"literal":"D"}, {"literal":"i"}, {"literal":"d"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$1", "_", "ACTION", "_", "PREPOSITION", "_", "PLACE"]},
    {"name": "QUESTION$string$2", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"u"}, {"literal":"s"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$2", "_", "OBJECT"]},
    {"name": "QUESTION$string$3", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"m"}, {"literal":"u"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$3", "_", "OBJECT"]},
    {"name": "EXCLAMATION", "symbols": ["SUBJECT", "_", "ACTION", "_", "PREPOSITION", "_", "PLACE"]},
    {"name": "SUBJECT", "symbols": [{"literal":"I","pos":124}]},
    {"name": "SUBJECT$string$1", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJECT", "symbols": ["SUBJECT$string$1"]},
    {"name": "SUBJECT$string$2", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJECT", "symbols": ["SUBJECT$string$2"]},
    {"name": "SUBJECT$string$3", "symbols": [{"literal":"W"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJECT", "symbols": ["SUBJECT$string$3"]},
    {"name": "ACTION$string$1", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$1", "_", "OBJECT"]},
    {"name": "ACTION$string$2", "symbols": [{"literal":"e"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$2", "_", "OBJECT"]},
    {"name": "ACTION$string$3", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$3", "_", "OBJECT"]},
    {"name": "ACTION$string$4", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$4", "_", "OBJECT"]},
    {"name": "ACTION$string$5", "symbols": [{"literal":"D"}, {"literal":"i"}, {"literal":"s"}, {"literal":"n"}, {"literal":"e"}, {"literal":"y"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$5", "_", "CHARACTER"]},
    {"name": "ACTION$string$6", "symbols": [{"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$6", "_", "RIDE"]},
    {"name": "PLACE$string$1", "symbols": [{"literal":"D"}, {"literal":"i"}, {"literal":"s"}, {"literal":"n"}, {"literal":"e"}, {"literal":"y"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$1"]},
    {"name": "PLACE$string$2", "symbols": [{"literal":"D"}, {"literal":"i"}, {"literal":"s"}, {"literal":"n"}, {"literal":"e"}, {"literal":"y"}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$2"]},
    {"name": "PLACE$string$3", "symbols": [{"literal":"C"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"n"}, {"literal":"i"}, {"literal":"a"}, {"literal":" "}, {"literal":"A"}, {"literal":"d"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$3"]},
    {"name": "PLACE$string$4", "symbols": [{"literal":"R"}, {"literal":"a"}, {"literal":"d"}, {"literal":"i"}, {"literal":"a"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"S"}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$4"]},
    {"name": "PLACE$string$5", "symbols": [{"literal":"A"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":" "}, {"literal":"C"}, {"literal":"a"}, {"literal":"m"}, {"literal":"p"}, {"literal":"u"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$5"]},
    {"name": "PLACE$string$6", "symbols": [{"literal":"S"}, {"literal":"t"}, {"literal":"a"}, {"literal":"r"}, {"literal":" "}, {"literal":"W"}, {"literal":"a"}, {"literal":"r"}, {"literal":"s"}, {"literal":" "}, {"literal":"L"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$6"]},
    {"name": "PLACE$string$7", "symbols": [{"literal":"E"}, {"literal":"n"}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"T"}, {"literal":"i"}, {"literal":"k"}, {"literal":"i"}, {"literal":" "}, {"literal":"R"}, {"literal":"o"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$7"]},
    {"name": "PLACE$string$8", "symbols": [{"literal":"r"}, {"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"r"}, {"literal":"o"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$8"]},
    {"name": "OBJECT$string$1", "symbols": [{"literal":"F"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":"P"}, {"literal":"a"}, {"literal":"s"}, {"literal":"s"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$1"]},
    {"name": "OBJECT$string$2", "symbols": [{"literal":"M"}, {"literal":"a"}, {"literal":"g"}, {"literal":"i"}, {"literal":"c"}, {"literal":" "}, {"literal":"B"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$2"]},
    {"name": "OBJECT$string$3", "symbols": [{"literal":"M"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":" "}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$3"]},
    {"name": "OBJECT$string$4", "symbols": [{"literal":"D"}, {"literal":"o"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"W"}, {"literal":"h"}, {"literal":"i"}, {"literal":"p"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$4"]},
    {"name": "OBJECT$string$5", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"n"}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$5"]},
    {"name": "OBJECT$string$6", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$6"]},
    {"name": "OBJECT$string$7", "symbols": [{"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$7"]},
    {"name": "OBJECT$string$8", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"x"}, {"literal":"i"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$8"]},
    {"name": "OBJECT$string$9", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"s"}, {"literal":"a"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$9"]},
    {"name": "PREPOSITION$string$1", "symbols": [{"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$1"]},
    {"name": "PREPOSITION$string$2", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$2"]},
    {"name": "RIDE$string$1", "symbols": [{"literal":"S"}, {"literal":"p"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"M"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RIDE", "symbols": ["RIDE$string$1"]},
    {"name": "RIDE$string$2", "symbols": [{"literal":"S"}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}, {"literal":" "}, {"literal":"M"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RIDE", "symbols": ["RIDE$string$2"]},
    {"name": "RIDE$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"T"}, {"literal":"o"}, {"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"T"}, {"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RIDE", "symbols": ["RIDE$string$3"]},
    {"name": "RIDE$string$4", "symbols": [{"literal":"I"}, {"literal":"t"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"A"}, {"literal":" "}, {"literal":"S"}, {"literal":"m"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"W"}, {"literal":"o"}, {"literal":"r"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RIDE", "symbols": ["RIDE$string$4"]},
    {"name": "RIDE$string$5", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"u"}, {"literal":"p"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RIDE", "symbols": ["RIDE$string$5"]},
    {"name": "CHARACTER$string$1", "symbols": [{"literal":"B"}, {"literal":"u"}, {"literal":"z"}, {"literal":"z"}, {"literal":" "}, {"literal":"L"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$1"]},
    {"name": "CHARACTER$string$2", "symbols": [{"literal":"M"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":" "}, {"literal":"M"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$2"]},
    {"name": "CHARACTER$string$3", "symbols": [{"literal":"E"}, {"literal":"l"}, {"literal":"s"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$3"]},
    {"name": "CHARACTER$string$4", "symbols": [{"literal":"R"}, {"literal":"a"}, {"literal":"p"}, {"literal":"u"}, {"literal":"n"}, {"literal":"z"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$4"]},
    {"name": "CHARACTER$string$5", "symbols": [{"literal":"L"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"M"}, {"literal":"c"}, {"literal":"Q"}, {"literal":"u"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$5"]},
    {"name": "CHARACTER$string$6", "symbols": [{"literal":"S"}, {"literal":"t"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$6"]},
    {"name": "CHARACTER$string$7", "symbols": [{"literal":"B"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$7"]},
    {"name": "CHARACTER$string$8", "symbols": [{"literal":"W"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$8"]},
    {"name": "CHARACTER$string$9", "symbols": [{"literal":"B"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}, {"literal":"f"}, {"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$9"]},
    {"name": "CHARACTER$string$10", "symbols": [{"literal":"M"}, {"literal":"u"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$10"]},
    {"name": "CHARACTER$string$11", "symbols": [{"literal":"S"}, {"literal":"i"}, {"literal":"m"}, {"literal":"b"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$11"]},
    {"name": "CHARACTER$string$12", "symbols": [{"literal":"T"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"B"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$12"]},
    {"name": "CONJUNCTION$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONJUNCTION", "symbols": ["CONJUNCTION$string$1"]},
    {"name": "CONJUNCTION$string$2", "symbols": [{"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONJUNCTION", "symbols": ["CONJUNCTION$string$2"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
