// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "START", "symbols": ["STARTUP_IDEA", {"literal":".","pos":6}]},
    {"name": "START", "symbols": ["STARTUP_IDEA", {"literal":"!","pos":12}]},
    {"name": "_", "symbols": [{"literal":" ","pos":18}]},
    {"name": "STARTUP_IDEA", "symbols": ["SUB", "_", "MOD", "_", "BUILD_VERB", "_", "OBJ", "_", "PURPOSE_CONJ", "_", "PURPOSE_VERB", "_", "PROBLEM_NOUNS", "_", "METHOD_VERB", "_", "TECH_NOUNS"]},
    {"name": "SUB", "symbols": [{"literal":"I","pos":62}]},
    {"name": "SUB$string$1", "symbols": [{"literal":"W"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$1"]},
    {"name": "SUB$string$2", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$2"]},
    {"name": "SUB$string$3", "symbols": [{"literal":"S"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"d"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"u"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$3"]},
    {"name": "MOD$string$1", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$1"]},
    {"name": "MOD$string$2", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$2"]},
    {"name": "MOD$string$3", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$3"]},
    {"name": "MOD$string$4", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$4"]},
    {"name": "BUILD_VERB$string$1", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BUILD_VERB", "symbols": ["BUILD_VERB$string$1"]},
    {"name": "BUILD_VERB$string$2", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"i"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BUILD_VERB", "symbols": ["BUILD_VERB$string$2"]},
    {"name": "BUILD_VERB$string$3", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"i"}, {"literal":"g"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BUILD_VERB", "symbols": ["BUILD_VERB$string$3"]},
    {"name": "BUILD_VERB$string$4", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BUILD_VERB", "symbols": ["BUILD_VERB$string$4"]},
    {"name": "OBJ$string$1", "symbols": [{"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$1"]},
    {"name": "OBJ$string$2", "symbols": [{"literal":"a"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"d"}, {"literal":"u"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$2"]},
    {"name": "OBJ$string$3", "symbols": [{"literal":"a"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"r"}, {"literal":"v"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$3"]},
    {"name": "OBJ$string$4", "symbols": [{"literal":"a"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"f"}, {"literal":"t"}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$4"]},
    {"name": "PURPOSE_CONJ$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PURPOSE_CONJ", "symbols": ["PURPOSE_CONJ$string$1"]},
    {"name": "PURPOSE_CONJ$string$2", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PURPOSE_CONJ", "symbols": ["PURPOSE_CONJ$string$2"]},
    {"name": "PURPOSE_VERB$string$1", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PURPOSE_VERB", "symbols": ["PURPOSE_VERB$string$1"]},
    {"name": "PURPOSE_VERB$string$2", "symbols": [{"literal":"t"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PURPOSE_VERB", "symbols": ["PURPOSE_VERB$string$2"]},
    {"name": "PURPOSE_VERB$string$3", "symbols": [{"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"t"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PURPOSE_VERB", "symbols": ["PURPOSE_VERB$string$3"]},
    {"name": "PROBLEM_NOUNS$string$1", "symbols": [{"literal":"g"}, {"literal":"l"}, {"literal":"o"}, {"literal":"b"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$1", "_", "COMBINING_CONJ", "_", "PROBLEM_NOUNS"]},
    {"name": "PROBLEM_NOUNS$string$2", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"m"}, {"literal":"i"}, {"literal":"c"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$2"]},
    {"name": "PROBLEM_NOUNS$string$3", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$3"]},
    {"name": "PROBLEM_NOUNS$string$4", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"e"}, {"literal":"d"}, {"literal":"u"}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$4"]},
    {"name": "PROBLEM_NOUNS$string$5", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"m"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$5"]},
    {"name": "PROBLEM_NOUNS$string$6", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"r"}, {"literal":"t"}, {"literal":"y"}, {"literal":" "}, {"literal":"d"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$6"]},
    {"name": "PROBLEM_NOUNS$string$7", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"i"}, {"literal":"s"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$7"]},
    {"name": "PROBLEM_NOUNS$string$8", "symbols": [{"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"o"}, {"literal":"m"}, {"literal":"i"}, {"literal":"c"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"b"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$8"]},
    {"name": "PROBLEM_NOUNS$string$9", "symbols": [{"literal":"n"}, {"literal":"u"}, {"literal":"c"}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$9"]},
    {"name": "PROBLEM_NOUNS$string$10", "symbols": [{"literal":"e"}, {"literal":"x"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"r"}, {"literal":"i"}, {"literal":"s"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$10", "_", "COMBINING_CONJ", "_", "PROBLEM_NOUNS"]},
    {"name": "PROBLEM_NOUNS$string$11", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"l"}, {"literal":"l"}, {"literal":"u"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$11"]},
    {"name": "PROBLEM_NOUNS$string$12", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"n"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"r"}, {"literal":"r"}, {"literal":"u"}, {"literal":"p"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$12", "_", "COMBINING_CONJ", "_", "PROBLEM_NOUNS"]},
    {"name": "PROBLEM_NOUNS$string$13", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"l"}, {"literal":"n"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"h"}, {"literal":"u"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$13"]},
    {"name": "PROBLEM_NOUNS$string$14", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$14", "_", "COMBINING_CONJ", "_", "PROBLEM_NOUNS"]},
    {"name": "PROBLEM_NOUNS$string$15", "symbols": [{"literal":"v"}, {"literal":"i"}, {"literal":"o"}, {"literal":"l"}, {"literal":"e"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$15"]},
    {"name": "PROBLEM_NOUNS$string$16", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$16", "_", "COMBINING_CONJ", "_", "PROBLEM_NOUNS"]},
    {"name": "PROBLEM_NOUNS$string$17", "symbols": [{"literal":"n"}, {"literal":"a"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$17"]},
    {"name": "PROBLEM_NOUNS$string$18", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"r"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROBLEM_NOUNS", "symbols": ["PROBLEM_NOUNS$string$18"]},
    {"name": "METHOD_VERB$string$1", "symbols": [{"literal":"u"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "METHOD_VERB", "symbols": ["METHOD_VERB$string$1"]},
    {"name": "METHOD_VERB$string$2", "symbols": [{"literal":"u"}, {"literal":"t"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"z"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "METHOD_VERB", "symbols": ["METHOD_VERB$string$2"]},
    {"name": "TECH_NOUNS$string$1", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$1", "_", "COMBINING_CONJ", "_", "TECH_NOUNS"]},
    {"name": "TECH_NOUNS$string$2", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"i"}, {"literal":"f"}, {"literal":"i"}, {"literal":"c"}, {"literal":"i"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$2", "_", "COMBINING_CONJ", "_", "TECH_NOUNS"]},
    {"name": "TECH_NOUNS$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"n"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$3"]},
    {"name": "TECH_NOUNS$string$4", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}, {"literal":"d"}, {"literal":"s"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"c"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$4"]},
    {"name": "TECH_NOUNS$string$5", "symbols": [{"literal":"r"}, {"literal":"o"}, {"literal":"b"}, {"literal":"o"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$5"]},
    {"name": "TECH_NOUNS$string$6", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":" "}, {"literal":"e"}, {"literal":"n"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$6"]},
    {"name": "TECH_NOUNS$string$7", "symbols": [{"literal":"b"}, {"literal":"l"}, {"literal":"o"}, {"literal":"c"}, {"literal":"k"}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$7"]},
    {"name": "TECH_NOUNS$string$8", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$8"]},
    {"name": "TECH_NOUNS$string$9", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"-"}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"u"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"f"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$9"]},
    {"name": "TECH_NOUNS$string$10", "symbols": [{"literal":"n"}, {"literal":"a"}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}, {"literal":"o"}, {"literal":"b"}, {"literal":"o"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$10", "_", "COMBINING_CONJ", "_", "TECH_NOUNS"]},
    {"name": "TECH_NOUNS$string$11", "symbols": [{"literal":"q"}, {"literal":"u"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"u"}, {"literal":"m"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"u"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$11", "_", "COMBINING_CONJ", "_", "TECH_NOUNS"]},
    {"name": "TECH_NOUNS$string$12", "symbols": [{"literal":"c"}, {"literal":"l"}, {"literal":"o"}, {"literal":"u"}, {"literal":"d"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"u"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$12"]},
    {"name": "TECH_NOUNS$string$13", "symbols": [{"literal":"b"}, {"literal":"l"}, {"literal":"o"}, {"literal":"c"}, {"literal":"k"}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$13"]},
    {"name": "TECH_NOUNS$string$14", "symbols": [{"literal":"N"}, {"literal":"F"}, {"literal":"T"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$14"]},
    {"name": "TECH_NOUNS$string$15", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"w"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"g"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$15"]},
    {"name": "TECH_NOUNS$string$16", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"b"}, {"literal":"u"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$16"]},
    {"name": "TECH_NOUNS$string$17", "symbols": [{"literal":"a"}, {"literal":"u"}, {"literal":"g"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$17"]},
    {"name": "TECH_NOUNS$string$18", "symbols": [{"literal":"3"}, {"literal":"D"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$18", "_", "COMBINING_CONJ", "_", "TECH_NOUNS"]},
    {"name": "TECH_NOUNS$string$19", "symbols": [{"literal":"5"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TECH_NOUNS", "symbols": ["TECH_NOUNS$string$19", "_", "COMBINING_CONJ", "_", "TECH_NOUNS"]},
    {"name": "COMBINING_CONJ$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMBINING_CONJ", "symbols": ["COMBINING_CONJ$string$1"]},
    {"name": "COMBINING_CONJ$string$2", "symbols": [{"literal":"p"}, {"literal":"l"}, {"literal":"u"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COMBINING_CONJ", "symbols": ["COMBINING_CONJ$string$2"]}
]
  , ParserStart: "START"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
