// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["INTRO", {"literal":".","pos":6}, "_", "SENTENCE", {"literal":".","pos":12}, "_", "ENDING", {"literal":".","pos":18}]},
    {"name": "MAIN", "symbols": ["INTRO", {"literal":".","pos":24}, "_", "QUESTION", {"literal":"?","pos":30}]},
    {"name": "MAIN$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN$string$2", "symbols": [{"literal":"!"}, {"literal":"!"}, {"literal":"!"}, {"literal":"!"}, {"literal":"!"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN", "symbols": ["MAIN$string$1", "_", "THREE_COUNT", "MAIN$string$2"]},
    {"name": "MAIN$string$3", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"i"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}, {"literal":"l"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN", "symbols": ["PERSON", "MAIN$string$3", "_", "SETLIST", {"literal":".","pos":52}, "_", "ENDING", {"literal":".","pos":58}]},
    {"name": "_", "symbols": [{"literal":" ","pos":64}]},
    {"name": "SENTENCE$string$1", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}, {"literal":" "}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE", "symbols": ["OBJECT", "_", "SENTENCE$string$1", "_", "ADJECTIVE"]},
    {"name": "SENTENCE$string$2", "symbols": [{"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"c"}, {"literal":"i"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE$string$3", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE", "symbols": ["SENTENCE$string$2", "_", "SUBJECT", "_", "SENTENCE$string$3", "_", "OBJECT"]},
    {"name": "SENTENCE$string$4", "symbols": [{"literal":"."}, {"literal":" "}, {"literal":"B"}, {"literal":"E"}, {"literal":"S"}, {"literal":"T"}, {"literal":"!"}, {"literal":" "}, {"literal":"S"}, {"literal":"E"}, {"literal":"C"}, {"literal":"T"}, {"literal":"I"}, {"literal":"O"}, {"literal":"N"}, {"literal":"!"}, {"literal":" "}, {"literal":"E"}, {"literal":"V"}, {"literal":"E"}, {"literal":"R"}, {"literal":"!"}, {"literal":"!"}, {"literal":"!"}, {"literal":"!"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE", "symbols": ["SECTION", "SENTENCE$string$4"]},
    {"name": "SENTENCE", "symbols": ["SUBJECT", "_", "VERB", "_", "FILLER", "_", "OBJECT"]},
    {"name": "SENTENCE", "symbols": ["OBJECT"]},
    {"name": "SENTENCE$string$5", "symbols": [{"literal":"M"}, {"literal":"y"}, {"literal":" "}, {"literal":"n"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE$string$6", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE", "symbols": ["SENTENCE$string$5", "_", "PERSON", "_", "SENTENCE$string$6", "_", "SECTION"]},
    {"name": "QUESTION", "symbols": ["Q_PHRASE", "_", "NOUN"]},
    {"name": "QUESTION$string$1", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION$string$2", "symbols": [{"literal":"m"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$1", "_", {"literal":"'","pos":153}, "NOUN", {"literal":"'","pos":157}, "_", "QUESTION$string$2"]},
    {"name": "QUESTION$string$3", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"'"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$3", "NOUN", {"literal":"'","pos":169}]},
    {"name": "QUESTION$string$4", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"g"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$4", "_", "PLACE"]},
    {"name": "THREE_COUNT", "symbols": ["NOUN", {"literal":"!","pos":185}, "_", "NOUN", {"literal":"!","pos":191}, "_", "NOUN"]},
    {"name": "THREE_COUNT", "symbols": ["NOUN", {"literal":"!","pos":201}, "_", "VERB", {"literal":"!","pos":207}, "_", "NOUN"]},
    {"name": "THREE_COUNT$string$1", "symbols": [{"literal":"!"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THREE_COUNT", "symbols": ["SUBJECT", "THREE_COUNT$string$1", "_", "PLACE"]},
    {"name": "THREE_COUNT$string$2", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"!"}, {"literal":" "}, {"literal":"T"}, {"literal":"o"}, {"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THREE_COUNT", "symbols": ["THREE_COUNT$string$2", "_", "SONG"]},
    {"name": "THREE_COUNT$string$3", "symbols": [{"literal":"W"}, {"literal":"H"}, {"literal":"E"}, {"literal":"R"}, {"literal":"E"}, {"literal":"!"}, {"literal":" "}, {"literal":"I"}, {"literal":"S"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THREE_COUNT", "symbols": ["THREE_COUNT$string$3", "_", "NOUN"]},
    {"name": "SETLIST", "symbols": ["SONG"]},
    {"name": "SETLIST$string$1", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETLIST", "symbols": ["SONG", "SETLIST$string$1", "_", "SONG"]},
    {"name": "SETLIST$string$2", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"b"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETLIST", "symbols": [{"literal":"'","pos":257}, "SONG", "SETLIST$string$2", "_", "ADJECTIVE", {"literal":"'","pos":267}]},
    {"name": "SETLIST$string$3", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETLIST", "symbols": ["SONG", "SETLIST$string$3", "_", "SONG"]},
    {"name": "SETLIST$string$4", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SETLIST", "symbols": ["SONG", "SETLIST$string$4", "_", "SONG"]},
    {"name": "NOUN", "symbols": ["SUBJECT"]},
    {"name": "NOUN", "symbols": ["OBJECT"]},
    {"name": "NOUN", "symbols": ["PLACE"]},
    {"name": "SUBJECT", "symbols": ["SECTION"]},
    {"name": "SUBJECT", "symbols": ["PERSON"]},
    {"name": "OBJECT", "symbols": ["MUSIC_WORD"]},
    {"name": "OBJECT$string$1", "symbols": [{"literal":"n"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$1"]},
    {"name": "OBJECT$string$2", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"n"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$2"]},
    {"name": "OBJECT$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["FILLER", "_", "OBJECT$string$3"]},
    {"name": "OBJECT", "symbols": ["ING", "_", "FILLER", "_", "OBJECT"]},
    {"name": "OBJECT$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"F"}, {"literal":"o"}, {"literal":"l"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$4"]},
    {"name": "OBJECT$string$5", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"D"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$5"]},
    {"name": "OBJECT$string$6", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"T"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$6"]},
    {"name": "OBJECT$string$7", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"o"}, {"literal":" "}, {"literal":"Q"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$7"]},
    {"name": "OBJECT$string$8", "symbols": [{"literal":"G"}, {"literal":"o"}, {"literal":"o"}, {"literal":"g"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$8"]},
    {"name": "OBJECT$string$9", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$9"]},
    {"name": "OBJECT$string$10", "symbols": [{"literal":"S"}, {"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$10"]},
    {"name": "OBJECT$string$11", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJECT", "symbols": ["OBJECT$string$11"]},
    {"name": "OBJECT", "symbols": ["SONG"]},
    {"name": "SONG$string$1", "symbols": [{"literal":"B"}, {"literal":"r"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"l"}, {"literal":"y"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONG", "symbols": ["SONG$string$1"]},
    {"name": "SONG$string$2", "symbols": [{"literal":"S"}, {"literal":"t"}, {"literal":"u"}, {"literal":"f"}, {"literal":"f"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONG", "symbols": ["SONG$string$2", "_", "SONG"]},
    {"name": "SONG$string$3", "symbols": [{"literal":"P"}, {"literal":"a"}, {"literal":"n"}, {"literal":"i"}, {"literal":"c"}, {"literal":" "}, {"literal":"S"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONG", "symbols": ["SONG$string$3"]},
    {"name": "SONG$string$4", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONG", "symbols": ["SONG$string$4", "_", "SONG"]},
    {"name": "SONG$string$5", "symbols": [{"literal":"A"}, {"literal":"R"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONG", "symbols": ["SONG$string$5"]},
    {"name": "SONG$string$6", "symbols": [{"literal":"P"}, {"literal":"u"}, {"literal":"n"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONG", "symbols": ["SONG$string$6"]},
    {"name": "SONG$string$7", "symbols": [{"literal":"C"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"J"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONG", "symbols": ["SONG$string$7"]},
    {"name": "SONG$string$8", "symbols": [{"literal":"H"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONG", "symbols": ["SONG$string$8"]},
    {"name": "SONG$string$9", "symbols": [{"literal":"R"}, {"literal":"o"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}, {"literal":" "}, {"literal":"G"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONG", "symbols": ["SONG$string$9"]},
    {"name": "SONG$string$10", "symbols": [{"literal":"O"}, {"literal":"n"}, {"literal":" "}, {"literal":"M"}, {"literal":"y"}, {"literal":" "}, {"literal":"W"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SONG", "symbols": ["SONG$string$10"]},
    {"name": "SECTION$string$1", "symbols": [{"literal":"A"}, {"literal":"B"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SECTION", "symbols": ["SECTION$string$1"]},
    {"name": "SECTION$string$2", "symbols": [{"literal":"C"}, {"literal":"P"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SECTION", "symbols": ["SECTION$string$2"]},
    {"name": "SECTION$string$3", "symbols": [{"literal":"A"}, {"literal":"l"}, {"literal":"t"}, {"literal":"o"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SECTION", "symbols": ["SECTION$string$3"]},
    {"name": "SECTION$string$4", "symbols": [{"literal":"T"}, {"literal":"e"}, {"literal":"n"}, {"literal":"r"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SECTION", "symbols": ["SECTION$string$4"]},
    {"name": "SECTION$string$5", "symbols": [{"literal":"B"}, {"literal":"o"}, {"literal":"n"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SECTION", "symbols": ["SECTION$string$5"]},
    {"name": "SECTION$string$6", "symbols": [{"literal":"M"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SECTION", "symbols": ["SECTION$string$6"]},
    {"name": "SECTION$string$7", "symbols": [{"literal":"T"}, {"literal":"ö"}, {"literal":"ö"}, {"literal":"b"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SECTION", "symbols": ["SECTION$string$7"]},
    {"name": "SECTION$string$8", "symbols": [{"literal":"T"}, {"literal":"r"}, {"literal":"u"}, {"literal":"m"}, {"literal":"p"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SECTION", "symbols": ["SECTION$string$8"]},
    {"name": "SECTION$string$9", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"D"}, {"literal":"o"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SECTION", "symbols": ["SECTION$string$9"]},
    {"name": "SECTION$string$10", "symbols": [{"literal":"A"}, {"literal":"x"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SECTION", "symbols": ["SECTION$string$10"]},
    {"name": "MUSIC_WORD$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC_WORD", "symbols": ["MUSIC_WORD$string$1"]},
    {"name": "MUSIC_WORD$string$2", "symbols": [{"literal":"s"}, {"literal":"y"}, {"literal":"n"}, {"literal":"c"}, {"literal":"o"}, {"literal":"p"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC_WORD", "symbols": ["MUSIC_WORD$string$2"]},
    {"name": "MUSIC_WORD$string$3", "symbols": [{"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"n"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC_WORD", "symbols": ["MUSIC_WORD$string$3"]},
    {"name": "MUSIC_WORD$string$4", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"l"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC_WORD", "symbols": ["SONG", "_", "MUSIC_WORD$string$4"]},
    {"name": "MUSIC_WORD$string$5", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC_WORD", "symbols": ["MUSIC_WORD$string$5"]},
    {"name": "MUSIC_WORD$string$6", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC_WORD", "symbols": ["MUSIC_WORD$string$6"]},
    {"name": "MUSIC_WORD$string$7", "symbols": [{"literal":"i"}, {"literal":"m"}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"v"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC_WORD", "symbols": ["MUSIC_WORD$string$7"]},
    {"name": "PERSON$string$1", "symbols": [{"literal":"f"}, {"literal":"l"}, {"literal":"i"}, {"literal":"q"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$1"]},
    {"name": "PERSON$string$2", "symbols": [{"literal":"K"}, {"literal":"e"}, {"literal":"y"}, {"literal":"v"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$2"]},
    {"name": "PERSON$string$3", "symbols": [{"literal":"B"}, {"literal":"i"}, {"literal":"t"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$3"]},
    {"name": "PERSON$string$4", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$4"]},
    {"name": "PERSON$string$5", "symbols": [{"literal":"X"}, {"literal":"u"}, {"literal":"l"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$5"]},
    {"name": "PERSON$string$6", "symbols": [{"literal":"Z"}, {"literal":"∞"}, {"literal":"g"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$6"]},
    {"name": "PERSON$string$7", "symbols": [{"literal":"P"}, {"literal":"o"}, {"literal":"g"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$7"]},
    {"name": "PERSON$string$8", "symbols": [{"literal":"B"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$8"]},
    {"name": "PERSON$string$9", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"f"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["FILLER", "_", "PERSON$string$9"]},
    {"name": "PERSON$string$10", "symbols": [{"literal":"P"}, {"literal":"s"}, {"literal":"y"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PERSON", "symbols": ["PERSON$string$10"]},
    {"name": "PLACE$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"S"}, {"literal":"h"}, {"literal":"a"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$1"]},
    {"name": "PLACE$string$2", "symbols": [{"literal":"M"}, {"literal":"a"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$2"]},
    {"name": "PLACE$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$3"]},
    {"name": "PLACE$string$4", "symbols": [{"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"r"}, {"literal":"m"}, {"literal":" "}, {"literal":"r"}, {"literal":"o"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PERSON", "PLACE$string$4"]},
    {"name": "PLACE$string$5", "symbols": [{"literal":"C"}, {"literal":"h"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"T"}, {"literal":"a"}, {"literal":"y"}, {"literal":"l"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"G"}, {"literal":"r"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$5"]},
    {"name": "Q_PHRASE$string$1", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Q_PHRASE", "symbols": ["Q_PHRASE$string$1"]},
    {"name": "Q_PHRASE$string$2", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Q_PHRASE", "symbols": ["Q_PHRASE$string$2"]},
    {"name": "Q_PHRASE$string$3", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Q_PHRASE", "symbols": ["Q_PHRASE$string$3"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"s"}, {"literal":"m"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["EMPHASIS", "_", "VERB$string$2"]},
    {"name": "VERB$string$3", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$3"]},
    {"name": "VERB$string$4", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$4"]},
    {"name": "VERB$string$5", "symbols": [{"literal":"y"}, {"literal":"e"}, {"literal":"e"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["EMPHASIS", "_", "VERB$string$5"]},
    {"name": "ADJECTIVE$string$1", "symbols": [{"literal":"S"}, {"literal":"A"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJECTIVE", "symbols": ["ADJECTIVE$string$1"]},
    {"name": "ADJECTIVE$string$2", "symbols": [{"literal":"p"}, {"literal":"s"}, {"literal":"y"}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"l"}, {"literal":"o"}, {"literal":"g"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"f"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJECTIVE", "symbols": ["ADJECTIVE$string$2"]},
    {"name": "ADJECTIVE$string$3", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"o"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJECTIVE", "symbols": ["ADJECTIVE$string$3"]},
    {"name": "ADJECTIVE", "symbols": ["EMPHASIS", "_", "ADJECTIVE"]},
    {"name": "ADJECTIVE$string$4", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJECTIVE", "symbols": ["ADJECTIVE$string$4"]},
    {"name": "ADJECTIVE$string$5", "symbols": [{"literal":"a"}, {"literal":"k"}, {"literal":"t"}, {"literal":"u"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJECTIVE", "symbols": ["ADJECTIVE$string$5"]},
    {"name": "ADJECTIVE$string$6", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"x"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJECTIVE", "symbols": ["ADJECTIVE$string$6"]},
    {"name": "ING$string$1", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ING", "symbols": ["ING$string$1", "SECTION"]},
    {"name": "ING$string$2", "symbols": [{"literal":"r"}, {"literal":"o"}, {"literal":"c"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ING", "symbols": ["ING$string$2"]},
    {"name": "ING$string$3", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ING", "symbols": ["ING$string$3"]},
    {"name": "ING$string$4", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"m"}, {"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ING", "symbols": ["ING$string$4", "SECTION"]},
    {"name": "FILLER$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FILLER", "symbols": ["FILLER$string$1"]},
    {"name": "FILLER$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FILLER", "symbols": ["FILLER$string$2"]},
    {"name": "FILLER$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FILLER", "symbols": ["FILLER$string$3"]},
    {"name": "EMPHASIS$string$1", "symbols": [{"literal":"a"}, {"literal":"b"}, {"literal":"s"}, {"literal":"o"}, {"literal":"l"}, {"literal":"u"}, {"literal":"t"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMPHASIS", "symbols": ["EMPHASIS$string$1"]},
    {"name": "EMPHASIS$string$2", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMPHASIS", "symbols": ["EMPHASIS$string$2"]},
    {"name": "EMPHASIS$string$3", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"d"}, {"literal":"-"}, {"literal":"d"}, {"literal":"a"}, {"literal":"m"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMPHASIS", "symbols": ["EMPHASIS$string$3"]},
    {"name": "INTRO$string$1", "symbols": [{"literal":"d"}, {"literal":"u"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTRO", "symbols": ["INTRO$string$1"]},
    {"name": "INTRO$string$2", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTRO", "symbols": ["INTRO$string$2"]},
    {"name": "INTRO$string$3", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}, {"literal":"l"}, {"literal":"y"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTRO", "symbols": ["INTRO$string$3", "_", "INTRO"]},
    {"name": "INTRO$string$4", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"g"}, {"literal":"u"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTRO", "symbols": ["INTRO$string$4"]},
    {"name": "INTRO$string$5", "symbols": [{"literal":"o"}, {"literal":"k"}, {"literal":"a"}, {"literal":"y"}, {"literal":","}, {"literal":" "}, {"literal":"b"}, {"literal":"u"}, {"literal":"t"}, {"literal":"."}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTRO", "symbols": ["INTRO$string$5"]},
    {"name": "ENDING$string$1", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENDING", "symbols": ["ENDING$string$1"]},
    {"name": "ENDING$string$2", "symbols": [{"literal":"R"}, {"literal":"T"}, {"literal":"F"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENDING", "symbols": ["ENDING$string$2"]},
    {"name": "ENDING$string$3", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENDING", "symbols": ["ENDING$string$3"]},
    {"name": "ENDING$string$4", "symbols": [{"literal":"W"}, {"literal":"T"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENDING", "symbols": ["ENDING$string$4"]},
    {"name": "ENDING$string$5", "symbols": [{"literal":"t"}, {"literal":"i"}, {"literal":"t"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"w"}, {"literal":" "}, {"literal":"s"}, {"literal":"k"}, {"literal":"a"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENDING", "symbols": ["ENDING$string$5"]},
    {"name": "ENDING$string$6", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"q"}, {"literal":"u"}, {"literal":"o"}, {"literal":"t"}, {"literal":"e"}, {"literal":"w"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENDING", "symbols": ["ENDING$string$6"]},
    {"name": "ENDING$string$7", "symbols": [{"literal":":"}, {"literal":"t"}, {"literal":"o"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENDING", "symbols": ["ENDING$string$7"]},
    {"name": "ENDING$string$8", "symbols": [{"literal":":"}, {"literal":"s"}, {"literal":"a"}, {"literal":"d"}, {"literal":"-"}, {"literal":"c"}, {"literal":"o"}, {"literal":"w"}, {"literal":"b"}, {"literal":"o"}, {"literal":"y"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENDING", "symbols": ["ENDING$string$8"]},
    {"name": "ENDING$string$9", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ENDING", "symbols": ["ENDING$string$9"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
