// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["REVIEW", {"literal":".","pos":7}]},
    {"name": "MAIN$string$1", "symbols": [{"literal":"R"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"u"}, {"literal":"p"}, {"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":":"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN", "symbols": ["MAIN$string$1", "UPDATE", {"literal":".","pos":15}]},
    {"name": "MAIN$string$2", "symbols": [{"literal":"I"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN", "symbols": ["MAIN$string$2", "STATEMENT", {"literal":".","pos":23}]},
    {"name": "_", "symbols": [{"literal":" ","pos":29}]},
    {"name": "REVIEW$string$1", "symbols": [{"literal":"W"}, {"literal":"o"}, {"literal":"w"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REVIEW", "symbols": ["REVIEW$string$1", "_", "REVIEW"]},
    {"name": "REVIEW$string$2", "symbols": [{"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REVIEW", "symbols": ["BOOK", "_", "EFFECT", "_", "REVIEW$string$2"]},
    {"name": "REVIEW$string$3", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"w"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"v"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REVIEW", "symbols": ["BOOK", "_", "REVIEW$string$3"]},
    {"name": "REVIEW$string$4", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"w"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"v"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REVIEW", "symbols": ["AUTHOR", "_", "REVIEW$string$4"]},
    {"name": "REVIEW$string$5", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"e"}, {"literal":"x"}, {"literal":"p"}, {"literal":"l"}, {"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REVIEW$string$6", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REVIEW$string$7", "symbols": [{"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REVIEW", "symbols": ["REVIEW$string$5", "_", "TOPIC", "_", "REVIEW$string$6", "_", "BOOK", "_", "EFFECT", "_", "REVIEW$string$7"]},
    {"name": "EFFECT$string$1", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"o"}, {"literal":"y"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EFFECT", "symbols": ["EFFECT$string$1"]},
    {"name": "EFFECT$string$2", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"v"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EFFECT", "symbols": ["EFFECT$string$2"]},
    {"name": "EFFECT$string$3", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"p"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EFFECT", "symbols": ["EFFECT$string$3"]},
    {"name": "EFFECT$string$4", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"u"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EFFECT", "symbols": ["EFFECT$string$4"]},
    {"name": "EFFECT$string$5", "symbols": [{"literal":"e"}, {"literal":"d"}, {"literal":"u"}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EFFECT", "symbols": ["EFFECT$string$5"]},
    {"name": "EFFECT$string$6", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EFFECT", "symbols": ["EFFECT$string$6"]},
    {"name": "EFFECT$string$7", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EFFECT", "symbols": ["EFFECT$string$7"]},
    {"name": "EFFECT$string$8", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"f"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EFFECT", "symbols": ["EFFECT$string$8"]},
    {"name": "EFFECT$string$9", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"r"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EFFECT", "symbols": ["EFFECT$string$9"]},
    {"name": "EFFECT$string$10", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"a"}, {"literal":"z"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EFFECT", "symbols": ["EFFECT$string$10"]},
    {"name": "UPDATE", "symbols": ["MANNER", "_", "ACTION", "_", "BOOK"]},
    {"name": "MANNER$string$1", "symbols": [{"literal":"C"}, {"literal":"u"}, {"literal":"r"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MANNER", "symbols": ["MANNER$string$1"]},
    {"name": "MANNER$string$2", "symbols": [{"literal":"S"}, {"literal":"t"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MANNER", "symbols": ["MANNER$string$2"]},
    {"name": "MANNER$string$3", "symbols": [{"literal":"A"}, {"literal":"l"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MANNER", "symbols": ["MANNER$string$3"]},
    {"name": "MANNER$string$4", "symbols": [{"literal":"H"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MANNER", "symbols": ["MANNER$string$4"]},
    {"name": "MANNER$string$5", "symbols": [{"literal":"S"}, {"literal":"i"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MANNER", "symbols": ["MANNER$string$5"]},
    {"name": "ACTION$string$1", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$1"]},
    {"name": "ACTION$string$2", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$2"]},
    {"name": "ACTION$string$3", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$3"]},
    {"name": "ACTION$string$4", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"v"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$4"]},
    {"name": "ACTION$string$5", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"n"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$5"]},
    {"name": "BOOK$string$1", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"G"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"G"}, {"literal":"a"}, {"literal":"t"}, {"literal":"s"}, {"literal":"b"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOK", "symbols": ["BOOK$string$1"]},
    {"name": "BOOK$string$2", "symbols": [{"literal":"G"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"E"}, {"literal":"x"}, {"literal":"p"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOK", "symbols": ["BOOK$string$2"]},
    {"name": "BOOK$string$3", "symbols": [{"literal":"W"}, {"literal":"u"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"H"}, {"literal":"e"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOK", "symbols": ["BOOK$string$3"]},
    {"name": "BOOK$string$4", "symbols": [{"literal":"C"}, {"literal":"r"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"P"}, {"literal":"u"}, {"literal":"n"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOK", "symbols": ["BOOK$string$4"]},
    {"name": "BOOK$string$5", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"s"}, {"literal":" "}, {"literal":"F"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"A"}, {"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOK", "symbols": ["BOOK$string$5"]},
    {"name": "BOOK$string$6", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"H"}, {"literal":"a"}, {"literal":"r"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"P"}, {"literal":"o"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOK", "symbols": ["BOOK$string$6"]},
    {"name": "BOOK$string$7", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"H"}, {"literal":"o"}, {"literal":"b"}, {"literal":"b"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOK", "symbols": ["BOOK$string$7"]},
    {"name": "BOOK$string$8", "symbols": [{"literal":"M"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"l"}, {"literal":"d"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOK", "symbols": ["BOOK$string$8"]},
    {"name": "BOOK$string$9", "symbols": [{"literal":"B"}, {"literal":"e"}, {"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOK", "symbols": ["BOOK$string$9"]},
    {"name": "STATEMENT$string$1", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATEMENT", "symbols": ["STATEMENT$string$1", "_", "AMOUNT", "_", "BOOKTYPE", "_", "TIME"]},
    {"name": "STATEMENT", "symbols": ["STATE", "_", "BOOKTYPE"]},
    {"name": "STATEMENT", "symbols": ["STATE", "_", "AUTHOR"]},
    {"name": "STATE$string$1", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"e"}, {"literal":"x"}, {"literal":"c"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE", "symbols": ["STATE$string$1"]},
    {"name": "STATE$string$2", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE", "symbols": ["STATE$string$2"]},
    {"name": "STATE$string$3", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE", "symbols": ["STATE$string$3"]},
    {"name": "STATE$string$4", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"g"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE", "symbols": ["STATE$string$4"]},
    {"name": "STATE$string$5", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE", "symbols": ["STATE$string$5"]},
    {"name": "STATE$string$6", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE", "symbols": ["STATE$string$6"]},
    {"name": "TIME$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$1"]},
    {"name": "TIME$string$2", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$2"]},
    {"name": "TIME$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$3"]},
    {"name": "TIME$string$4", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$4"]},
    {"name": "TIME$string$5", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$5"]},
    {"name": "TIME$string$6", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$6"]},
    {"name": "TIME$string$7", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"5"}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME", "symbols": ["TIME$string$7"]},
    {"name": "AMOUNT$string$1", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":" "}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AMOUNT", "symbols": ["AMOUNT$string$1"]},
    {"name": "AMOUNT$string$2", "symbols": [{"literal":"2"}, {"literal":"5"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AMOUNT", "symbols": ["AMOUNT$string$2"]},
    {"name": "AMOUNT$string$3", "symbols": [{"literal":"1"}, {"literal":"1"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AMOUNT", "symbols": ["AMOUNT$string$3"]},
    {"name": "AMOUNT", "symbols": [{"literal":"7","pos":336}]},
    {"name": "AMOUNT$string$4", "symbols": [{"literal":"n"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AMOUNT", "symbols": ["AMOUNT$string$4"]},
    {"name": "BOOKTYPE$string$1", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["BOOKTYPE$string$1"]},
    {"name": "BOOKTYPE$string$2", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["AUTHOR", "_", "BOOKTYPE$string$2"]},
    {"name": "BOOKTYPE$string$3", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["BOOKTYPE$string$3"]},
    {"name": "BOOKTYPE$string$4", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"e"}, {"literal":"t"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["BOOKTYPE$string$4"]},
    {"name": "BOOKTYPE$string$5", "symbols": [{"literal":"c"}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"s"}, {"literal":"i"}, {"literal":"c"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["BOOKTYPE$string$5"]},
    {"name": "BOOKTYPE$string$6", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["BOOKTYPE$string$6"]},
    {"name": "BOOKTYPE$string$7", "symbols": [{"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["BOOKTYPE$string$7"]},
    {"name": "BOOKTYPE$string$8", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"r"}, {"literal":"r"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["BOOKTYPE$string$8"]},
    {"name": "BOOKTYPE$string$9", "symbols": [{"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["BOOKTYPE$string$9"]},
    {"name": "BOOKTYPE$string$10", "symbols": [{"literal":"e"}, {"literal":"p"}, {"literal":"i"}, {"literal":"c"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"s"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["BOOKTYPE$string$10"]},
    {"name": "BOOKTYPE$string$11", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"n"}, {"literal":"-"}, {"literal":"f"}, {"literal":"i"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOKTYPE", "symbols": ["BOOKTYPE$string$11"]},
    {"name": "AUTHOR$string$1", "symbols": [{"literal":"K"}, {"literal":"a"}, {"literal":"z"}, {"literal":"u"}, {"literal":"o"}, {"literal":" "}, {"literal":"I"}, {"literal":"s"}, {"literal":"h"}, {"literal":"i"}, {"literal":"g"}, {"literal":"u"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUTHOR", "symbols": ["AUTHOR$string$1"]},
    {"name": "AUTHOR$string$2", "symbols": [{"literal":"H"}, {"literal":"a"}, {"literal":"r"}, {"literal":"u"}, {"literal":"k"}, {"literal":"i"}, {"literal":" "}, {"literal":"M"}, {"literal":"u"}, {"literal":"r"}, {"literal":"a"}, {"literal":"k"}, {"literal":"a"}, {"literal":"m"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUTHOR", "symbols": ["AUTHOR$string$2"]},
    {"name": "AUTHOR$string$3", "symbols": [{"literal":"M"}, {"literal":"a"}, {"literal":"y"}, {"literal":"a"}, {"literal":" "}, {"literal":"A"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"l"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUTHOR", "symbols": ["AUTHOR$string$3"]},
    {"name": "AUTHOR$string$4", "symbols": [{"literal":"J"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"B"}, {"literal":"a"}, {"literal":"l"}, {"literal":"d"}, {"literal":"w"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUTHOR", "symbols": ["AUTHOR$string$4"]},
    {"name": "AUTHOR$string$5", "symbols": [{"literal":"C"}, {"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"D"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUTHOR", "symbols": ["AUTHOR$string$5"]},
    {"name": "AUTHOR$string$6", "symbols": [{"literal":"J"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"A"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUTHOR", "symbols": ["AUTHOR$string$6"]},
    {"name": "AUTHOR$string$7", "symbols": [{"literal":"E"}, {"literal":"r"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"H"}, {"literal":"e"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"w"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUTHOR", "symbols": ["AUTHOR$string$7"]},
    {"name": "AUTHOR$string$8", "symbols": [{"literal":"C"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"N"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AUTHOR", "symbols": ["AUTHOR$string$8"]},
    {"name": "TOPIC$string$1", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"h"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$1"]},
    {"name": "TOPIC$string$2", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"s"}, {"literal":"c"}, {"literal":"u"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"i"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$2"]},
    {"name": "TOPIC$string$3", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$3"]},
    {"name": "TOPIC$string$4", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"d"}, {"literal":"h"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"n"}, {"literal":"o"}, {"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$4"]},
    {"name": "TOPIC$string$5", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"y"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$5"]},
    {"name": "TOPIC$string$6", "symbols": [{"literal":"i"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$6"]},
    {"name": "TOPIC$string$7", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$7"]},
    {"name": "TOPIC$string$8", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"x"}, {"literal":"u"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$8"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
