// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["HEARTBROKENSTATEMENT", {"literal":".","pos":6}]},
    {"name": "MAIN", "symbols": ["OVERTHINKINGQUESTION", {"literal":"?","pos":12}]},
    {"name": "MAIN", "symbols": ["HEARTBROKENEXCLAMATION", {"literal":"!","pos":17}]},
    {"name": "_", "symbols": [{"literal":" ","pos":23}]},
    {"name": "OVERTHINKINGQUESTION$string$1", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"y"}, {"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERTHINKINGQUESTION$string$2", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}, {"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERTHINKINGQUESTION$string$3", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERTHINKINGQUESTION", "symbols": ["OVERTHINKINGQUESTION$string$1", "_", "BREAKUPEE", "_", "OVERTHINKINGQUESTION$string$2", "_", "COPINGMECHANISMS", "_", "OVERTHINKINGQUESTION$string$3", "_", "OVERTHINKINGQUESTION"]},
    {"name": "OVERTHINKINGQUESTION$string$4", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERTHINKINGQUESTION$string$5", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERTHINKINGQUESTION$string$6", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERTHINKINGQUESTION", "symbols": ["OVERTHINKINGQUESTION$string$4", "_", "COPINGMECHANISMS", "_", "OVERTHINKINGQUESTION$string$5", "_", "OVERANALYZINGMODIFIER", "_", "OVERTHINKINGQUESTION$string$6", "_", "DRAMATICREACTIONS"]},
    {"name": "OVERTHINKINGQUESTION$string$7", "symbols": [{"literal":"W"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":" "}, {"literal":"a"}, {"literal":"w"}, {"literal":"a"}, {"literal":"y"}, {"literal":" "}, {"literal":"i"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERTHINKINGQUESTION$string$8", "symbols": [{"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERTHINKINGQUESTION$string$9", "symbols": [{"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERTHINKINGQUESTION$string$10", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERTHINKINGQUESTION", "symbols": ["OVERTHINKINGQUESTION$string$7", "_", "BREAKUPEE", "_", "OBSESSIVEADVERB", "_", "OVERTHINKINGQUESTION$string$8", "_", "SADSTUFF", "_", "OVERTHINKINGQUESTION$string$9", "_", "BREAKUPEE", "_", "OBSESSIVEADVERB", "_", "HEARTACHEVERB", "_", "OVERTHINKINGQUESTION$string$10"]},
    {"name": "HEARTBROKENSTATEMENT$string$1", "symbols": [{"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENSTATEMENT", "symbols": ["BREAKUPEE", "_", "HEARTBROKENSTATEMENT$string$1", "_", "OBSESSIVEADVERB", "_", "DRAMATICREACTIONS"]},
    {"name": "HEARTBROKENSTATEMENT$string$2", "symbols": [{"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENSTATEMENT$string$3", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"c"}, {"literal":"a"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENSTATEMENT$string$4", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENSTATEMENT", "symbols": ["BREAKUPEE", "_", "HEARTBROKENSTATEMENT$string$2", "_", "DRAMATICREACTIONS", "_", "HEARTBROKENSTATEMENT$string$3", "_", "BREAKUPEE", "_", "OBSESSIVEADVERB", "_", "HEARTACHEVERB", "_", "HEARTBROKENSTATEMENT$string$4"]},
    {"name": "HEARTBROKENSTATEMENT", "symbols": ["DRAMATICREACTIONS"]},
    {"name": "HEARTBROKENSTATEMENT$string$5", "symbols": [{"literal":"H"}, {"literal":"e"}, {"literal":"y"}, {"literal":" "}, {"literal":"S"}, {"literal":"i"}, {"literal":"r"}, {"literal":"i"}, {"literal":","}, {"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENSTATEMENT", "symbols": ["HEARTBROKENSTATEMENT$string$5", "_", "SADSTUFF"]},
    {"name": "HEARTBROKENSTATEMENT$string$6", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENSTATEMENT$string$7", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENSTATEMENT", "symbols": ["BREAKUPEE", "_", "HEARTBROKENSTATEMENT$string$6", "_", "THINGSTHATREMINDMEOFHIM", "_", "HEARTBROKENSTATEMENT$string$7"]},
    {"name": "HEARTBROKENEXCLAMATION$string$1", "symbols": [{"literal":"H"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENEXCLAMATION$string$2", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENEXCLAMATION", "symbols": ["HEARTBROKENEXCLAMATION$string$1", "_", "ANGRYADJECTIVE", "_", "HEARTBROKENEXCLAMATION$string$2", "_", "HEARTBROKENEXCLAMATION"]},
    {"name": "HEARTBROKENEXCLAMATION$string$3", "symbols": [{"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENEXCLAMATION", "symbols": ["BREAKUPEE", "_", "HEARTBROKENEXCLAMATION$string$3", "_", "OBSESSIVEADVERB", "_", "DRAMATICREACTIONS"]},
    {"name": "HEARTBROKENEXCLAMATION$string$4", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTBROKENEXCLAMATION", "symbols": [{"literal":"I","pos":222}, "_", "HEARTACHEVERB", "_", "HEARTBROKENEXCLAMATION$string$4"]},
    {"name": "ANGRYADJECTIVE$string$1", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYADJECTIVE", "symbols": ["ANGRYADJECTIVE$string$1"]},
    {"name": "ANGRYADJECTIVE$string$2", "symbols": [{"literal":"m"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYADJECTIVE", "symbols": ["ANGRYADJECTIVE$string$2"]},
    {"name": "ANGRYADJECTIVE$string$3", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYADJECTIVE", "symbols": ["ANGRYADJECTIVE$string$3"]},
    {"name": "ANGRYADJECTIVE$string$4", "symbols": [{"literal":"n"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYADJECTIVE", "symbols": ["ANGRYADJECTIVE$string$4"]},
    {"name": "ANGRYADJECTIVE$string$5", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"s"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYADJECTIVE", "symbols": ["ANGRYADJECTIVE$string$5"]},
    {"name": "ANGRYADJECTIVE$string$6", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYADJECTIVE", "symbols": ["ANGRYADJECTIVE$string$6"]},
    {"name": "BREAKUPEE", "symbols": [{"literal":"I","pos":252}]},
    {"name": "OBSESSIVEADVERB$string$1", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBSESSIVEADVERB", "symbols": ["OBSESSIVEADVERB$string$1"]},
    {"name": "OBSESSIVEADVERB$string$2", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBSESSIVEADVERB", "symbols": ["OBSESSIVEADVERB$string$2"]},
    {"name": "OBSESSIVEADVERB$string$3", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"e"}, {"literal":"q"}, {"literal":"u"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBSESSIVEADVERB", "symbols": ["OBSESSIVEADVERB$string$3"]},
    {"name": "OBSESSIVEADVERB$string$4", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBSESSIVEADVERB", "symbols": ["OBSESSIVEADVERB$string$4"]},
    {"name": "HEARTACHEVERB$string$1", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTACHEVERB", "symbols": ["HEARTACHEVERB$string$1"]},
    {"name": "HEARTACHEVERB$string$2", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTACHEVERB", "symbols": ["HEARTACHEVERB$string$2"]},
    {"name": "HEARTACHEVERB$string$3", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTACHEVERB", "symbols": ["HEARTACHEVERB$string$3"]},
    {"name": "HEARTACHEVERB$string$4", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HEARTACHEVERB", "symbols": ["HEARTACHEVERB$string$4"]},
    {"name": "DRAMATICREACTIONS$string$1", "symbols": [{"literal":"h"}, {"literal":"u"}, {"literal":"r"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRAMATICREACTIONS", "symbols": ["DRAMATICREACTIONS$string$1"]},
    {"name": "DRAMATICREACTIONS$string$2", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"y"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRAMATICREACTIONS", "symbols": ["DRAMATICREACTIONS$string$2"]},
    {"name": "DRAMATICREACTIONS$string$3", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"i"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"w"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRAMATICREACTIONS", "symbols": ["DRAMATICREACTIONS$string$3"]},
    {"name": "DRAMATICREACTIONS$string$4", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"y"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRAMATICREACTIONS", "symbols": ["DRAMATICREACTIONS$string$4"]},
    {"name": "DRAMATICREACTIONS$string$5", "symbols": [{"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"i"}, {"literal":"z"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRAMATICREACTIONS", "symbols": ["DRAMATICREACTIONS$string$5", "_", "THINGSTHATREMINDMEOFHIM"]},
    {"name": "DRAMATICREACTIONS$string$6", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"a"}, {"literal":"w"}, {"literal":"a"}, {"literal":"y"}, {"literal":" "}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRAMATICREACTIONS", "symbols": ["DRAMATICREACTIONS$string$6", "_", "THINGSTHATREMINDMEOFHIM"]},
    {"name": "OVERANALYZINGMODIFIER$string$1", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"o"}, {"literal":"r"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OVERANALYZINGMODIFIER", "symbols": ["OVERANALYZINGMODIFIER$string$1"]},
    {"name": "THINGSTHATREMINDMEOFHIM$string$1", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"c"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGSTHATREMINDMEOFHIM", "symbols": ["THINGSTHATREMINDMEOFHIM$string$1"]},
    {"name": "THINGSTHATREMINDMEOFHIM$string$2", "symbols": [{"literal":"m"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGSTHATREMINDMEOFHIM", "symbols": ["THINGSTHATREMINDMEOFHIM$string$2"]},
    {"name": "THINGSTHATREMINDMEOFHIM$string$3", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGSTHATREMINDMEOFHIM", "symbols": ["THINGSTHATREMINDMEOFHIM$string$3"]},
    {"name": "COPINGMECHANISMS$string$1", "symbols": [{"literal":"T"}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COPINGMECHANISMS", "symbols": ["COPINGMECHANISMS$string$1"]},
    {"name": "COPINGMECHANISMS$string$2", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"x"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"i"}, {"literal":"r"}, {"literal":" "}, {"literal":"d"}, {"literal":"y"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COPINGMECHANISMS", "symbols": ["COPINGMECHANISMS$string$2"]},
    {"name": "COPINGMECHANISMS$string$3", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COPINGMECHANISMS", "symbols": ["COPINGMECHANISMS$string$3"]},
    {"name": "SADSTUFF$string$1", "symbols": [{"literal":"T"}, {"literal":"a"}, {"literal":"y"}, {"literal":"l"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"s"}, {"literal":"w"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SADSTUFF", "symbols": ["SADSTUFF$string$1"]},
    {"name": "SADSTUFF$string$2", "symbols": [{"literal":"O"}, {"literal":"l"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"a"}, {"literal":" "}, {"literal":"R"}, {"literal":"o"}, {"literal":"d"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SADSTUFF", "symbols": ["SADSTUFF$string$2"]},
    {"name": "SADSTUFF$string$3", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"b"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"k"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SADSTUFF", "symbols": ["SADSTUFF$string$3"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
