// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["SENTENCE"]},
    {"name": "SENTENCE", "symbols": ["CANCONTINUE"]},
    {"name": "SENTENCE", "symbols": ["CANTCONTINUE"]},
    {"name": "CANCONTINUE", "symbols": ["OPTIONCANCONTINUE", {"literal":" ","pos":22}, "SENTENCE"]},
    {"name": "CANCONTINUE", "symbols": ["OPTIONCANCONTINUE"]},
    {"name": "OPTIONCANCONTINUE$string$1", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPTIONCANCONTINUE$string$2", "symbols": [{"literal":"?"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"f"}, {"literal":"i"}, {"literal":"n"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPTIONCANCONTINUE$string$3", "symbols": [{"literal":"s"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPTIONCANCONTINUE", "symbols": ["OPTIONCANCONTINUE$string$1", "POINTLESSACTIVITY", "OPTIONCANCONTINUE$string$2", "BADJOB", "OPTIONCANCONTINUE$string$3"]},
    {"name": "OPTIONCANCONTINUE$string$4", "symbols": [{"literal":"O"}, {"literal":"h"}, {"literal":" "}, {"literal":"y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"h"}, {"literal":","}, {"literal":" "}, {"literal":"I"}, {"literal":"’"}, {"literal":"m"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPTIONCANCONTINUE$string$5", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPTIONCANCONTINUE", "symbols": ["OPTIONCANCONTINUE$string$4", "BADJOB", "_", "OPTIONCANCONTINUE$string$5"]},
    {"name": "OPTIONCANCONTINUE$string$6", "symbols": [{"literal":"W"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPTIONCANCONTINUE$string$7", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":"t"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}, {"literal":"?"}, {"literal":" "}, {"literal":"S"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}, {"literal":"!"}, {"literal":" "}, {"literal":"I"}, {"literal":"'"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OPTIONCANCONTINUE", "symbols": ["OPTIONCANCONTINUE$string$6", "POINTLESSACTIVITY", "_", "OPTIONCANCONTINUE$string$7", "POINTLESSSSOCIALS", {"literal":".","pos":66}]},
    {"name": "ALPHAMALEACTIVITY$string$1", "symbols": [{"literal":"t"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"2"}, {"literal":"0"}, {"literal":" "}, {"literal":"u"}, {"literal":"n"}, {"literal":"i"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ALPHAMALEACTIVITY", "symbols": ["ALPHAMALEACTIVITY$string$1"]},
    {"name": "ALPHAMALEACTIVITY$string$2", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ALPHAMALEACTIVITY", "symbols": ["ALPHAMALEACTIVITY$string$2"]},
    {"name": "ALPHAMALEACTIVITY$string$3", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":" "}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"n"}, {"literal":"s"}, {"literal":"h"}, {"literal":"i"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ALPHAMALEACTIVITY", "symbols": ["ALPHAMALEACTIVITY$string$3"]},
    {"name": "ALPHAMALEACTIVITY$string$4", "symbols": [{"literal":"t"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"C"}, {"literal":"S"}, {"literal":"4"}, {"literal":"5"}, {"literal":"6"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ALPHAMALEACTIVITY", "symbols": ["ALPHAMALEACTIVITY$string$4"]},
    {"name": "ALPHAMALEACTIVITY$string$5", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"d"}, {"literal":"u"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"s"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ALPHAMALEACTIVITY", "symbols": ["ALPHAMALEACTIVITY$string$5"]},
    {"name": "ALPHAMALEACTIVITY$string$6", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"t"}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ALPHAMALEACTIVITY", "symbols": ["ALPHAMALEACTIVITY$string$6"]},
    {"name": "ALPHAMALEACTIVITY$string$7", "symbols": [{"literal":"u"}, {"literal":"p"}, {"literal":"d"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"u"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ALPHAMALEACTIVITY", "symbols": ["ALPHAMALEACTIVITY$string$7"]},
    {"name": "POINTLESSACTIVITY$string$1", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POINTLESSACTIVITY", "symbols": ["POINTLESSACTIVITY$string$1"]},
    {"name": "POINTLESSACTIVITY$string$2", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"o"}, {"literal":"t"}, {"literal":"b"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POINTLESSACTIVITY", "symbols": ["POINTLESSACTIVITY$string$2"]},
    {"name": "POINTLESSACTIVITY$string$3", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"n"}, {"literal":" "}, {"literal":"p"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"o"}, {"literal":"s"}, {"literal":"o"}, {"literal":"p"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POINTLESSACTIVITY", "symbols": ["POINTLESSACTIVITY$string$3"]},
    {"name": "POINTLESSACTIVITY$string$4", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"e"}, {"literal":"e"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POINTLESSACTIVITY", "symbols": ["POINTLESSACTIVITY$string$4"]},
    {"name": "POINTLESSACTIVITY$string$5", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"l"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POINTLESSACTIVITY", "symbols": ["POINTLESSACTIVITY$string$5"]},
    {"name": "POINTLESSSSOCIALS$string$1", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"L"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":"e"}, {"literal":"d"}, {"literal":"I"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POINTLESSSSOCIALS", "symbols": ["POINTLESSSSOCIALS$string$1"]},
    {"name": "POINTLESSSSOCIALS$string$2", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"W"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}, {"literal":"T"}, {"literal":"o"}, {"literal":"M"}, {"literal":"e"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POINTLESSSSOCIALS", "symbols": ["POINTLESSSSOCIALS$string$2"]},
    {"name": "POINTLESSSSOCIALS$string$3", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"l"}, {"literal":"l"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POINTLESSSSOCIALS", "symbols": ["POINTLESSSSOCIALS$string$3"]},
    {"name": "POINTLESSSSOCIALS$string$4", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"i"}, {"literal":"p"}, {"literal":"e"}, {"literal":" "}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POINTLESSSSOCIALS", "symbols": ["POINTLESSSSOCIALS$string$4"]},
    {"name": "_", "symbols": [{"literal":" ","pos":141}]},
    {"name": "BADJOB$string$1", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"r"}, {"literal":"v"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BADJOB", "symbols": ["BADJOB$string$1"]},
    {"name": "BADJOB$string$2", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BADJOB", "symbols": ["BADJOB$string$2"]},
    {"name": "BADJOB$string$3", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"c"}, {"literal":"i"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BADJOB", "symbols": ["BADJOB$string$3"]},
    {"name": "BADJOB$string$4", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BADJOB", "symbols": ["BADJOB$string$4"]},
    {"name": "GOODJOB$string$1", "symbols": [{"literal":"C"}, {"literal":"E"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GOODJOB", "symbols": ["GOODJOB$string$1"]},
    {"name": "GOODJOB$string$2", "symbols": [{"literal":"C"}, {"literal":"F"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GOODJOB", "symbols": ["GOODJOB$string$2"]},
    {"name": "GOODJOB$string$3", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GOODJOB", "symbols": ["GOODJOB$string$3"]},
    {"name": "GOODJOB$string$4", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"f"}, {"literal":"t"}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GOODJOB", "symbols": ["GOODJOB$string$4"]},
    {"name": "GOODJOB$string$5", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"w"}, {"literal":"y"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GOODJOB", "symbols": ["GOODJOB$string$5"]},
    {"name": "GOODJOB$string$6", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"c"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GOODJOB", "symbols": ["GOODJOB$string$6"]},
    {"name": "CANTCONTINUE", "symbols": ["SORRY"]},
    {"name": "CANTCONTINUE", "symbols": ["NEED"]},
    {"name": "CANTCONTINUE", "symbols": ["NOTIME"]},
    {"name": "CANTCONTINUE", "symbols": ["HOW"]},
    {"name": "SORRY$string$1", "symbols": [{"literal":"S"}, {"literal":"o"}, {"literal":"r"}, {"literal":"r"}, {"literal":"y"}, {"literal":","}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"’"}, {"literal":"t"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SORRY$string$2", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SORRY", "symbols": ["SORRY$string$1", "POINTLESSACTIVITY", "SORRY$string$2", "ALPHAMALEACTIVITY", {"literal":".","pos":217}]},
    {"name": "NEED$string$1", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NEED$string$2", "symbols": [{"literal":"!"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":"n"}, {"literal":"’"}, {"literal":"t"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NEED", "symbols": ["NEED$string$1", "ALPHAMALEACTIVITY", "_", "NEED$string$2", "BADJOB", {"literal":".","pos":233}]},
    {"name": "NOTIME$string$1", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOTIME$string$2", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"’"}, {"literal":"t"}, {"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOTIME", "symbols": ["NOTIME$string$1", "ALPHAMALEACTIVITY", "_", "NOTIME$string$2", "POINTLESSACTIVITY", {"literal":".","pos":249}]},
    {"name": "HOW$string$1", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"e"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW$string$2", "symbols": [{"literal":"i"}, {"literal":"f"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"’"}, {"literal":"t"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW", "symbols": ["HOW$string$1", "GOODJOB", "_", "HOW$string$2", "ALPHAMALEACTIVITY", {"literal":"!","pos":265}]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
