// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["SENTENCEANDQ", {"literal":"?","pos":6}]},
    {"name": "MAIN", "symbols": ["QUESTION", {"literal":"?","pos":12}]},
    {"name": "_", "symbols": [{"literal":" ","pos":18}]},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "OBJ", "_", "SUBVERB", "_", "PREDVERB", "_", "MOD"]},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "OBJ", "_", "SUBVERB", "_", "PREDVERB", "_", "TEMP"]},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "OBJ", "_", "SUBVERB", "_", "PREDVERB", "_", "MOD", "_", "TEMP"]},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "OBJ", "_", "SUBVERB", "_", "PREDVERB", "_", "LOCATION"]},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "OBJ", "_", "SUBVERB", "_", "PREDVERB", "_", "MOD", "_", "LOCATION"]},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "OBJ", "_", "SUBVERB", "_", "PREDVERB", "_", "TEMP", "_", "LOCATION"]},
    {"name": "QUESTION$string$1", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "OBJ", "_", "SUBVERB", "_", "PREDVERB", "_", "TEMP", "_", "LOCATION", "_", "QUESTION$string$1", "_", "GERUND"]},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "OBJ", "_", "SUBVERB", "_", "PREDVERB", "_", "MOD", "_", "TEMP", "_", "LOCATION"]},
    {"name": "QUESTION$string$2", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "OBJ", "_", "SUBVERB", "_", "PREDVERB", "_", "MOD", "_", "TEMP", "_", "LOCATION", "_", "QUESTION$string$2", "_", "GERUND"]},
    {"name": "QUESTION", "symbols": ["PREFACE", "_", "QUESTION"]},
    {"name": "PREFACE$string$1", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREFACE", "symbols": ["PREFACE$string$1"]},
    {"name": "PREFACE$string$2", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREFACE", "symbols": ["PREFACE$string$2"]},
    {"name": "PREFACE$string$3", "symbols": [{"literal":"W"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"t"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREFACE", "symbols": ["PREFACE$string$3"]},
    {"name": "PREFACE$string$4", "symbols": [{"literal":"J"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREFACE", "symbols": ["PREFACE$string$4"]},
    {"name": "PREFACE$string$5", "symbols": [{"literal":"O"}, {"literal":"u"}, {"literal":"t"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"c"}, {"literal":"u"}, {"literal":"r"}, {"literal":"i"}, {"literal":"o"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"y"}, {"literal":":"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREFACE", "symbols": ["PREFACE$string$5"]},
    {"name": "QUESTIONWORD$string$1", "symbols": [{"literal":"D"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONWORD", "symbols": ["QUESTIONWORD$string$1"]},
    {"name": "QUESTIONWORD$string$2", "symbols": [{"literal":"W"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONWORD", "symbols": ["QUESTIONWORD$string$2"]},
    {"name": "SENTENCEANDQ$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCEANDQ", "symbols": ["PREDSUB", "_", "ADJ", "_", "SENTENCEANDQ$string$1", "_", "INTENTIONS", "_", "QUESTION"]},
    {"name": "TEMP$string$1", "symbols": [{"literal":"t"}, {"literal":"o"}, {"literal":"n"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMP", "symbols": ["TEMP$string$1"]},
    {"name": "TEMP$string$2", "symbols": [{"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMP", "symbols": ["TEMP$string$2"]},
    {"name": "TEMP$string$3", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":"n"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMP", "symbols": ["TEMP$string$3"]},
    {"name": "TEMP$string$4", "symbols": [{"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMP", "symbols": ["TEMP$string$4"]},
    {"name": "TEMP$string$5", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"b"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMP", "symbols": ["TEMP$string$5"]},
    {"name": "LOCATION$string$1", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"E"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"m"}, {"literal":"p"}, {"literal":"u"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$1"]},
    {"name": "LOCATION$string$2", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"G"}, {"literal":"o"}, {"literal":"v"}, {"literal":"c"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$2"]},
    {"name": "LOCATION$string$3", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"E"}, {"literal":"V"}, {"literal":"G"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$3"]},
    {"name": "LOCATION$string$4", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"J"}, {"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$4"]},
    {"name": "LOCATION$string$5", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"C"}, {"literal":"r"}, {"literal":"o"}, {"literal":"M"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$5"]},
    {"name": "LOCATION$string$6", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"C"}, {"literal":"a"}, {"literal":"s"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$6"]},
    {"name": "LOCATION$string$7", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"S"}, {"literal":"o"}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$7"]},
    {"name": "LOCATION$string$8", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$8"]},
    {"name": "LOCATION$string$9", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"W"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"L"}, {"literal":"a"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$9"]},
    {"name": "LOCATION$string$10", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"C"}, {"literal":"e"}, {"literal":"d"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$10"]},
    {"name": "LOCATION$string$11", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"N"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$11"]},
    {"name": "LOCATION$string$12", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"M"}, {"literal":"i"}, {"literal":"r"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOCATION", "symbols": ["LOCATION$string$12"]},
    {"name": "PREDSUB$string$1", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDSUB", "symbols": ["PREDSUB$string$1"]},
    {"name": "PREDSUB$string$2", "symbols": [{"literal":"I"}, {"literal":"'"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDSUB", "symbols": ["PREDSUB$string$2"]},
    {"name": "INTENTIONS$string$1", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"f"}, {"literal":"u"}, {"literal":"n"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTENTIONS", "symbols": ["INTENTIONS$string$1"]},
    {"name": "INTENTIONS$string$2", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"n"}, {"literal":"a"}, {"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTENTIONS", "symbols": ["INTENTIONS$string$2"]},
    {"name": "INTENTIONS$string$3", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"f"}, {"literal":"e"}, {"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"l"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":"y"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTENTIONS", "symbols": ["INTENTIONS$string$3"]},
    {"name": "ADJ$string$1", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$1"]},
    {"name": "ADJ$string$2", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"w"}, {"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"w"}, {"literal":"n"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$2"]},
    {"name": "ADJ$string$3", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"a"}, {"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$3"]},
    {"name": "OBJSUB$string$1", "symbols": [{"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJSUB", "symbols": ["OBJSUB$string$1"]},
    {"name": "OBJSUB$string$2", "symbols": [{"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"u"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"g"}, {"literal":"u"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJSUB", "symbols": ["OBJSUB$string$2"]},
    {"name": "OBJSUB$string$3", "symbols": [{"literal":"a"}, {"literal":" "}, {"literal":"t"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJSUB", "symbols": ["OBJSUB$string$3"]},
    {"name": "OBJSUB$string$4", "symbols": [{"literal":"a"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"l"}, {"literal":"i"}, {"literal":"d"}, {"literal":"-"}, {"literal":"l"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"g"}, {"literal":"u"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJSUB", "symbols": ["OBJSUB$string$4"]},
    {"name": "OBJSUB$string$5", "symbols": [{"literal":"a"}, {"literal":" "}, {"literal":"h"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"d"}, {"literal":"u"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJSUB", "symbols": ["OBJSUB$string$5"]},
    {"name": "SUBVERB$string$1", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBVERB", "symbols": ["SUBVERB$string$1"]},
    {"name": "SUBVERB$string$2", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBVERB", "symbols": ["SUBVERB$string$2"]},
    {"name": "SUBVERB$string$3", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBVERB", "symbols": ["SUBVERB$string$3"]},
    {"name": "PREDVERB$string$1", "symbols": [{"literal":"c"}, {"literal":"u"}, {"literal":"d"}, {"literal":"d"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDVERB", "symbols": ["PREDVERB$string$1"]},
    {"name": "PREDVERB$string$2", "symbols": [{"literal":"'"}, {"literal":"h"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}, {"literal":"'"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDVERB", "symbols": ["PREDVERB$string$2"]},
    {"name": "PREDVERB$string$3", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDVERB", "symbols": ["PREDVERB$string$3", "_", "MEDIA"]},
    {"name": "PREDVERB$string$4", "symbols": [{"literal":"s"}, {"literal":"n"}, {"literal":"u"}, {"literal":"g"}, {"literal":"g"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDVERB", "symbols": ["PREDVERB$string$4"]},
    {"name": "GERUND$string$1", "symbols": [{"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GERUND", "symbols": ["GERUND$string$1", "_", "FOODS"]},
    {"name": "GERUND$string$2", "symbols": [{"literal":"s"}, {"literal":"n"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GERUND", "symbols": ["GERUND$string$2", "_", "FOODS"]},
    {"name": "GERUND$string$3", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GERUND", "symbols": ["GERUND$string$3", "_", "MUSIC"]},
    {"name": "MOD$string$1", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$1", "_", "OBJSUB"]},
    {"name": "MOD$string$2", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":"t"}, {"literal":"t"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MOD", "symbols": ["MOD$string$2"]},
    {"name": "OBJ$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"c"}, {"literal":"u"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$1"]},
    {"name": "OBJ$string$2", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"g"}, {"literal":"i"}, {"literal":"r"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$2"]},
    {"name": "OBJ$string$3", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"f"}, {"literal":"e"}, {"literal":"m"}, {"literal":"a"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$3"]},
    {"name": "OBJ$string$4", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$4"]},
    {"name": "MEDIA$string$1", "symbols": [{"literal":"a"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"v"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MEDIA", "symbols": ["MEDIA$string$1"]},
    {"name": "MEDIA$string$2", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"T"}, {"literal":"V"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MEDIA", "symbols": ["MEDIA$string$2"]},
    {"name": "MEDIA$string$3", "symbols": [{"literal":"E"}, {"literal":"u"}, {"literal":"p"}, {"literal":"h"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MEDIA", "symbols": ["MEDIA$string$3"]},
    {"name": "MEDIA$string$4", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MEDIA", "symbols": ["MEDIA$string$4"]},
    {"name": "MEDIA$string$5", "symbols": [{"literal":"N"}, {"literal":"e"}, {"literal":"t"}, {"literal":"f"}, {"literal":"l"}, {"literal":"i"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MEDIA", "symbols": ["MEDIA$string$5"]},
    {"name": "FOODS$string$1", "symbols": [{"literal":"M"}, {"literal":"i"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"o"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOODS", "symbols": ["FOODS$string$1"]},
    {"name": "FOODS$string$2", "symbols": [{"literal":"k"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"r"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOODS", "symbols": ["FOODS$string$2"]},
    {"name": "FOODS$string$3", "symbols": [{"literal":"T"}, {"literal":"r"}, {"literal":"a"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"J"}, {"literal":"o"}, {"literal":"e"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"d"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"o"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOODS", "symbols": ["FOODS$string$3"]},
    {"name": "FOODS$string$4", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}, {"literal":"n"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOODS", "symbols": ["FOODS$string$4"]},
    {"name": "FOODS$string$5", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"s"}, {"literal":"h"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOODS", "symbols": ["FOODS$string$5"]},
    {"name": "MUSIC$string$1", "symbols": [{"literal":"R"}, {"literal":"a"}, {"literal":"y"}, {"literal":" "}, {"literal":"J"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC", "symbols": ["MUSIC$string$1"]},
    {"name": "MUSIC$string$2", "symbols": [{"literal":"2"}, {"literal":"0"}, {"literal":"0"}, {"literal":"0"}, {"literal":"s"}, {"literal":" "}, {"literal":"R"}, {"literal":"&"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC", "symbols": ["MUSIC$string$2"]},
    {"name": "MUSIC$string$3", "symbols": [{"literal":"B"}, {"literal":"R"}, {"literal":"O"}, {"literal":"C"}, {"literal":"K"}, {"literal":"H"}, {"literal":"A"}, {"literal":"M"}, {"literal":"P"}, {"literal":"T"}, {"literal":"O"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC", "symbols": ["MUSIC$string$3"]},
    {"name": "MUSIC$string$4", "symbols": [{"literal":"W"}, {"literal":"i"}, {"literal":"z"}, {"literal":"K"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC", "symbols": ["MUSIC$string$4"]},
    {"name": "MUSIC$string$5", "symbols": [{"literal":"P"}, {"literal":"A"}, {"literal":"R"}, {"literal":"T"}, {"literal":"Y"}, {"literal":"N"}, {"literal":"E"}, {"literal":"X"}, {"literal":"T"}, {"literal":"D"}, {"literal":"O"}, {"literal":"O"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MUSIC", "symbols": ["MUSIC$string$5"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
