// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["ANGRYCOMMENT", {"literal":".","pos":6}]},
    {"name": "MAIN", "symbols": ["RAGEMOMENT", {"literal":"!","pos":12}]},
    {"name": "_", "symbols": [{"literal":" ","pos":18}]},
    {"name": "ANGRYCOMMENT$string$1", "symbols": [{"literal":"I"}, {"literal":"'"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYCOMMENT$string$2", "symbols": [{"literal":"a"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYCOMMENT", "symbols": ["ANGRYCOMMENT$string$1", "_", "ANGRYACTION", "_", "ANGRYCOMMENT$string$2", "_", "GAME"]},
    {"name": "ANGRYCOMMENT$string$3", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYCOMMENT$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"g"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYCOMMENT", "symbols": ["ANGRYCOMMENT$string$3", "_", "REGRET", "_", "ANGRYCOMMENT$string$4"]},
    {"name": "ANGRYCOMMENT$string$5", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"g"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYCOMMENT", "symbols": ["ANGRYCOMMENT$string$5", "_", "DESCRIPTION"]},
    {"name": "RAGEMOMENT$string$1", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RAGEMOMENT$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"g"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RAGEMOMENT", "symbols": ["RAGEMOMENT$string$1", "_", "ANGRYACTION", "_", "RAGEMOMENT$string$2"]},
    {"name": "RAGEMOMENT$string$3", "symbols": [{"literal":"I"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RAGEMOMENT", "symbols": ["RAGEMOMENT$string$3", "_", "UNLUCKY", "_", "GAME"]},
    {"name": "RAGEMOMENT$string$4", "symbols": [{"literal":"H"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RAGEMOMENT", "symbols": ["RAGEMOMENT$string$4", "_", "BADATGAME"]},
    {"name": "UNLUCKY$string$1", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UNLUCKY", "symbols": ["UNLUCKY$string$1", "_", "BADATGAME"]},
    {"name": "UNLUCKY$string$2", "symbols": [{"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UNLUCKY", "symbols": ["UNLUCKY$string$2"]},
    {"name": "UNLUCKY$string$3", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"p"}, {"literal":"a"}, {"literal":"w"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UNLUCKY", "symbols": ["UNLUCKY$string$3"]},
    {"name": "UNLUCKY$string$4", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"j"}, {"literal":"o"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UNLUCKY", "symbols": ["UNLUCKY$string$4"]},
    {"name": "GAME$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"g"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GAME", "symbols": ["GAME$string$1"]},
    {"name": "GAME$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GAME", "symbols": ["GAME$string$2"]},
    {"name": "ANGRYACTION$string$1", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYACTION", "symbols": ["ANGRYACTION$string$1"]},
    {"name": "ANGRYACTION$string$2", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYACTION", "symbols": ["ANGRYACTION$string$2"]},
    {"name": "ANGRYACTION$string$3", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"f"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYACTION", "symbols": ["ANGRYACTION$string$3"]},
    {"name": "ANGRYACTION$string$4", "symbols": [{"literal":"u"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYACTION", "symbols": ["ANGRYACTION$string$4"]},
    {"name": "ANGRYACTION$string$5", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANGRYACTION", "symbols": ["OTHERACTION", "_", "ANGRYACTION$string$5", "_", "ANGRYACTION"]},
    {"name": "OTHERACTION$string$1", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"v"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"d"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"v"}, {"literal":"i"}, {"literal":"e"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OTHERACTION", "symbols": ["OTHERACTION$string$1"]},
    {"name": "OTHERACTION$string$2", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OTHERACTION", "symbols": ["OTHERACTION$string$2"]},
    {"name": "BADATGAME$string$1", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BADATGAME", "symbols": ["BADATGAME$string$1"]},
    {"name": "BADATGAME$string$2", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BADATGAME", "symbols": ["BADATGAME$string$2"]},
    {"name": "BADATGAME$string$3", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"a"}, {"literal":"w"}, {"literal":"n"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"m"}, {"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BADATGAME", "symbols": ["BADATGAME$string$3"]},
    {"name": "BADATGAME$string$4", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BADATGAME", "symbols": ["BADATGAME$string$4"]},
    {"name": "BADATGAME$string$5", "symbols": [{"literal":"a"}, {"literal":"i"}, {"literal":"m"}, {"literal":"b"}, {"literal":"o"}, {"literal":"t"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BADATGAME", "symbols": ["BADATGAME$string$5"]},
    {"name": "BADATGAME$string$6", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BADATGAME", "symbols": ["BADATGAME$string$6"]},
    {"name": "DESCRIPTION$string$1", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"y"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTION", "symbols": ["DESCRIPTION$string$1"]},
    {"name": "DESCRIPTION$string$2", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"y"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"g"}, {"literal":"g"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTION", "symbols": ["DESCRIPTION$string$2"]},
    {"name": "DESCRIPTION$string$3", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"f"}, {"literal":"u"}, {"literal":"n"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTION", "symbols": ["DESCRIPTION$string$3"]},
    {"name": "DESCRIPTION$string$4", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTION", "symbols": ["DESCRIPTION$string$4"]},
    {"name": "DESCRIPTION$string$5", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTION", "symbols": ["DESCRIPTION$string$5"]},
    {"name": "DESCRIPTION$string$6", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTION", "symbols": ["DESCRIPTION$string$6"]},
    {"name": "DESCRIPTION$string$7", "symbols": [{"literal":"l"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTION", "symbols": ["DESCRIPTION$string$7"]},
    {"name": "REGRET$string$1", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"y"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REGRET", "symbols": ["REGRET$string$1"]},
    {"name": "REGRET$string$2", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REGRET", "symbols": ["REGRET$string$2"]},
    {"name": "REGRET$string$3", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REGRET", "symbols": ["REGRET$string$3"]},
    {"name": "REGRET$string$4", "symbols": [{"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REGRET", "symbols": ["REGRET$string$4"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
