// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["PICKUPLINE", {"literal":".","pos":6}]},
    {"name": "MAIN", "symbols": ["INQUIRY", {"literal":"?","pos":12}]},
    {"name": "_", "symbols": [{"literal":" ","pos":18}]},
    {"name": "INQUIRY", "symbols": ["HOOK", "_", "INQUIRYWORD", "_", "PLAYER2", "_", "ACTION1", "_", "REDFLAGS"]},
    {"name": "INQUIRY", "symbols": ["HOOK", "_", "INQUIRYWORD", "_", "PLAYER2", "_", "ACTION1TO", "_", "DATEPLANS"]},
    {"name": "INQUIRY", "symbols": ["HOOK", "_", "INQUIRYWORD", "_", "PLAYER2", "_", "ACTION1TO", "_", "DATEPLANS", "_", "CHANGER"]},
    {"name": "INQUIRY$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INQUIRY", "symbols": ["PLAYER2", "_", "ACTION1", "_", {"literal":"a","pos":96}, "_", "PLAYER3", "_", "ABOUT", "_", "REDFLAGS", "_", "INQUIRY$string$1", "_", "REDFLAGS", "_", "CONFIRMATION"]},
    {"name": "INQUIRYWORD$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INQUIRYWORD", "symbols": ["INQUIRYWORD$string$1"]},
    {"name": "PICKUPLINE$string$1", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PICKUPLINE", "symbols": ["PLAYER1", "_", "ACTION1TO", "_", "DATEPLANS", "_", "PICKUPLINE$string$1"]},
    {"name": "PICKUPLINE$string$2", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PICKUPLINE", "symbols": ["PLAYER3", "_", "ACTION3TO", "_", "DATEPLANS", "_", "PICKUPLINE$string$2"]},
    {"name": "PICKUPLINE$string$3", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PICKUPLINE", "symbols": ["PLAYER1", "_", "UNCERTAINACTION", "_", "PLAYER2", "_", "ACTION1", "_", {"literal":"a","pos":179}, "_", "PLAYER3", "_", "ABOUT", "_", "REDFLAGS", "_", "PICKUPLINE$string$3", "_", "PLAYER1", "_", "CERTAINACTION", "_", "PLAYER2", "_", "ACTION1", "_", "REDFLAGS"]},
    {"name": "PICKUPLINE$string$4", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PICKUPLINE", "symbols": ["PLAYER1", "_", "ACTION1TO", "_", "DATEPLANS", "_", "PICKUPLINE$string$4", "_", "PICKUPLINE"]},
    {"name": "HOOK", "symbols": ["GREETING", "_", "PETNAME"]},
    {"name": "PLAYER1", "symbols": [{"literal":"I","pos":251}]},
    {"name": "PLAYER2$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLAYER2", "symbols": ["PLAYER2$string$1"]},
    {"name": "PLAYER3$string$1", "symbols": [{"literal":"D"}, {"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLAYER3", "symbols": ["PLAYER3$string$1"]},
    {"name": "PLAYER3$string$2", "symbols": [{"literal":"S"}, {"literal":"u"}, {"literal":"g"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLAYER3", "symbols": ["PLAYER3$string$2"]},
    {"name": "ACTION1$string$1", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION1", "symbols": ["ACTION1$string$1"]},
    {"name": "ACTION1$string$2", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION1", "symbols": ["ACTION1$string$2"]},
    {"name": "ACTION1$string$3", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION1", "symbols": ["ACTION1$string$3"]},
    {"name": "ACTION3$string$1", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION3", "symbols": ["ACTION3$string$1"]},
    {"name": "ACTION3$string$2", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION3", "symbols": ["ACTION3$string$2"]},
    {"name": "ACTION3$string$3", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION3", "symbols": ["ACTION3$string$3"]},
    {"name": "ACTION1TO$string$1", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION1TO", "symbols": ["ACTION1TO$string$1"]},
    {"name": "ACTION1TO$string$2", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION1TO", "symbols": ["ACTION1TO$string$2"]},
    {"name": "ACTION1TO$string$3", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION1TO", "symbols": ["ACTION1TO$string$3"]},
    {"name": "ACTION3TO$string$1", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION3TO", "symbols": ["ACTION3TO$string$1"]},
    {"name": "ACTION3TO$string$2", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION3TO", "symbols": ["ACTION3TO$string$2"]},
    {"name": "ACTION3TO$string$3", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION3TO", "symbols": ["ACTION3TO$string$3"]},
    {"name": "CERTAINACTION$string$1", "symbols": [{"literal":"k"}, {"literal":"n"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CERTAINACTION", "symbols": ["CERTAINACTION$string$1"]},
    {"name": "CERTAINACTION$string$2", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CERTAINACTION", "symbols": ["CERTAINACTION$string$2"]},
    {"name": "CERTAINACTION$string$3", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"p"}, {"literal":"o"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CERTAINACTION", "symbols": ["CERTAINACTION$string$3"]},
    {"name": "CERTAINACTION$string$4", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":" "}, {"literal":"a"}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CERTAINACTION", "symbols": ["CERTAINACTION$string$4"]},
    {"name": "UNCERTAINACTION$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UNCERTAINACTION", "symbols": ["UNCERTAINACTION$string$1"]},
    {"name": "UNCERTAINACTION$string$2", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"s"}, {"literal":"p"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UNCERTAINACTION", "symbols": ["UNCERTAINACTION$string$2"]},
    {"name": "UNCERTAINACTION$string$3", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UNCERTAINACTION", "symbols": ["UNCERTAINACTION$string$3"]},
    {"name": "UNCERTAINACTION$string$4", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"f"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UNCERTAINACTION", "symbols": ["UNCERTAINACTION$string$4"]},
    {"name": "ABOUT$string$1", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"o"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ABOUT", "symbols": ["ABOUT$string$1"]},
    {"name": "ABOUT$string$2", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"o"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ABOUT", "symbols": ["ABOUT$string$2"]},
    {"name": "ABOUT$string$3", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"o"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"p"}, {"literal":"p"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ABOUT", "symbols": ["ABOUT$string$3"]},
    {"name": "CONFIRMATION$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONFIRMATION", "symbols": ["CONFIRMATION$string$1"]},
    {"name": "CONFIRMATION$string$2", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"i"}, {"literal":"r"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"g"}, {"literal":"u"}, {"literal":"r"}, {"literal":"r"}, {"literal":"r"}, {"literal":"l"}, {"literal":"l"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONFIRMATION", "symbols": ["CONFIRMATION$string$2"]},
    {"name": "GREETING$string$1", "symbols": [{"literal":"W"}, {"literal":"y"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING", "symbols": ["GREETING$string$1"]},
    {"name": "GREETING$string$2", "symbols": [{"literal":"H"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING", "symbols": ["GREETING$string$2"]},
    {"name": "GREETING$string$3", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"y"}, {"literal":"y"}, {"literal":"y"}, {"literal":"y"}, {"literal":"y"}, {"literal":"y"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING", "symbols": ["GREETING$string$3"]},
    {"name": "GREETING$string$4", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"p"}, {"literal":"o"}, {"literal":"p"}, {"literal":"p"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING", "symbols": ["GREETING$string$4"]},
    {"name": "PETNAME$string$1", "symbols": [{"literal":"C"}, {"literal":"u"}, {"literal":"t"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PETNAME", "symbols": ["PETNAME$string$1"]},
    {"name": "PETNAME$string$2", "symbols": [{"literal":"B"}, {"literal":"a"}, {"literal":"b"}, {"literal":"y"}, {"literal":"g"}, {"literal":"u"}, {"literal":"r"}, {"literal":"l"}, {"literal":"l"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PETNAME", "symbols": ["PETNAME$string$2"]},
    {"name": "PETNAME$string$3", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"t"}, {"literal":"s"}, {"literal":"t"}, {"literal":"u"}, {"literal":"f"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PETNAME", "symbols": ["PETNAME$string$3"]},
    {"name": "PETNAME$string$4", "symbols": [{"literal":"S"}, {"literal":"u"}, {"literal":"g"}, {"literal":"a"}, {"literal":"r"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"b"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PETNAME", "symbols": ["PETNAME$string$4"]},
    {"name": "CHANGER$string$1", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"c"}, {"literal":"a"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHANGER$string$2", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHANGER", "symbols": ["CHANGER$string$1", "PLAYER1", "_", "CHANGER$string$2"]},
    {"name": "CHANGER$string$3", "symbols": [{"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHANGER$string$4", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHANGER", "symbols": ["CHANGER$string$3", "_", "PLAYER1", "_", "ACTION1", "_", "REDFLAGS", "_", "CHANGER$string$4"]},
    {"name": "CHANGER$string$5", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHANGER", "symbols": ["CHANGER$string$5", "_", "PLAYER3"]},
    {"name": "REDFLAGS$string$1", "symbols": [{"literal":"J"}, {"literal":"o"}, {"literal":"e"}, {"literal":" "}, {"literal":"R"}, {"literal":"o"}, {"literal":"g"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REDFLAGS", "symbols": ["REDFLAGS$string$1"]},
    {"name": "REDFLAGS$string$2", "symbols": [{"literal":"S"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":"c"}, {"literal":"l"}, {"literal":"o"}, {"literal":"u"}, {"literal":"d"}, {"literal":" "}, {"literal":"r"}, {"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REDFLAGS", "symbols": ["REDFLAGS$string$2"]},
    {"name": "REDFLAGS$string$3", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"g"}, {"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"a"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REDFLAGS", "symbols": ["REDFLAGS$string$3"]},
    {"name": "REDFLAGS$string$4", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REDFLAGS", "symbols": ["REDFLAGS$string$4"]},
    {"name": "REDFLAGS$string$5", "symbols": [{"literal":"g"}, {"literal":"u"}, {"literal":"y"}, {"literal":"s"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}, {"literal":" "}, {"literal":"j"}, {"literal":"o"}, {"literal":"b"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REDFLAGS", "symbols": ["REDFLAGS$string$5"]},
    {"name": "DATEPLANS$string$1", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"t"}, {"literal":"f"}, {"literal":"l"}, {"literal":"i"}, {"literal":"x"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATEPLANS", "symbols": ["DATEPLANS$string$1"]},
    {"name": "DATEPLANS$string$2", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATEPLANS", "symbols": ["DATEPLANS$string$2"]},
    {"name": "DATEPLANS$string$3", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATEPLANS", "symbols": ["DATEPLANS$string$3"]},
    {"name": "DATEPLANS$string$4", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"r"}, {"literal":" "}, {"literal":"g"}, {"literal":"a"}, {"literal":"z"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DATEPLANS", "symbols": ["DATEPLANS$string$4"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
