// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["GREETING", {"literal":"!","pos":6}]},
    {"name": "MAIN$subexpression$1", "symbols": ["PARTING"]},
    {"name": "MAIN$subexpression$1", "symbols": ["INSTRUCTION"]},
    {"name": "MAIN$subexpression$1", "symbols": ["HIRING_REQUIREMENT"]},
    {"name": "MAIN$subexpression$1", "symbols": ["FOLLOW_UP"]},
    {"name": "MAIN", "symbols": ["MAIN$subexpression$1", {"literal":".","pos":26}]},
    {"name": "MAIN", "symbols": ["MAIN_QUESTION", {"literal":"?","pos":32}]},
    {"name": "MAIN", "symbols": ["RANDOM_MUTTERINGS", "ELLIPSES_RECURSION"]},
    {"name": "GREETING$string$1", "symbols": [{"literal":"H"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING", "symbols": ["GREETING$string$1"]},
    {"name": "GREETING$string$2", "symbols": [{"literal":"H"}, {"literal":"i"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING", "symbols": ["GREETING$string$2"]},
    {"name": "GREETING$string$3", "symbols": [{"literal":"G"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING", "symbols": ["GREETING$string$3", "TIME_OF_DAY"]},
    {"name": "GREETING$string$4", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING$subexpression$1$subexpression$1", "symbols": ["INTRO_ACT", "GREETING$subexpression$1$subexpression$1$string$1"]},
    {"name": "GREETING$subexpression$1", "symbols": ["GREETING$subexpression$1$subexpression$1"]},
    {"name": "GREETING$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":" "}, {"literal":"a"}, {"literal":"c"}, {"literal":"q"}, {"literal":"u"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING$subexpression$1", "symbols": ["GREETING$subexpression$1$string$1"]},
    {"name": "GREETING", "symbols": ["DESCRIPTOR", "GREETING$string$4", "GREETING$subexpression$1"]},
    {"name": "TIME_OF_DAY$string$1", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$1"]},
    {"name": "TIME_OF_DAY$string$2", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"n"}, {"literal":"o"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$2"]},
    {"name": "TIME_OF_DAY$string$3", "symbols": [{"literal":" "}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$3"]},
    {"name": "DESCRIPTOR$string$1", "symbols": [{"literal":"G"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTOR", "symbols": ["DESCRIPTOR$string$1"]},
    {"name": "DESCRIPTOR$string$2", "symbols": [{"literal":"G"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTOR", "symbols": ["DESCRIPTOR$string$2"]},
    {"name": "DESCRIPTOR$string$3", "symbols": [{"literal":"N"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTOR", "symbols": ["DESCRIPTOR$string$3"]},
    {"name": "DESCRIPTOR$string$4", "symbols": [{"literal":"L"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTOR", "symbols": ["DESCRIPTOR$string$4"]},
    {"name": "DESCRIPTOR$string$5", "symbols": [{"literal":"P"}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DESCRIPTOR", "symbols": ["DESCRIPTOR$string$5"]},
    {"name": "INTRO_ACT$string$1", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTRO_ACT", "symbols": ["INTRO_ACT$string$1"]},
    {"name": "INTRO_ACT$string$2", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INTRO_ACT", "symbols": ["INTRO_ACT$string$2"]},
    {"name": "PARTING$string$1", "symbols": [{"literal":"B"}, {"literal":"y"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PARTING", "symbols": ["PARTING$string$1"]},
    {"name": "PARTING$string$2", "symbols": [{"literal":"S"}, {"literal":"e"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PARTING", "symbols": ["PARTING$string$2", "TIME_LATER"]},
    {"name": "TIME_LATER$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_LATER", "symbols": ["TIME_LATER$string$1"]},
    {"name": "TIME_LATER$string$2", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_LATER", "symbols": ["TIME_LATER$string$2"]},
    {"name": "TIME_LATER$string$3", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"f"}, {"literal":"e"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_LATER$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_LATER$subexpression$1", "symbols": ["TIME_LATER$subexpression$1$string$1"]},
    {"name": "TIME_LATER$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_LATER$subexpression$1", "symbols": ["TIME_LATER$subexpression$1$string$2"]},
    {"name": "TIME_LATER", "symbols": ["TIME_LATER$string$3", "TIME_LATER$subexpression$1"]},
    {"name": "INSTRUCTION$string$1", "symbols": [{"literal":"T"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INSTRUCTION", "symbols": ["INSTRUCTION$string$1", "TOPIC"]},
    {"name": "TOPIC$string$1", "symbols": [{"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$1"]},
    {"name": "TOPIC$string$2", "symbols": [{"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"j"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$2"]},
    {"name": "TOPIC$string$3", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"g"}, {"literal":"a"}, {"literal":"p"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC$subexpression$1", "symbols": ["TOPIC$subexpression$1$string$1"]},
    {"name": "TOPIC$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"u"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC$subexpression$1", "symbols": ["TOPIC$subexpression$1$string$2"]},
    {"name": "TOPIC$subexpression$1$string$3", "symbols": [{"literal":" "}, {"literal":"e"}, {"literal":"d"}, {"literal":"u"}, {"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC$subexpression$1", "symbols": ["TOPIC$subexpression$1$string$3"]},
    {"name": "TOPIC", "symbols": ["TOPIC$string$3", "TOPIC$subexpression$1"]},
    {"name": "TOPIC$string$4", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"'"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"e"}, {"literal":"x"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TOPIC", "symbols": ["TOPIC$string$4"]},
    {"name": "HIRING_REQUIREMENT$string$1", "symbols": [{"literal":"W"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HIRING_REQUIREMENT$string$2", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"h"}, {"literal":"o"}, {"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HIRING_REQUIREMENT", "symbols": ["HIRING_REQUIREMENT$string$1", "EMPLOYEE_TYPE", "HIRING_REQUIREMENT$string$2", "EMPLOYEE_QUALITY_PHRASE"]},
    {"name": "EMPLOYEE_QUALITY_PHRASE$string$1", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMPLOYEE_QUALITY_PHRASE", "symbols": ["QUALITY", "EMPLOYEE_QUALITY_PHRASE$string$1", "EMPLOYEE_QUALITY_PHRASE"]},
    {"name": "EMPLOYEE_QUALITY_PHRASE", "symbols": ["QUALITY"]},
    {"name": "QUALITY$string$1", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$1"]},
    {"name": "QUALITY$string$2", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"y"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$2"]},
    {"name": "QUALITY$string$3", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"r"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$3"]},
    {"name": "QUALITY$string$4", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$4"]},
    {"name": "QUALITY$string$5", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$5"]},
    {"name": "QUALITY$string$6", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"m"}, {"literal":"b"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$6"]},
    {"name": "QUALITY$string$7", "symbols": [{"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":"-"}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$7"]},
    {"name": "QUALITY$string$8", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"p"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$8"]},
    {"name": "QUALITY$string$9", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$9"]},
    {"name": "QUALITY$string$10", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$10"]},
    {"name": "QUALITY$string$11", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"a"}, {"literal":"l"}, {"literal":"-"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$11"]},
    {"name": "QUALITY$string$12", "symbols": [{"literal":" "}, {"literal":"q"}, {"literal":"u"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"-"}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$12"]},
    {"name": "QUALITY$string$13", "symbols": [{"literal":" "}, {"literal":"h"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$13"]},
    {"name": "QUALITY$string$14", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"p"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$14"]},
    {"name": "QUALITY$string$15", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUALITY", "symbols": ["QUALITY$string$15"]},
    {"name": "EMPLOYEE_TYPE$string$1", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"e"}, {"literal":"a"}, {"literal":"m"}, {"literal":"-"}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMPLOYEE_TYPE", "symbols": ["EMPLOYEE_TYPE$string$1"]},
    {"name": "EMPLOYEE_TYPE$string$2", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}, {"literal":"-"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMPLOYEE_TYPE", "symbols": ["EMPLOYEE_TYPE$string$2"]},
    {"name": "EMPLOYEE_TYPE$string$3", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"-"}, {"literal":"g"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMPLOYEE_TYPE", "symbols": ["EMPLOYEE_TYPE$string$3"]},
    {"name": "EMPLOYEE_TYPE$string$4", "symbols": [{"literal":" "}, {"literal":"e"}, {"literal":"m"}, {"literal":"p"}, {"literal":"l"}, {"literal":"o"}, {"literal":"y"}, {"literal":"e"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMPLOYEE_TYPE", "symbols": ["EMPLOYEE_TYPE$string$4"]},
    {"name": "EMPLOYEE_TYPE$string$5", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"i"}, {"literal":"s"}, {"literal":"k"}, {"literal":"-"}, {"literal":"t"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMPLOYEE_TYPE", "symbols": ["EMPLOYEE_TYPE$string$5"]},
    {"name": "MAIN_QUESTION$string$1", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN_QUESTION", "symbols": ["MAIN_QUESTION$string$1", "WHY_QUESTION"]},
    {"name": "MAIN_QUESTION$string$2", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN_QUESTION", "symbols": ["MAIN_QUESTION$string$2", "WHAT_QUESTION"]},
    {"name": "MAIN_QUESTION$string$3", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN_QUESTION", "symbols": ["MAIN_QUESTION$string$3", "HOW_QUESTION"]},
    {"name": "MAIN_QUESTION$string$4", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN_QUESTION", "symbols": ["MAIN_QUESTION$string$4", "WHERE_QUESTION"]},
    {"name": "MAIN_QUESTION$string$5", "symbols": [{"literal":"D"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MAIN_QUESTION", "symbols": ["MAIN_QUESTION$string$5", "DO_QUESTION"]},
    {"name": "WHY_QUESTION$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":" "}, {"literal":"h"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHY_QUESTION", "symbols": ["WHY_QUESTION$string$1"]},
    {"name": "WHY_QUESTION$string$2", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"d"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"j"}, {"literal":"o"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHY_QUESTION", "symbols": ["WHY_QUESTION$string$2"]},
    {"name": "WHY_QUESTION$string$3", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"d"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHY_QUESTION", "symbols": ["WHY_QUESTION$string$3"]},
    {"name": "WHAT_QUESTION$string$1", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"g"}, {"literal":"t"}, {"literal":"h"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$1", "symbols": ["WHAT_QUESTION$subexpression$1$string$1"]},
    {"name": "WHAT_QUESTION$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":"a"}, {"literal":"k"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$1", "symbols": ["WHAT_QUESTION$subexpression$1$string$2"]},
    {"name": "WHAT_QUESTION", "symbols": ["WHAT_QUESTION$string$1", "WHAT_QUESTION$subexpression$1"]},
    {"name": "WHAT_QUESTION$string$2", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$2$string$1", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"i"}, {"literal":"g"}, {"literal":"g"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$2$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$2$subexpression$1", "symbols": ["WHAT_QUESTION$subexpression$2$subexpression$1$string$1"]},
    {"name": "WHAT_QUESTION$subexpression$2$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"i"}, {"literal":"l"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$2$subexpression$1", "symbols": ["WHAT_QUESTION$subexpression$2$subexpression$1$string$2"]},
    {"name": "WHAT_QUESTION$subexpression$2", "symbols": ["WHAT_QUESTION$subexpression$2$string$1", "WHAT_QUESTION$subexpression$2$subexpression$1"]},
    {"name": "WHAT_QUESTION$subexpression$2$string$2", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"v"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}, {"literal":"s"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$2", "symbols": ["WHAT_QUESTION$subexpression$2$string$2"]},
    {"name": "WHAT_QUESTION$subexpression$2$string$3", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"u"}, {"literal":"r"}, {"literal":"p"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"f"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$2", "symbols": ["WHAT_QUESTION$subexpression$2$string$3"]},
    {"name": "WHAT_QUESTION", "symbols": ["WHAT_QUESTION$string$2", "WHAT_QUESTION$subexpression$2"]},
    {"name": "WHAT_QUESTION$string$3", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$3$string$1", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"r"}, {"literal":"o"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$3", "symbols": ["WHAT_QUESTION$subexpression$3$string$1"]},
    {"name": "WHAT_QUESTION$subexpression$3$string$2", "symbols": [{"literal":" "}, {"literal":"v"}, {"literal":"a"}, {"literal":"l"}, {"literal":"u"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$3", "symbols": ["WHAT_QUESTION$subexpression$3$string$2"]},
    {"name": "WHAT_QUESTION$subexpression$3$string$3", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$3", "symbols": ["WHAT_QUESTION$subexpression$3$string$3"]},
    {"name": "WHAT_QUESTION", "symbols": ["WHAT_QUESTION$string$3", "WHAT_QUESTION$subexpression$3"]},
    {"name": "WHAT_QUESTION$string$4", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$4$string$1", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$4", "symbols": ["WHAT_QUESTION$subexpression$4$string$1"]},
    {"name": "WHAT_QUESTION$subexpression$4$string$2", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"j"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":" "}, {"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$4", "symbols": ["WHAT_QUESTION$subexpression$4$string$2"]},
    {"name": "WHAT_QUESTION$subexpression$4$string$3", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"e"}, {"literal":"m"}, {"literal":"b"}, {"literal":"a"}, {"literal":"r"}, {"literal":"r"}, {"literal":"a"}, {"literal":"s"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"i"}, {"literal":"l"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$4", "symbols": ["WHAT_QUESTION$subexpression$4$string$3"]},
    {"name": "WHAT_QUESTION$subexpression$4$string$4", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}, {"literal":"n"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"r"}, {"literal":"o"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHAT_QUESTION$subexpression$4", "symbols": ["WHAT_QUESTION$subexpression$4$string$4"]},
    {"name": "WHAT_QUESTION", "symbols": ["WHAT_QUESTION$string$4", "WHAT_QUESTION$subexpression$4"]},
    {"name": "HOW_QUESTION$string$1", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"i"}, {"literal":"s"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$1", "symbols": ["HOW_QUESTION$subexpression$1$subexpression$1$string$1"]},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"f"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$1", "symbols": ["HOW_QUESTION$subexpression$1$subexpression$1$string$2"]},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$1$string$3", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$1", "symbols": ["HOW_QUESTION$subexpression$1$subexpression$1$string$3"]},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$1$string$4", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"o"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"v"}, {"literal":"i"}, {"literal":"e"}, {"literal":"w"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$1", "symbols": ["HOW_QUESTION$subexpression$1$subexpression$1$string$4"]},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$1$string$5", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"w"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$1", "symbols": ["HOW_QUESTION$subexpression$1$subexpression$1$string$5"]},
    {"name": "HOW_QUESTION$subexpression$1", "symbols": ["HOW_QUESTION$subexpression$1$string$1", "HOW_QUESTION$subexpression$1$subexpression$1"]},
    {"name": "HOW_QUESTION$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$2$string$1", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"i"}, {"literal":"l"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$2", "symbols": ["HOW_QUESTION$subexpression$1$subexpression$2$string$1"]},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$2$string$2", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":"g"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"j"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$2", "symbols": ["HOW_QUESTION$subexpression$1$subexpression$2$string$2"]},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$2$string$3", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION$subexpression$1$subexpression$2", "symbols": ["HOW_QUESTION$subexpression$1$subexpression$2$string$3"]},
    {"name": "HOW_QUESTION$subexpression$1", "symbols": ["HOW_QUESTION$subexpression$1$string$2", "HOW_QUESTION$subexpression$1$subexpression$2"]},
    {"name": "HOW_QUESTION", "symbols": ["HOW_QUESTION$string$1", "HOW_QUESTION$subexpression$1"]},
    {"name": "HOW_QUESTION$string$2", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HOW_QUESTION", "symbols": ["HOW_QUESTION$string$2"]},
    {"name": "WHERE_QUESTION$string$1", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHERE_QUESTION$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHERE_QUESTION$subexpression$1", "symbols": ["WHERE_QUESTION$subexpression$1$string$1", "FORECAST"]},
    {"name": "WHERE_QUESTION$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"f"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":" "}, {"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHERE_QUESTION$subexpression$1", "symbols": ["WHERE_QUESTION$subexpression$1$string$2"]},
    {"name": "WHERE_QUESTION$subexpression$1$string$3", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WHERE_QUESTION$subexpression$1", "symbols": ["WHERE_QUESTION$subexpression$1$string$3"]},
    {"name": "WHERE_QUESTION", "symbols": ["WHERE_QUESTION$string$1", "WHERE_QUESTION$subexpression$1"]},
    {"name": "FORECAST$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FORECAST$subexpression$1", "symbols": ["FORECAST$subexpression$1$string$1"]},
    {"name": "FORECAST$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"h"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FORECAST$subexpression$1", "symbols": ["FORECAST$subexpression$1$string$2"]},
    {"name": "FORECAST$subexpression$1$string$3", "symbols": [{"literal":" "}, {"literal":"y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FORECAST$subexpression$1", "symbols": ["FORECAST$subexpression$1$string$3"]},
    {"name": "FORECAST", "symbols": ["NUMBER", "FORECAST$subexpression$1"]},
    {"name": "NUMBER$string$1", "symbols": [{"literal":" "}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUMBER", "symbols": ["NUMBER$string$1"]},
    {"name": "NUMBER$string$2", "symbols": [{"literal":" "}, {"literal":"3"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUMBER", "symbols": ["NUMBER$string$2"]},
    {"name": "NUMBER$string$3", "symbols": [{"literal":" "}, {"literal":"4"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUMBER", "symbols": ["NUMBER$string$3"]},
    {"name": "NUMBER$string$4", "symbols": [{"literal":" "}, {"literal":"5"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUMBER", "symbols": ["NUMBER$string$4"]},
    {"name": "NUMBER$string$5", "symbols": [{"literal":" "}, {"literal":"8"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUMBER", "symbols": ["NUMBER$string$5"]},
    {"name": "NUMBER$string$6", "symbols": [{"literal":" "}, {"literal":"1"}, {"literal":"0"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUMBER", "symbols": ["NUMBER$string$6"]},
    {"name": "DO_QUESTION$string$1", "symbols": [{"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_QUESTION$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"q"}, {"literal":"u"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_QUESTION$subexpression$1", "symbols": ["DO_QUESTION$subexpression$1$string$1"]},
    {"name": "DO_QUESTION$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"v"}, {"literal":"i"}, {"literal":"b"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_QUESTION$subexpression$1", "symbols": ["DO_QUESTION$subexpression$1$string$2"]},
    {"name": "DO_QUESTION$subexpression$1$string$3", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_QUESTION$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_QUESTION$subexpression$1$subexpression$1", "symbols": ["DO_QUESTION$subexpression$1$subexpression$1$string$1"]},
    {"name": "DO_QUESTION$subexpression$1$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_QUESTION$subexpression$1$subexpression$1", "symbols": ["DO_QUESTION$subexpression$1$subexpression$1$string$2"]},
    {"name": "DO_QUESTION$subexpression$1", "symbols": ["DO_QUESTION$subexpression$1$string$3", "DO_QUESTION$subexpression$1$subexpression$1"]},
    {"name": "DO_QUESTION$subexpression$1$string$4", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_QUESTION$subexpression$1", "symbols": ["DO_QUESTION$subexpression$1$string$4"]},
    {"name": "DO_QUESTION", "symbols": ["DO_QUESTION$string$1", "DO_QUESTION$subexpression$1"]},
    {"name": "FOLLOW_UP$subexpression$1$string$1", "symbols": [{"literal":"W"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOLLOW_UP$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOLLOW_UP$subexpression$1$subexpression$1", "symbols": ["FOLLOW_UP$subexpression$1$subexpression$1$string$1"]},
    {"name": "FOLLOW_UP$subexpression$1$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOLLOW_UP$subexpression$1$subexpression$1", "symbols": ["FOLLOW_UP$subexpression$1$subexpression$1$string$2"]},
    {"name": "FOLLOW_UP$subexpression$1", "symbols": ["FOLLOW_UP$subexpression$1$string$1", "FOLLOW_UP$subexpression$1$subexpression$1"]},
    {"name": "FOLLOW_UP$subexpression$1$string$2", "symbols": [{"literal":"E"}, {"literal":"x"}, {"literal":"p"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":" "}, {"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":" "}, {"literal":"u"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOLLOW_UP$subexpression$1", "symbols": ["FOLLOW_UP$subexpression$1$string$2"]},
    {"name": "FOLLOW_UP", "symbols": ["FOLLOW_UP$subexpression$1", "TIME_LATER"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$1$string$1"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$1$string$2"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1$string$3", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}, {"literal":"i"}, {"literal":"f"}, {"literal":"f"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$1$subexpression$1$string$1"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"i"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$1$subexpression$1$string$2"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1$string$4", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$1$string$3", "RANDOM_MUTTERINGS$subexpression$1$subexpression$1$subexpression$1", "RANDOM_MUTTERINGS$subexpression$1$subexpression$1$string$4"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$2$string$1", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"f"}, {"literal":"f"}, {"literal":"e"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$2$string$1"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$2$string$2", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"e"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$2$string$2"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$2$string$3", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$2$string$3"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$2$string$4", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"p"}, {"literal":"o"}, {"literal":"l"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$2$string$4"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$2$string$5", "symbols": [{"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$2$string$5"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$1", "RANDOM_MUTTERINGS$subexpression$1$subexpression$2"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$3$string$1", "symbols": [{"literal":" "}, {"literal":"s"}, {"literal":"l"}, {"literal":"e"}, {"literal":"e"}, {"literal":"p"}, {"literal":"-"}, {"literal":"d"}, {"literal":"e"}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$3", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$3$string$1"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$3$string$2", "symbols": [{"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$3", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$3$string$2"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$3$string$3", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"p"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"s"}, {"literal":"l"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$1$subexpression$3", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$subexpression$3$string$3"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$1$string$1", "RANDOM_MUTTERINGS$subexpression$1$subexpression$3"]},
    {"name": "RANDOM_MUTTERINGS", "symbols": [{"literal":"I","pos":593}, "RANDOM_MUTTERINGS$subexpression$1"]},
    {"name": "RANDOM_MUTTERINGS$string$1", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"j"}, {"literal":"o"}, {"literal":"b"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$2$string$1", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$2$string$1"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$2$string$2", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$2$string$2"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$2$string$3", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":"i"}, {"literal":"b"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"f"}, {"literal":"u"}, {"literal":"l"}, {"literal":"f"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$2$string$3"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$2$string$4", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$2$string$4"]},
    {"name": "RANDOM_MUTTERINGS", "symbols": ["RANDOM_MUTTERINGS$string$1", "RANDOM_MUTTERINGS$subexpression$2"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$string$1", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"t"}, {"literal":"i"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$1$string$1"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"o"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$1$string$2"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1$string$1", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1$string$1"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1$string$2", "symbols": [{"literal":" "}, {"literal":"o"}, {"literal":"r"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1$string$2"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1$string$3", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"u"}, {"literal":"y"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1$string$3"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1$string$4", "symbols": [{"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"b"}, {"literal":"u"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1$string$4"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$string$3", "symbols": [{"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$1$subexpression$1", "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$string$3"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1$string$4", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}, {"literal":"i"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$1", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$1$string$4"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$string$1", "RANDOM_MUTTERINGS$subexpression$3$subexpression$1"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$string$2", "symbols": [{"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$2$string$1", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"e"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$2$string$1"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$2$string$2", "symbols": [{"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$2$string$2"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$2$string$3", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"f"}, {"literal":"l"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RANDOM_MUTTERINGS$subexpression$3$subexpression$2", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$subexpression$2$string$3"]},
    {"name": "RANDOM_MUTTERINGS$subexpression$3", "symbols": ["RANDOM_MUTTERINGS$subexpression$3$string$2", "RANDOM_MUTTERINGS$subexpression$3$subexpression$2"]},
    {"name": "RANDOM_MUTTERINGS", "symbols": ["NAME", "RANDOM_MUTTERINGS$subexpression$3"]},
    {"name": "NAME$string$1", "symbols": [{"literal":"S"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$1"]},
    {"name": "NAME$string$2", "symbols": [{"literal":"S"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$2"]},
    {"name": "NAME$string$3", "symbols": [{"literal":"T"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$3"]},
    {"name": "NAME$string$4", "symbols": [{"literal":"M"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"l"}, {"literal":"d"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$4"]},
    {"name": "NAME$string$5", "symbols": [{"literal":"M"}, {"literal":"i"}, {"literal":"l"}, {"literal":"d"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$5"]},
    {"name": "NAME$string$6", "symbols": [{"literal":"G"}, {"literal":"o"}, {"literal":"r"}, {"literal":"d"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$6"]},
    {"name": "NAME$string$7", "symbols": [{"literal":"K"}, {"literal":"a"}, {"literal":"i"}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$7"]},
    {"name": "NAME$string$8", "symbols": [{"literal":"A"}, {"literal":"l"}, {"literal":"e"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$8"]},
    {"name": "NAME$string$9", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NAME", "symbols": ["NAME$string$9"]},
    {"name": "ELLIPSES_RECURSION", "symbols": [{"literal":".","pos":775}, "ELLIPSES_RECURSION"]},
    {"name": "ELLIPSES_RECURSION", "symbols": [{"literal":".","pos":781}]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
