// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["HYPESENTENCE"]},
    {"name": "_", "symbols": [{"literal":" ","pos":10}]},
    {"name": "HYPESENTENCE", "symbols": ["COMMENT", {"literal":".","pos":18}]},
    {"name": "HYPESENTENCE", "symbols": ["EXCLAMATION", {"literal":"!","pos":24}]},
    {"name": "HYPESENTENCE", "symbols": ["QUESTION", {"literal":"?","pos":30}]},
    {"name": "HYPESENTENCE", "symbols": ["EMOJI"]},
    {"name": "COMMENT", "symbols": ["NOUN", "_", "PREP", "_", "VERB", "_", "NOUN", "_", "EMOJI"]},
    {"name": "COMMENT", "symbols": ["NOUN", "_", "VERB"]},
    {"name": "COMMENT", "symbols": ["NOUN", "_", "VERB", "_", "ADJ"]},
    {"name": "EXCLAMATION", "symbols": ["PREP", "_", "ADJ", "_", "EMOJI"]},
    {"name": "EXCLAMATION", "symbols": ["NOUN", "_", "VERB"]},
    {"name": "EXCLAMATION", "symbols": ["NOUN", "_", "EMOJI"]},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "NOUN", "_", "PREP", "_", "ADJ"]},
    {"name": "QUESTION", "symbols": ["QUESTIONWORD", "_", "NOUN", "_", "ADJ"]},
    {"name": "EMOJI$string$1", "symbols": [{"literal":"\ud83d"}, {"literal":"\ude0e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOJI", "symbols": ["EMOJI$string$1"]},
    {"name": "EMOJI$string$2", "symbols": [{"literal":"\ud83d"}, {"literal":"\udd25"}, {"literal":"\ud83d"}, {"literal":"\udd25"}, {"literal":"\ud83d"}, {"literal":"\udd25"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOJI", "symbols": ["EMOJI$string$2"]},
    {"name": "EMOJI$string$3", "symbols": [{"literal":"\ud83e"}, {"literal":"\udd2f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOJI", "symbols": ["EMOJI$string$3"]},
    {"name": "EMOJI$string$4", "symbols": [{"literal":"\ud83e"}, {"literal":"\udd76"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOJI", "symbols": ["EMOJI$string$4"]},
    {"name": "EMOJI$string$5", "symbols": [{"literal":"\ud83e"}, {"literal":"\udd27"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOJI", "symbols": ["EMOJI$string$5"]},
    {"name": "EMOJI$string$6", "symbols": [{"literal":"\ud83e"}, {"literal":"\udd11"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOJI", "symbols": ["EMOJI$string$6"]},
    {"name": "EMOJI$string$7", "symbols": [{"literal":"\ud83d"}, {"literal":"\ude4f"}, {"literal":"\ud83c"}, {"literal":"\udffb"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOJI", "symbols": ["EMOJI$string$7"]},
    {"name": "EMOJI$string$8", "symbols": [{"literal":"\ud83d"}, {"literal":"\udc40"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EMOJI", "symbols": ["EMOJI$string$8"]},
    {"name": "NOUN$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOUN", "symbols": ["NOUN$string$1"]},
    {"name": "NOUN$string$2", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOUN", "symbols": ["NOUN$string$2"]},
    {"name": "NOUN$string$3", "symbols": [{"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOUN", "symbols": ["NOUN$string$3"]},
    {"name": "NOUN$string$4", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOUN", "symbols": ["NOUN$string$4"]},
    {"name": "NOUN$string$5", "symbols": [{"literal":"w"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOUN", "symbols": ["NOUN$string$5"]},
    {"name": "NOUN", "symbols": ["GOAT"]},
    {"name": "NOUN$string$6", "symbols": [{"literal":"D"}, {"literal":"1"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOUN", "symbols": ["NOUN$string$6"]},
    {"name": "PREP$string$1", "symbols": [{"literal":"t"}, {"literal":"o"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREP", "symbols": ["PREP$string$1"]},
    {"name": "PREP$string$2", "symbols": [{"literal":"s"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREP", "symbols": ["PREP$string$2"]},
    {"name": "PREP$string$3", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREP", "symbols": ["PREP$string$3"]},
    {"name": "PREP$string$4", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREP", "symbols": ["PREP$string$4"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"r"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"t"}, {"literal":"a"}, {"literal":"l"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$2"]},
    {"name": "VERB$string$3", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$3"]},
    {"name": "VERB$string$4", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$4"]},
    {"name": "ADJ$string$1", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$1"]},
    {"name": "ADJ$string$2", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"c"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$2"]},
    {"name": "ADJ$string$3", "symbols": [{"literal":"d"}, {"literal":"r"}, {"literal":"i"}, {"literal":"p"}, {"literal":"p"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$3"]},
    {"name": "ADJ$string$4", "symbols": [{"literal":"s"}, {"literal":"l"}, {"literal":"i"}, {"literal":"m"}, {"literal":"m"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$4"]},
    {"name": "ADJ$string$5", "symbols": [{"literal":"f"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$5"]},
    {"name": "ADJ$string$6", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$6"]},
    {"name": "QUESTIONWORD$string$1", "symbols": [{"literal":"H"}, {"literal":"O"}, {"literal":"W"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONWORD", "symbols": ["QUESTIONWORD$string$1"]},
    {"name": "OBJ$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"G"}, {"literal":"O"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$1"]},
    {"name": "OBJ$string$2", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$2"]},
    {"name": "OBJ$string$3", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$3"]},
    {"name": "OBJ$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"g"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$4"]},
    {"name": "OBJ$string$5", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"u"}, {"literal":"t"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$5"]},
    {"name": "GOAT$string$1", "symbols": [{"literal":"G"}, {"literal":"O"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GOAT", "symbols": ["GOAT$string$1"]},
    {"name": "GOAT$string$2", "symbols": [{"literal":"G"}, {"literal":"O"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GOAT", "symbols": ["GOAT", "_", "GOAT$string$2"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
