// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["UTTERANCE", {"literal":"!","pos":6}]},
    {"name": "MAIN", "symbols": ["QUESTION", {"literal":"?","pos":12}]},
    {"name": "MAIN", "symbols": ["GREETING", {"literal":"!","pos":18}]},
    {"name": "MAIN", "symbols": ["ANNOUNCEMENT"]},
    {"name": "MAIN", "symbols": ["EXECUTION"]},
    {"name": "UTTERANCE$string$1", "symbols": [{"literal":"A"}, {"literal":"r"}, {"literal":"g"}, {"literal":"h"}, {"literal":","}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UTTERANCE$string$2", "symbols": [{"literal":"'"}, {"literal":"s"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UTTERANCE$string$3", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"u"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UTTERANCE", "symbols": ["UTTERANCE$string$1", "PROPERNOUN", "UTTERANCE$string$2", "ITEM", {"literal":" ","pos":40}, "UTTERANCE$string$3", "PARTOFSHIP"]},
    {"name": "UTTERANCE$string$4", "symbols": [{"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"y"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":"f"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"r"}, {"literal":"u"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UTTERANCE", "symbols": ["SUBJECT", "UTTERANCE$string$4"]},
    {"name": "UTTERANCE$string$5", "symbols": [{"literal":"A"}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"!"}, {"literal":" "}, {"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UTTERANCE$string$6", "symbols": [{"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UTTERANCE", "symbols": ["UTTERANCE$string$5", "ITEM", "UTTERANCE$string$6", "PLACE"]},
    {"name": "UTTERANCE$string$7", "symbols": [{"literal":"W"}, {"literal":"a"}, {"literal":"l"}, {"literal":"k"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "UTTERANCE", "symbols": ["UTTERANCE$string$7", "INSULT"]},
    {"name": "UTTERANCE", "symbols": ["PROPERNOUN", "ACCUSATION"]},
    {"name": "QUESTION$string$1", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"o"}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"C"}, {"literal":"a"}, {"literal":"p"}, {"literal":"t"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"B"}, {"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"B"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$1"]},
    {"name": "QUESTION$string$2", "symbols": [{"literal":"N"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"f"}, {"literal":"e"}, {"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"b"}, {"literal":"o"}, {"literal":"r"}, {"literal":","}, {"literal":" "}, {"literal":"e"}, {"literal":"h"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$2", "PROPERNOUN"]},
    {"name": "QUESTION$string$3", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"h"}, {"literal":"e"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTIONSTARTER", "PROPERNOUN", {"literal":" ","pos":92}, "VERB", "QUESTION$string$3", "INSULT"]},
    {"name": "QUESTION$string$4", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTIONSTARTER", "PROPERNOUN", "QUESTION$string$4", "AFFIRMATION"]},
    {"name": "QUESTION$string$5", "symbols": [{"literal":"W"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION$string$6", "symbols": [{"literal":" "}, {"literal":"k"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$5", "SUBJECT", "QUESTION$string$6", "THREAT"]},
    {"name": "GREETING$string$1", "symbols": [{"literal":"A"}, {"literal":"h"}, {"literal":"o"}, {"literal":"y"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING", "symbols": ["GREETING$string$1", "PROPERNOUN"]},
    {"name": "GREETING$string$2", "symbols": [{"literal":"L"}, {"literal":"e"}, {"literal":"t"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"i"}, {"literal":"l"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "GREETING", "symbols": ["GREETING$string$2", "PROPERNOUN"]},
    {"name": "ANNOUNCEMENT$string$1", "symbols": [{"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"v"}, {"literal":"o"}, {"literal":"l"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENT", "symbols": ["PROPERNOUN", "ANNOUNCEMENT$string$1", "VERB", {"literal":"!","pos":144}]},
    {"name": "ANNOUNCEMENT$string$2", "symbols": [{"literal":"A"}, {"literal":"r"}, {"literal":"g"}, {"literal":"h"}, {"literal":","}, {"literal":" "}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"a"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENT$string$3", "symbols": [{"literal":"s"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENT$string$4", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"g"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENT", "symbols": ["ANNOUNCEMENT$string$2", "INSULT", "ANNOUNCEMENT$string$3", "ANNOUNCEMENT$string$4", "VERB", {"literal":".","pos":158}]},
    {"name": "ANNOUNCEMENT$string$5", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}, {"literal":"o"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENT$string$6", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"C"}, {"literal":"o"}, {"literal":"-"}, {"literal":"C"}, {"literal":"a"}, {"literal":"p"}, {"literal":"t"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENT", "symbols": ["SUBJECT", "ANNOUNCEMENT$string$5", "PROPERNOUN", "ANNOUNCEMENT$string$6", "AFFIRMATION", {"literal":".","pos":172}]},
    {"name": "ANNOUNCEMENT$string$7", "symbols": [{"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENT$string$8", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"k"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENT$string$9", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENT", "symbols": ["PROPERNOUN", "ANNOUNCEMENT$string$7", "VERB", "ANNOUNCEMENT$string$8", "THREAT", "ANNOUNCEMENT$string$9", "INSULT", {"literal":".","pos":190}]},
    {"name": "ANNOUNCEMENT$string$10", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ANNOUNCEMENT", "symbols": ["SUBJECT", "ANNOUNCEMENT$string$10", "VERB", {"literal":".","pos":200}]},
    {"name": "EXECUTION$string$1", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"l"}, {"literal":"k"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"f"}, {"literal":"a"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXECUTION", "symbols": ["PROPERNOUN", "EXECUTION$string$1", "VERB", {"literal":".","pos":212}]},
    {"name": "EXECUTION$string$2", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"f"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXECUTION$string$3", "symbols": [{"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXECUTION$string$4", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXECUTION", "symbols": ["SUBJECT", "EXECUTION$string$2", "PROPERNOUN", "EXECUTION$string$3", "THREAT", "EXECUTION$string$4", "INSULT", {"literal":".","pos":230}]},
    {"name": "EXECUTION$string$5", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"s"}, {"literal":"m"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"w"}, {"literal":"n"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}, {"literal":" "}, {"literal":"w"}, {"literal":"h"}, {"literal":"o"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXECUTION$string$6", "symbols": [{"literal":" "}, {"literal":"a"}, {"literal":"g"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXECUTION", "symbols": ["SUBJECT", "EXECUTION$string$5", "PROPERNOUN", {"literal":" ","pos":240}, "VERB", "EXECUTION$string$6"]},
    {"name": "EXECUTION$string$7", "symbols": [{"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXECUTION$string$8", "symbols": [{"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":"f"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"n"}, {"literal":"o"}, {"literal":"n"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXECUTION", "symbols": ["SUBJECT", "EXECUTION$string$7", "PROPERNOUN", "EXECUTION$string$8"]},
    {"name": "EXECUTION$string$9", "symbols": [{"literal":"A"}, {"literal":"h"}, {"literal":"o"}, {"literal":"y"}, {"literal":" "}, {"literal":"m"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"y"}, {"literal":"s"}, {"literal":"!"}, {"literal":" "}, {"literal":"T"}, {"literal":"o"}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXECUTION", "symbols": ["EXECUTION$string$9", "PROPERNOUN", {"literal":".","pos":262}]},
    {"name": "SUBJECT$string$1", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJECT", "symbols": ["SUBJECT$string$1"]},
    {"name": "SUBJECT", "symbols": [{"literal":"I","pos":272}]},
    {"name": "SUBJECT$string$2", "symbols": [{"literal":"W"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJECT", "symbols": ["SUBJECT$string$2"]},
    {"name": "SUBJECT$string$3", "symbols": [{"literal":"M"}, {"literal":"y"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"d"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJECT", "symbols": ["SUBJECT$string$3"]},
    {"name": "SUBJECT$string$4", "symbols": [{"literal":"M"}, {"literal":"y"}, {"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"r"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJECT", "symbols": ["SUBJECT$string$4"]},
    {"name": "ITEM$string$1", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ITEM", "symbols": ["ITEM$string$1"]},
    {"name": "ITEM$string$2", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ITEM", "symbols": ["ITEM$string$2"]},
    {"name": "ITEM$string$3", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ITEM", "symbols": ["ITEM$string$3"]},
    {"name": "ITEM$string$4", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"s"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ITEM", "symbols": ["ITEM$string$4"]},
    {"name": "PARTOFSHIP$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PARTOFSHIP", "symbols": ["PARTOFSHIP$string$1"]},
    {"name": "PARTOFSHIP$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PARTOFSHIP", "symbols": ["PARTOFSHIP$string$2"]},
    {"name": "PARTOFSHIP$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"n"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PARTOFSHIP", "symbols": ["PARTOFSHIP$string$3"]},
    {"name": "PLACE$string$1", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"B"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$1"]},
    {"name": "PLACE$string$2", "symbols": [{"literal":"D"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":" "}, {"literal":"M"}, {"literal":"a"}, {"literal":"n"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"C"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$2"]},
    {"name": "PLACE$string$3", "symbols": [{"literal":"P"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"C"}, {"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACE", "symbols": ["PLACE$string$3"]},
    {"name": "PROPERNOUN$string$1", "symbols": [{"literal":"B"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"B"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROPERNOUN", "symbols": ["PROPERNOUN$string$1"]},
    {"name": "PROPERNOUN$string$2", "symbols": [{"literal":"I"}, {"literal":"s"}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":" "}, {"literal":"B"}, {"literal":"l"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROPERNOUN", "symbols": ["PROPERNOUN$string$2"]},
    {"name": "PROPERNOUN$string$3", "symbols": [{"literal":"J"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"S"}, {"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"b"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROPERNOUN", "symbols": ["PROPERNOUN$string$3"]},
    {"name": "PROPERNOUN$string$4", "symbols": [{"literal":"L"}, {"literal":"o"}, {"literal":"u"}, {"literal":"i"}, {"literal":"e"}, {"literal":" "}, {"literal":"G"}, {"literal":"o"}, {"literal":"l"}, {"literal":"d"}, {"literal":"b"}, {"literal":"o"}, {"literal":"t"}, {"literal":"t"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROPERNOUN", "symbols": ["PROPERNOUN$string$4"]},
    {"name": "PROPERNOUN$string$5", "symbols": [{"literal":"J"}, {"literal":"o"}, {"literal":"h"}, {"literal":"n"}, {"literal":" "}, {"literal":"C"}, {"literal":"a"}, {"literal":"n"}, {"literal":"n"}, {"literal":"o"}, {"literal":"n"}, {"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROPERNOUN", "symbols": ["PROPERNOUN$string$5"]},
    {"name": "PROPERNOUN$string$6", "symbols": [{"literal":"T"}, {"literal":"a"}, {"literal":"y"}, {"literal":"l"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"J"}, {"literal":"e"}, {"literal":"w"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PROPERNOUN", "symbols": ["PROPERNOUN$string$6"]},
    {"name": "ACCUSATION$string$1", "symbols": [{"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACCUSATION$string$2", "symbols": [{"literal":" "}, {"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"b"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACCUSATION", "symbols": ["ACCUSATION$string$1", "PLACE", "ACCUSATION$string$2", "ITEM"]},
    {"name": "ACCUSATION$string$3", "symbols": [{"literal":"!"}, {"literal":" "}, {"literal":"Y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"s"}, {"literal":"n"}, {"literal":"i"}, {"literal":"f"}, {"literal":"f"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACCUSATION", "symbols": ["ACCUSATION$string$3", "ITEM"]},
    {"name": "QUESTIONSTARTER$string$1", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":" "}, {"literal":"y"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONSTARTER", "symbols": ["QUESTIONSTARTER$string$1"]},
    {"name": "QUESTIONSTARTER$string$2", "symbols": [{"literal":"I"}, {"literal":"n"}, {"literal":" "}, {"literal":"w"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONSTARTER", "symbols": ["QUESTIONSTARTER$string$2"]},
    {"name": "QUESTIONSTARTER$string$3", "symbols": [{"literal":"G"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}, {"literal":"!"}, {"literal":" "}, {"literal":"W"}, {"literal":"h"}, {"literal":"o"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONSTARTER", "symbols": ["QUESTIONSTARTER$string$3"]},
    {"name": "QUESTIONSTARTER$string$4", "symbols": [{"literal":"B"}, {"literal":"y"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"!"}, {"literal":" "}, {"literal":"W"}, {"literal":"h"}, {"literal":"y"}, {"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"d"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONSTARTER", "symbols": ["QUESTIONSTARTER$string$4"]},
    {"name": "QUESTIONSTARTER$string$5", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONSTARTER$string$6", "symbols": [{"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONSTARTER", "symbols": ["QUESTIONSTARTER$string$5", "THREAT", "QUESTIONSTARTER$string$6"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"c"}, {"literal":"l"}, {"literal":"e"}, {"literal":"a"}, {"literal":"n"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"f"}, {"literal":"e"}, {"literal":"c"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":"f"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$2"]},
    {"name": "VERB$string$3", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"r"}, {"literal":"t"}, {"literal":"y"}, {"literal":" "}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$3", "ITEM"]},
    {"name": "VERB$string$4", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"b"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"w"}, {"literal":"a"}, {"literal":"w"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$4"]},
    {"name": "INSULT$string$1", "symbols": [{"literal":"s"}, {"literal":"m"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INSULT", "symbols": ["INSULT$string$1", "INSULT"]},
    {"name": "INSULT$string$2", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"l"}, {"literal":"y"}, {"literal":"-"}, {"literal":"l"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INSULT", "symbols": ["INSULT$string$2", "INSULT"]},
    {"name": "INSULT$string$3", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"u"}, {"literal":"r"}, {"literal":"v"}, {"literal":"y"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INSULT", "symbols": ["INSULT$string$3", "INSULT"]},
    {"name": "INSULT$string$4", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}, {"literal":"w"}, {"literal":"a"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INSULT", "symbols": ["INSULT$string$4"]},
    {"name": "INSULT$string$5", "symbols": [{"literal":"r"}, {"literal":"a"}, {"literal":"p"}, {"literal":"s"}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INSULT", "symbols": ["INSULT$string$5"]},
    {"name": "INSULT$string$6", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"k"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INSULT", "symbols": ["INSULT$string$6"]},
    {"name": "AFFIRMATION$string$1", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AFFIRMATION", "symbols": ["AFFIRMATION$string$1", "AFFIRMATION"]},
    {"name": "AFFIRMATION$string$2", "symbols": [{"literal":"j"}, {"literal":"o"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AFFIRMATION", "symbols": ["AFFIRMATION$string$2", "AFFIRMATION"]},
    {"name": "AFFIRMATION$string$3", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"s"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AFFIRMATION", "symbols": ["AFFIRMATION$string$3", "AFFIRMATION"]},
    {"name": "AFFIRMATION$string$4", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AFFIRMATION", "symbols": ["AFFIRMATION$string$4"]},
    {"name": "AFFIRMATION$string$5", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"c"}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AFFIRMATION", "symbols": ["AFFIRMATION$string$5"]},
    {"name": "THREAT$string$1", "symbols": [{"literal":"K"}, {"literal":"r"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THREAT", "symbols": ["THREAT$string$1"]},
    {"name": "THREAT$string$2", "symbols": [{"literal":"M"}, {"literal":"e"}, {"literal":"g"}, {"literal":"a"}, {"literal":"l"}, {"literal":"a"}, {"literal":"d"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THREAT", "symbols": ["THREAT$string$2"]},
    {"name": "THREAT$string$3", "symbols": [{"literal":"G"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"M"}, {"literal":"o"}, {"literal":"b"}, {"literal":"y"}, {"literal":" "}, {"literal":"D"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THREAT", "symbols": ["THREAT$string$3"]},
    {"name": "THREAT$string$4", "symbols": [{"literal":"D"}, {"literal":"o"}, {"literal":"d"}, {"literal":"o"}, {"literal":" "}, {"literal":"b"}, {"literal":"i"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THREAT", "symbols": ["THREAT$string$4"]},
    {"name": "THREAT$string$5", "symbols": [{"literal":"S"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"S"}, {"literal":"e"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THREAT", "symbols": ["THREAT$string$5"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
