// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["CRYPTOSTATEMENT"]},
    {"name": "MAIN", "symbols": ["ADVICE"]},
    {"name": "MAIN", "symbols": ["QUESTION"]},
    {"name": "_", "symbols": [{"literal":" ","pos":14}]},
    {"name": "CRYPTOSTATEMENT", "symbols": ["COIN", "PREDICTION", {"literal":".","pos":24}]},
    {"name": "CRYPTOSTATEMENTQ", "symbols": ["COIN", "PREDICTION"]},
    {"name": "COIN$string$1", "symbols": [{"literal":"B"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COIN", "symbols": ["COIN$string$1"]},
    {"name": "COIN$string$2", "symbols": [{"literal":"E"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"u"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COIN", "symbols": ["COIN$string$2"]},
    {"name": "COIN$string$3", "symbols": [{"literal":"D"}, {"literal":"o"}, {"literal":"g"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COIN", "symbols": ["COIN$string$3"]},
    {"name": "COIN$string$4", "symbols": [{"literal":"S"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COIN", "symbols": ["COIN$string$4"]},
    {"name": "PREDICTION$string$1", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDICTION", "symbols": ["_", "PREDICTION$string$1"]},
    {"name": "PREDICTION$string$2", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"h"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDICTION", "symbols": ["_", "PREDICTION$string$2", "PRICE"]},
    {"name": "PREDICTION$string$3", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"f"}, {"literal":"u"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDICTION", "symbols": ["_", "PREDICTION$string$3"]},
    {"name": "PREDICTION$string$4", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"f"}, {"literal":"o"}, {"literal":"r"}, {"literal":"m"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"S"}, {"literal":"&"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDICTION", "symbols": ["_", "PREDICTION$string$4"]},
    {"name": "PREDICTION$string$5", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"z"}, {"literal":"e"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDICTION", "symbols": ["_", "PREDICTION$string$5"]},
    {"name": "PREDICTION$string$6", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"g"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDICTION$string$7", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREDICTION", "symbols": ["_", "PREDICTION$string$6", "_", "PREDICTION$string$7", "_", "CRYPTOSTATEMENTQ"]},
    {"name": "PRICE$string$1", "symbols": [{"literal":"$"}, {"literal":"1"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PRICE", "symbols": ["_", "PRICE$string$1"]},
    {"name": "PRICE$string$2", "symbols": [{"literal":"$"}, {"literal":"1"}, {"literal":" "}, {"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PRICE", "symbols": ["_", "PRICE$string$2"]},
    {"name": "PRICE$string$3", "symbols": [{"literal":"1"}, {"literal":" "}, {"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PRICE", "symbols": ["_", "PRICE$string$3"]},
    {"name": "PRICE$string$4", "symbols": [{"literal":"1"}, {"literal":"/"}, {"literal":"1"}, {"literal":"0"}, {"literal":"0"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PRICE", "symbols": ["_", "PRICE$string$4"]},
    {"name": "ADVICE$string$1", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVICE", "symbols": ["SUBBEG", "_", "ADVICE$string$1", "_", "RECOMMENDATION", "_", "COIN", "REASON", {"literal":".","pos":132}]},
    {"name": "QUESTIONADVICE$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTIONADVICE", "symbols": ["QUESTIONADVICE$string$1", "_", "RECOMMENDATION", "_", "COIN", "REASON"]},
    {"name": "RECOMMENDATION$string$1", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATION", "symbols": ["RECOMMENDATION$string$1"]},
    {"name": "RECOMMENDATION$string$2", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATION", "symbols": ["RECOMMENDATION$string$2"]},
    {"name": "RECOMMENDATION$string$3", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATION$string$4", "symbols": [{"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"b"}, {"literal":"u"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATION", "symbols": ["RECOMMENDATION$string$3", "_", "OBJ", "_", "RECOMMENDATION$string$4"]},
    {"name": "RECOMMENDATION$string$5", "symbols": [{"literal":"q"}, {"literal":"u"}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":" "}, {"literal":"j"}, {"literal":"o"}, {"literal":"b"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATION", "symbols": ["RECOMMENDATION$string$5"]},
    {"name": "OBJ$string$1", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$1"]},
    {"name": "OBJ$string$2", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$2"]},
    {"name": "OBJ$string$3", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$3"]},
    {"name": "OBJ$string$4", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OBJ", "symbols": ["OBJ$string$4"]},
    {"name": "RECOMMENDATIONQ$string$1", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATIONQ", "symbols": ["RECOMMENDATIONQ$string$1"]},
    {"name": "RECOMMENDATIONQ$string$2", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATIONQ", "symbols": ["RECOMMENDATIONQ$string$2"]},
    {"name": "RECOMMENDATIONQ$string$3", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATIONQ$string$4", "symbols": [{"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"b"}, {"literal":"u"}, {"literal":"y"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATIONQ", "symbols": ["RECOMMENDATIONQ$string$3", "_", "OBJ", "_", "RECOMMENDATIONQ$string$4"]},
    {"name": "RECOMMENDATIONQ$string$5", "symbols": [{"literal":"q"}, {"literal":"u"}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"j"}, {"literal":"o"}, {"literal":"b"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}, {"literal":" "}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATIONQ", "symbols": ["RECOMMENDATIONQ$string$5"]},
    {"name": "REASON$string$1", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"c"}, {"literal":"a"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REASON", "symbols": ["_", "REASON$string$1", "_", "CRYPTOSTATEMENTQ"]},
    {"name": "REASON$string$2", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REASON$string$3", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"h"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "REASON", "symbols": ["_", "REASON$string$2", "_", "COIN", "_", "REASON$string$3", "PRICE"]},
    {"name": "RECOMMENDATION3$string$1", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATION3", "symbols": ["RECOMMENDATION3$string$1"]},
    {"name": "RECOMMENDATION3$string$2", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATION3", "symbols": ["RECOMMENDATION3$string$2"]},
    {"name": "RECOMMENDATION3$string$3", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"y"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATION3", "symbols": ["RECOMMENDATION3$string$3"]},
    {"name": "RECOMMENDATION3$string$4", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RECOMMENDATION3", "symbols": ["RECOMMENDATION3$string$4"]},
    {"name": "QUESTION$string$1", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$1", "_", "CONTRACTION", "SUB", "RECOMMENDATION3", "_", "COIN", {"literal":"?","pos":260}]},
    {"name": "QUESTION$string$2", "symbols": [{"literal":"D"}, {"literal":"i"}, {"literal":"d"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$2", "_", "QUESTIONADVICE", {"literal":"?","pos":269}]},
    {"name": "QUESTION$string$3", "symbols": [{"literal":"D"}, {"literal":"o"}, {"literal":" "}, {"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$3", "_", "RECOMMENDATIONQ", "_", "COIN", "REASON", {"literal":"?","pos":283}]},
    {"name": "QUESTION$string$4", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$4", "_", "SUB", "RECOMMENDATION3", "_", "COIN", {"literal":"?","pos":297}]},
    {"name": "CONTRACTION$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONTRACTION", "symbols": ["CONTRACTION$string$1", "_"]},
    {"name": "CONTRACTION$string$2", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONTRACTION", "symbols": ["CONTRACTION$string$2", "_"]},
    {"name": "CONTRACTION$string$3", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONTRACTION", "symbols": ["CONTRACTION$string$3", "_"]},
    {"name": "CONTRACTION$string$4", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONTRACTION", "symbols": ["CONTRACTION$string$4", "_"]},
    {"name": "SUB", "symbols": [{"literal":"I","pos":329}, "_"]},
    {"name": "SUB$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$1", "_"]},
    {"name": "SUB$string$2", "symbols": [{"literal":"w"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$2", "_"]},
    {"name": "SUBBEG", "symbols": [{"literal":"I","pos":349}]},
    {"name": "SUBBEG$string$1", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBBEG", "symbols": ["SUBBEG$string$1"]},
    {"name": "SUBBEG$string$2", "symbols": [{"literal":"W"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBBEG", "symbols": ["SUBBEG$string$2"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
