// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["SENTENCE", {"literal":".","pos":6}]},
    {"name": "_", "symbols": [{"literal":" ","pos":12}]},
    {"name": "SENTENCE", "symbols": ["OBJ", "_", "SUB", "_", "VERB"]},
    {"name": "SENTENCE$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE$string$2", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE", "symbols": ["SENTENCE$string$1", "_", "OBJ", "_", "SENTENCE$string$2"]},
    {"name": "OBJ", "symbols": ["FOOD"]},
    {"name": "OBJ", "symbols": ["DRINK"]},
    {"name": "VERB", "symbols": ["FOODVERB"]},
    {"name": "VERB", "symbols": ["DRINKVERB"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$2"]},
    {"name": "FOOD", "symbols": ["FOODADJ", "_", "FOOD"]},
    {"name": "FOOD$string$1", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOOD", "symbols": ["FOOD$string$1"]},
    {"name": "FOOD$string$2", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":" "}, {"literal":"p"}, {"literal":"o"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOOD", "symbols": ["FOOD$string$2"]},
    {"name": "FOOD$string$3", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOOD", "symbols": ["FOOD$string$3"]},
    {"name": "FOOD$string$4", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"n"}, {"literal":"i"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOOD", "symbols": ["FOOD$string$4"]},
    {"name": "FOODADJ$string$1", "symbols": [{"literal":"t"}, {"literal":"o"}, {"literal":"a"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOODADJ", "symbols": ["FOODADJ$string$1"]},
    {"name": "FOODADJ$string$2", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOODADJ", "symbols": ["FOODADJ$string$2"]},
    {"name": "DRINK", "symbols": ["DRINKADJ", "_", "DRINK"]},
    {"name": "DRINK$string$1", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"a"}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINK", "symbols": ["DRINK$string$1"]},
    {"name": "DRINK$string$2", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINK", "symbols": ["DRINK$string$2"]},
    {"name": "DRINK$string$3", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINK", "symbols": ["DRINK$string$3"]},
    {"name": "DRINK$string$4", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"u"}, {"literal":"c"}, {"literal":"c"}, {"literal":"i"}, {"literal":"n"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINK", "symbols": ["DRINK$string$4"]},
    {"name": "DRINKADJ$string$1", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"e"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINKADJ", "symbols": ["DRINKADJ$string$1"]},
    {"name": "DRINKADJ$string$2", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINKADJ", "symbols": ["DRINKADJ$string$2"]},
    {"name": "DRINKADJ$string$3", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINKADJ", "symbols": ["DRINKADJ$string$3"]},
    {"name": "DRINKADJ$string$4", "symbols": [{"literal":"i"}, {"literal":"c"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINKADJ", "symbols": ["DRINKADJ$string$4"]},
    {"name": "DRINKADJ$string$5", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINKADJ", "symbols": ["DRINKADJ$string$5"]},
    {"name": "DRINKADJ$string$6", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINKADJ", "symbols": ["DRINKADJ$string$6"]},
    {"name": "DRINKADJ$string$7", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINKADJ", "symbols": ["DRINKADJ$string$7"]},
    {"name": "SUB", "symbols": [{"literal":"I","pos":164}]},
    {"name": "SUB$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$1"]},
    {"name": "SUB$string$2", "symbols": [{"literal":"w"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$2"]},
    {"name": "SUB$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$3"]},
    {"name": "SUB$string$4", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$4"]},
    {"name": "SUB$string$5", "symbols": [{"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$5"]},
    {"name": "FOODVERB$string$1", "symbols": [{"literal":"e"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOODVERB", "symbols": ["FOODVERB$string$1"]},
    {"name": "FOODVERB$string$2", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOODVERB", "symbols": ["FOODVERB$string$2"]},
    {"name": "DRINKVERB$string$1", "symbols": [{"literal":"d"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINKVERB", "symbols": ["DRINKVERB$string$1"]},
    {"name": "DRINKVERB$string$2", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DRINKVERB", "symbols": ["DRINKVERB$string$2"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
