// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["SENTENCE", {"literal":"!","pos":6}]},
    {"name": "SENTENCE", "symbols": ["CLASSIFIER", "_", "NOUN", "_", "ADVERB", "_", "ACTION", "_", "TARGET"]},
    {"name": "CLASSIFIER", "symbols": ["CHARACTERCLASSIFIER", "_", "POLITICALCLASSIFIER"]},
    {"name": "CHARACTERCLASSIFIER$string$1", "symbols": [{"literal":"S"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTERCLASSIFIER", "symbols": ["CHARACTERCLASSIFIER$string$1"]},
    {"name": "CHARACTERCLASSIFIER$string$2", "symbols": [{"literal":"D"}, {"literal":"e"}, {"literal":"l"}, {"literal":"u"}, {"literal":"s"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTERCLASSIFIER", "symbols": ["CHARACTERCLASSIFIER$string$2"]},
    {"name": "CHARACTERCLASSIFIER$string$3", "symbols": [{"literal":"U"}, {"literal":"n"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTERCLASSIFIER", "symbols": ["CHARACTERCLASSIFIER$string$3"]},
    {"name": "CHARACTERCLASSIFIER$string$4", "symbols": [{"literal":"I"}, {"literal":"d"}, {"literal":"i"}, {"literal":"o"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTERCLASSIFIER", "symbols": ["CHARACTERCLASSIFIER$string$4"]},
    {"name": "CHARACTERCLASSIFIER$string$5", "symbols": [{"literal":"B"}, {"literal":"r"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTERCLASSIFIER", "symbols": ["CHARACTERCLASSIFIER$string$5"]},
    {"name": "POLITICALCLASSIFIER$string$1", "symbols": [{"literal":"D"}, {"literal":"e"}, {"literal":"m"}, {"literal":"o"}, {"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POLITICALCLASSIFIER", "symbols": ["POLITICALCLASSIFIER$string$1"]},
    {"name": "POLITICALCLASSIFIER$string$2", "symbols": [{"literal":"R"}, {"literal":"e"}, {"literal":"p"}, {"literal":"u"}, {"literal":"b"}, {"literal":"l"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POLITICALCLASSIFIER", "symbols": ["POLITICALCLASSIFIER$string$2"]},
    {"name": "POLITICALCLASSIFIER$string$3", "symbols": [{"literal":"r"}, {"literal":"a"}, {"literal":"d"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POLITICALCLASSIFIER", "symbols": ["POLITICALCLASSIFIER$string$3"]},
    {"name": "POLITICALCLASSIFIER$string$4", "symbols": [{"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":"m"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POLITICALCLASSIFIER", "symbols": ["POLITICALCLASSIFIER$string$4"]},
    {"name": "NOUN", "symbols": ["FIGURE"]},
    {"name": "NOUN", "symbols": ["ORGANIZATION"]},
    {"name": "FIGURE$string$1", "symbols": [{"literal":"D"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"T"}, {"literal":"r"}, {"literal":"u"}, {"literal":"m"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$1"]},
    {"name": "FIGURE$string$2", "symbols": [{"literal":"H"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"C"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$2"]},
    {"name": "FIGURE$string$3", "symbols": [{"literal":"J"}, {"literal":"o"}, {"literal":"e"}, {"literal":" "}, {"literal":"B"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$3"]},
    {"name": "FIGURE$string$4", "symbols": [{"literal":"B"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"O"}, {"literal":"b"}, {"literal":"a"}, {"literal":"m"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$4"]},
    {"name": "FIGURE$string$5", "symbols": [{"literal":"A"}, {"literal":"l"}, {"literal":"e"}, {"literal":"x"}, {"literal":" "}, {"literal":"J"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$5"]},
    {"name": "FIGURE$string$6", "symbols": [{"literal":"A"}, {"literal":"n"}, {"literal":"d"}, {"literal":"r"}, {"literal":"e"}, {"literal":"w"}, {"literal":" "}, {"literal":"T"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$6"]},
    {"name": "FIGURE$string$7", "symbols": [{"literal":"N"}, {"literal":"a"}, {"literal":"n"}, {"literal":"c"}, {"literal":"y"}, {"literal":" "}, {"literal":"P"}, {"literal":"e"}, {"literal":"l"}, {"literal":"o"}, {"literal":"s"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$7"]},
    {"name": "FIGURE$string$8", "symbols": [{"literal":"M"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"M"}, {"literal":"c"}, {"literal":"C"}, {"literal":"o"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$8"]},
    {"name": "FIGURE$string$9", "symbols": [{"literal":"A"}, {"literal":"O"}, {"literal":"C"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$9"]},
    {"name": "FIGURE$string$10", "symbols": [{"literal":"S"}, {"literal":"t"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"B"}, {"literal":"a"}, {"literal":"n"}, {"literal":"n"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$10"]},
    {"name": "FIGURE$string$11", "symbols": [{"literal":"M"}, {"literal":"a"}, {"literal":"r"}, {"literal":"j"}, {"literal":"o"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":" "}, {"literal":"T"}, {"literal":"a"}, {"literal":"y"}, {"literal":"l"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"G"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$11"]},
    {"name": "FIGURE$string$12", "symbols": [{"literal":"J"}, {"literal":"i"}, {"literal":"m"}, {"literal":" "}, {"literal":"A"}, {"literal":"c"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FIGURE", "symbols": ["FIGURE$string$12"]},
    {"name": "ORGANIZATION$string$1", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"e"}, {"literal":"p"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGANIZATION", "symbols": ["ORGANIZATION$string$1"]},
    {"name": "ORGANIZATION$string$2", "symbols": [{"literal":"r"}, {"literal":"a"}, {"literal":"d"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGANIZATION", "symbols": ["ORGANIZATION$string$2"]},
    {"name": "ORGANIZATION$string$3", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"a"}, {"literal":"m"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGANIZATION", "symbols": ["ORGANIZATION$string$3"]},
    {"name": "ORGANIZATION$string$4", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"r"}, {"literal":"-"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGANIZATION", "symbols": ["ORGANIZATION$string$4"]},
    {"name": "ORGANIZATION$string$5", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"r"}, {"literal":"-"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGANIZATION", "symbols": ["ORGANIZATION$string$5"]},
    {"name": "ORGANIZATION$string$6", "symbols": [{"literal":"A"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"f"}, {"literal":"a"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGANIZATION", "symbols": ["ORGANIZATION$string$6"]},
    {"name": "ORGANIZATION$string$7", "symbols": [{"literal":"Q"}, {"literal":"a"}, {"literal":"n"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGANIZATION", "symbols": ["ORGANIZATION$string$7"]},
    {"name": "ORGANIZATION$string$8", "symbols": [{"literal":"B"}, {"literal":"L"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ORGANIZATION", "symbols": ["ORGANIZATION$string$8"]},
    {"name": "ADVERB$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"r"}, {"literal":"i"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$1"]},
    {"name": "ADVERB$string$2", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"d"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$2"]},
    {"name": "ADVERB$string$3", "symbols": [{"literal":"i"}, {"literal":"g"}, {"literal":"n"}, {"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$3"]},
    {"name": "ACTION$string$1", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"e"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$1"]},
    {"name": "ACTION$string$2", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$2"]},
    {"name": "ACTION$string$3", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$3"]},
    {"name": "ACTION$string$4", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"o"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$4"]},
    {"name": "ACTION$string$5", "symbols": [{"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$5"]},
    {"name": "ACTION$string$6", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$6"]},
    {"name": "ACTION$string$7", "symbols": [{"literal":"e"}, {"literal":"x"}, {"literal":"p"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$7"]},
    {"name": "ACTION$string$8", "symbols": [{"literal":"r"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":"g"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$8"]},
    {"name": "ACTION$string$9", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$9"]},
    {"name": "ACTION$string$10", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$10"]},
    {"name": "ACTION$string$11", "symbols": [{"literal":"k"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ACTION", "symbols": ["ACTION$string$11"]},
    {"name": "TARGET$string$1", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"o"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$1"]},
    {"name": "TARGET$string$2", "symbols": [{"literal":"A"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$2"]},
    {"name": "TARGET$string$3", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"c"}, {"literal":"i"}, {"literal":"e"}, {"literal":"t"}, {"literal":"y"}, {"literal":" "}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":" "}, {"literal":"k"}, {"literal":"n"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$3"]},
    {"name": "TARGET$string$4", "symbols": [{"literal":"g"}, {"literal":"u"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$4"]},
    {"name": "TARGET$string$5", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"C"}, {"literal":"a"}, {"literal":"p"}, {"literal":"i"}, {"literal":"t"}, {"literal":"o"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$5"]},
    {"name": "TARGET$string$6", "symbols": [{"literal":"d"}, {"literal":"e"}, {"literal":"m"}, {"literal":"o"}, {"literal":"c"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$6"]},
    {"name": "TARGET$string$7", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"s"}, {"literal":"c"}, {"literal":"i"}, {"literal":"s"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$7"]},
    {"name": "TARGET$string$8", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"p"}, {"literal":"e"}, {"literal":"e"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$8"]},
    {"name": "TARGET$string$9", "symbols": [{"literal":"c"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"l"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$9"]},
    {"name": "TARGET$string$10", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"k"}, {"literal":"e"}, {"literal":"i"}, {"literal":"s"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$10"]},
    {"name": "TARGET$string$11", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"C"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"t"}, {"literal":"u"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TARGET", "symbols": ["TARGET$string$11"]},
    {"name": "_", "symbols": [{"literal":" ","pos":284}]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
