// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "Main", "symbols": ["SENTENCE", "dot"]},
    {"name": "Main", "symbols": ["QUESTION", "question_mark"]},
    {"name": "Main", "symbols": ["EXCITEMENT", "exclamation_point"]},
    {"name": "_", "symbols": [{"literal":" ","pos":24}]},
    {"name": "dot", "symbols": [{"literal":".","pos":30}]},
    {"name": "question_mark", "symbols": [{"literal":"?","pos":36}]},
    {"name": "exclamation_point", "symbols": [{"literal":"!","pos":42}]},
    {"name": "SENTENCE$string$1", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE$string$2", "symbols": [{"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE", "symbols": ["Subject", "_", "SENTENCE$string$1", "_", "Object", "_", "SENTENCE$string$2", "_", "Artist"]},
    {"name": "SENTENCE$string$3", "symbols": [{"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SENTENCE", "symbols": ["Subject", "_", "Verb", "_", "Gerund", "_", "Object", "_", "SENTENCE$string$3", "_", "Places"]},
    {"name": "SENTENCE", "symbols": ["Subject", "_", "Verb", "_", "Object"]},
    {"name": "SENTENCE", "symbols": ["Subject", "_", "Actions", "_", "Places"]},
    {"name": "QUESTION$subexpression$1", "symbols": ["Places"]},
    {"name": "QUESTION$subexpression$1", "symbols": ["Object"]},
    {"name": "QUESTION$subexpression$1", "symbols": ["Artist"]},
    {"name": "QUESTION", "symbols": ["Question_words", "_", "Lower_Subject", "_", "Verb", "_", "QUESTION$subexpression$1"]},
    {"name": "EXCITEMENT$string$1", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXCITEMENT", "symbols": ["Subject", "_", "EXCITEMENT$string$1", "_", "Places"]},
    {"name": "Question_words$string$1", "symbols": [{"literal":"D"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Question_words", "symbols": ["Question_words$string$1"]},
    {"name": "Question_words$string$2", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"m"}, {"literal":"u"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Question_words", "symbols": ["Question_words$string$2"]},
    {"name": "Adj$string$1", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Adj", "symbols": ["Adj$string$1"]},
    {"name": "Adj$string$2", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Adj", "symbols": ["Adj$string$2"]},
    {"name": "Adj$string$3", "symbols": [{"literal":"d"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"m"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Adj", "symbols": ["Adj$string$3"]},
    {"name": "Artist$string$1", "symbols": [{"literal":"V"}, {"literal":"a"}, {"literal":"n"}, {"literal":" "}, {"literal":"G"}, {"literal":"o"}, {"literal":"g"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Artist", "symbols": ["Artist$string$1"]},
    {"name": "Artist$string$2", "symbols": [{"literal":"M"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Artist", "symbols": ["Artist$string$2"]},
    {"name": "Artist$string$3", "symbols": [{"literal":"M"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Artist", "symbols": ["Artist$string$3"]},
    {"name": "Artist$string$4", "symbols": [{"literal":"R"}, {"literal":"o"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Artist", "symbols": ["Artist$string$4"]},
    {"name": "Artist$string$5", "symbols": [{"literal":"R"}, {"literal":"e"}, {"literal":"n"}, {"literal":"o"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Artist", "symbols": ["Artist$string$5"]},
    {"name": "Artist$string$6", "symbols": [{"literal":"D"}, {"literal":"e"}, {"literal":"g"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Artist", "symbols": ["Artist$string$6"]},
    {"name": "Artist$string$7", "symbols": [{"literal":"C"}, {"literal":"é"}, {"literal":"z"}, {"literal":"a"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Artist", "symbols": ["Artist$string$7"]},
    {"name": "Object$string$1", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Object", "symbols": ["Object$string$1"]},
    {"name": "Object$string$2", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"u"}, {"literal":"s"}, {"literal":"h"}, {"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"o"}, {"literal":"k"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Object", "symbols": ["Object$string$2"]},
    {"name": "Object$string$3", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Object", "symbols": ["Object$string$3"]},
    {"name": "Object$string$4", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Object", "symbols": ["Object$string$4"]},
    {"name": "Object$string$5", "symbols": [{"literal":"m"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":"u"}, {"literal":"m"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Object", "symbols": ["Object$string$5"]},
    {"name": "Object$string$6", "symbols": [{"literal":"g"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Object", "symbols": ["Object$string$6"]},
    {"name": "Object$string$7", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Object", "symbols": ["Object$string$7"]},
    {"name": "Object$subexpression$1", "symbols": ["Adj", "Object"]},
    {"name": "Object", "symbols": ["Object$subexpression$1"]},
    {"name": "Places$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"L"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Places", "symbols": ["Places$string$1"]},
    {"name": "Places$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"C"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Places", "symbols": ["Places$string$2"]},
    {"name": "Places$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"A"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"C"}, {"literal":"o"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Places", "symbols": ["Places$string$3"]},
    {"name": "Places$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"u"}, {"literal":"s"}, {"literal":"e"}, {"literal":"u"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Places", "symbols": ["Places$string$4"]},
    {"name": "Places$string$5", "symbols": [{"literal":"M"}, {"literal":"c"}, {"literal":"M"}, {"literal":"u"}, {"literal":"r"}, {"literal":"t"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"B"}, {"literal":"u"}, {"literal":"i"}, {"literal":"l"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Places", "symbols": ["Places$string$5"]},
    {"name": "Places$string$6", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"R"}, {"literal":"o"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"S"}, {"literal":"c"}, {"literal":"u"}, {"literal":"l"}, {"literal":"p"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"G"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Places", "symbols": ["Places$string$6"]},
    {"name": "Subject", "symbols": [{"literal":"I","pos":278}]},
    {"name": "Subject$string$1", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Subject", "symbols": ["Subject$string$1"]},
    {"name": "Subject$string$2", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Subject", "symbols": ["Subject$string$2"]},
    {"name": "Subject$string$3", "symbols": [{"literal":"W"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Subject", "symbols": ["Subject$string$3"]},
    {"name": "Lower_Subject", "symbols": [{"literal":"I","pos":296}]},
    {"name": "Lower_Subject$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Lower_Subject", "symbols": ["Lower_Subject$string$1"]},
    {"name": "Lower_Subject$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Lower_Subject", "symbols": ["Lower_Subject$string$2"]},
    {"name": "Lower_Subject$string$3", "symbols": [{"literal":"w"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Lower_Subject", "symbols": ["Lower_Subject$string$3"]},
    {"name": "Verb$string$1", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Verb", "symbols": ["Verb$string$1"]},
    {"name": "Verb$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":" "}, {"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Verb", "symbols": ["Verb$string$2"]},
    {"name": "Verb$string$3", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Verb", "symbols": ["Verb$string$3"]},
    {"name": "Verb$string$4", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Verb", "symbols": ["Verb$string$4"]},
    {"name": "Actions$string$1", "symbols": [{"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Actions", "symbols": ["Actions$string$1"]},
    {"name": "Actions$string$2", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Actions", "symbols": ["Actions$string$2"]},
    {"name": "Actions$string$3", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"l"}, {"literal":"k"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Actions", "symbols": ["Actions$string$3"]},
    {"name": "Actions$string$4", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Actions", "symbols": ["Actions$string$4"]},
    {"name": "Gerund$string$1", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"e"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Gerund", "symbols": ["Gerund$string$1"]},
    {"name": "Gerund$string$2", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Gerund", "symbols": ["Gerund$string$2"]},
    {"name": "Gerund$string$3", "symbols": [{"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Gerund", "symbols": ["Gerund$string$3"]},
    {"name": "Gerund$string$4", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Gerund", "symbols": ["Gerund$string$4"]},
    {"name": "Gerund$string$5", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"l"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Gerund", "symbols": ["Gerund$string$5"]}
]
  , ParserStart: "Main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
