// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "SENTENCE", "symbols": ["BOAST", "PERIOD"]},
    {"name": "BOAST", "symbols": ["BASIS", "_", "SUBJECT", "_", "DESCRIPTION"]},
    {"name": "VERACITY$string$1", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"I"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERACITY", "symbols": ["VERACITY$string$1"]},
    {"name": "VERACITY$string$2", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}, {"literal":" "}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"p"}, {"literal":"u"}, {"literal":"t"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"w"}, {"literal":"s"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERACITY", "symbols": ["VERACITY$string$2"]},
    {"name": "VERACITY$string$3", "symbols": [{"literal":","}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"d"}, {"literal":"e"}, {"literal":"l"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"b"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"n"}, {"literal":"e"}, {"literal":"w"}, {"literal":"s"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERACITY", "symbols": ["VERACITY$string$3"]},
    {"name": "BASIS", "symbols": ["PM"]},
    {"name": "BASIS", "symbols": ["MV"]},
    {"name": "MV", "symbols": ["MEDIA", "VERACITY", "_", "VERB"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"s"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"s"}, {"literal":"a"}, {"literal":"y"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$2"]},
    {"name": "VERB$string$3", "symbols": [{"literal":"t"}, {"literal":"o"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$3"]},
    {"name": "VERB$string$4", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$4"]},
    {"name": "PM", "symbols": ["PPHRASE", "_", "MEDIA", "VERACITY"]},
    {"name": "PPHRASE$string$1", "symbols": [{"literal":"A"}, {"literal":"c"}, {"literal":"c"}, {"literal":"o"}, {"literal":"r"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PPHRASE", "symbols": ["PPHRASE$string$1"]},
    {"name": "PPHRASE$string$2", "symbols": [{"literal":"A"}, {"literal":"s"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"p"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"b"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PPHRASE", "symbols": ["PPHRASE$string$2"]},
    {"name": "DESCRIPTION", "symbols": ["SIMPLEVERB", "_", "ADJPHRASE"]},
    {"name": "SIMPLEVERB$string$1", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SIMPLEVERB", "symbols": ["SIMPLEVERB$string$1"]},
    {"name": "ADJPHRASE", "symbols": ["EXTREME", "_", "ADJ"]},
    {"name": "EXTREME", "symbols": ["VEXTREME"]},
    {"name": "EXTREME", "symbols": ["VERY"]},
    {"name": "VEXTREME", "symbols": ["VERY", "_", "EXTREME"]},
    {"name": "VERY$string$1", "symbols": [{"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERY", "symbols": ["VERY$string$1"]},
    {"name": "ADJ$string$1", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$1"]},
    {"name": "ADJ$string$2", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"r"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$2"]},
    {"name": "ADJ$string$3", "symbols": [{"literal":"P"}, {"literal":"r"}, {"literal":"o"}, {"literal":"-"}, {"literal":" "}, {"literal":"A"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$3"]},
    {"name": "ADJ$string$4", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADJ", "symbols": ["ADJ$string$4"]},
    {"name": "SUBJECT", "symbols": ["WORLDLEADER"]},
    {"name": "SUBJECT", "symbols": ["COUNTRY"]},
    {"name": "SUBJECT", "symbols": ["FAMILY"]},
    {"name": "MEDIA$string$1", "symbols": [{"literal":"F"}, {"literal":"o"}, {"literal":"x"}, {"literal":" "}, {"literal":"N"}, {"literal":"e"}, {"literal":"w"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MEDIA", "symbols": ["MEDIA$string$1"]},
    {"name": "MEDIA$string$2", "symbols": [{"literal":"P"}, {"literal":"a"}, {"literal":"r"}, {"literal":"l"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MEDIA", "symbols": ["MEDIA$string$2"]},
    {"name": "MEDIA$string$3", "symbols": [{"literal":"Q"}, {"literal":" "}, {"literal":"A"}, {"literal":"n"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MEDIA", "symbols": ["MEDIA$string$3"]},
    {"name": "MEDIA$string$4", "symbols": [{"literal":"O"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"A"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":" "}, {"literal":"N"}, {"literal":"e"}, {"literal":"w"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MEDIA", "symbols": ["MEDIA$string$4"]},
    {"name": "WORLDLEADER$string$1", "symbols": [{"literal":"P"}, {"literal":"u"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WORLDLEADER", "symbols": ["WORLDLEADER$string$1"]},
    {"name": "WORLDLEADER$string$2", "symbols": [{"literal":"K"}, {"literal":"i"}, {"literal":"m"}, {"literal":" "}, {"literal":"J"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"U"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WORLDLEADER", "symbols": ["WORLDLEADER$string$2"]},
    {"name": "WORLDLEADER$string$3", "symbols": [{"literal":"X"}, {"literal":"i"}, {"literal":" "}, {"literal":"J"}, {"literal":"i"}, {"literal":"n"}, {"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WORLDLEADER", "symbols": ["WORLDLEADER$string$3"]},
    {"name": "FAMILY$string$1", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY", "symbols": ["FAMILY$string$1"]},
    {"name": "FAMILY$string$2", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"d"}, {"literal":"a"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY", "symbols": ["FAMILY$string$2"]},
    {"name": "FAMILY$string$3", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"w"}, {"literal":"i"}, {"literal":"f"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY", "symbols": ["FAMILY$string$3"]},
    {"name": "FAMILY$string$4", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"g"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FAMILY", "symbols": ["FAMILY$string$4"]},
    {"name": "COUNTRY$string$1", "symbols": [{"literal":"R"}, {"literal":"u"}, {"literal":"s"}, {"literal":"s"}, {"literal":"i"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COUNTRY", "symbols": ["COUNTRY$string$1"]},
    {"name": "COUNTRY$string$2", "symbols": [{"literal":"N"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"K"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COUNTRY", "symbols": ["COUNTRY$string$2"]},
    {"name": "COUNTRY$string$3", "symbols": [{"literal":"C"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COUNTRY", "symbols": ["COUNTRY$string$3"]},
    {"name": "_", "symbols": [{"literal":" ","pos":250}]},
    {"name": "PERIOD", "symbols": [{"literal":".","pos":256}]}
]
  , ParserStart: "SENTENCE"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
