// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["QUESTION", {"literal":"?","pos":6}]},
    {"name": "_", "symbols": [{"literal":" ","pos":12}]},
    {"name": "QUESTION$string$1", "symbols": [{"literal":"C"}, {"literal":"a"}, {"literal":"n"}, {"literal":" "}, {"literal":"I"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "QUESTION", "symbols": ["QUESTION$string$1", "_", "VERB", "_", "ORDER"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"g"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$2"]},
    {"name": "VERB$string$3", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$3"]},
    {"name": "ORDER", "symbols": [{"literal":"a","pos":46}, "_", "SIZE", "_", "DRINK", "_", "EXTRA"]},
    {"name": "DRINK", "symbols": ["TEMPERATURE", "_", "TYPE"]},
    {"name": "TEMPERATURE$string$1", "symbols": [{"literal":"i"}, {"literal":"c"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMPERATURE", "symbols": ["TEMPERATURE$string$1"]},
    {"name": "TEMPERATURE$string$2", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMPERATURE", "symbols": ["TEMPERATURE$string$2"]},
    {"name": "TEMPERATURE$string$3", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"r"}, {"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"h"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMPERATURE", "symbols": ["TEMPERATURE$string$3"]},
    {"name": "TEMPERATURE$string$4", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMPERATURE", "symbols": ["TEMPERATURE$string$4"]},
    {"name": "TEMPERATURE$string$5", "symbols": [{"literal":"r"}, {"literal":"o"}, {"literal":"o"}, {"literal":"m"}, {"literal":" "}, {"literal":"t"}, {"literal":"e"}, {"literal":"m"}, {"literal":"p"}, {"literal":"a"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMPERATURE", "symbols": ["TEMPERATURE$string$5"]},
    {"name": "TEMPERATURE$string$6", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":" "}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMPERATURE", "symbols": ["TEMPERATURE$string$6"]},
    {"name": "TEMPERATURE$string$7", "symbols": [{"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":" "}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TEMPERATURE", "symbols": ["TEMPERATURE$string$7"]},
    {"name": "TYPE$string$1", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"l"}, {"literal":" "}, {"literal":"m"}, {"literal":"a"}, {"literal":"c"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"a"}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$1"]},
    {"name": "TYPE$string$2", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$2"]},
    {"name": "TYPE$string$3", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$3"]},
    {"name": "TYPE$string$4", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$4"]},
    {"name": "TYPE$string$5", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":" "}, {"literal":"d"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$5"]},
    {"name": "TYPE$string$6", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"b"}, {"literal":"r"}, {"literal":"e"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$6"]},
    {"name": "TYPE$string$7", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$7"]},
    {"name": "TYPE$string$8", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"t"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$8"]},
    {"name": "TYPE$string$9", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"o"}, {"literal":"w"}, {"literal":"n"}, {"literal":" "}, {"literal":"s"}, {"literal":"u"}, {"literal":"g"}, {"literal":"a"}, {"literal":"r"}, {"literal":" "}, {"literal":"o"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"k"}, {"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"e"}, {"literal":"s"}, {"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$9"]},
    {"name": "TYPE$string$10", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TYPE", "symbols": ["TYPE$string$10"]},
    {"name": "EXTRA$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXTRA", "symbols": ["EXTRA", "_", "EXTRA$string$1", "_", "EXTRA"]},
    {"name": "EXTRA$string$2", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXTRA$string$3", "symbols": [{"literal":"p"}, {"literal":"u"}, {"literal":"m"}, {"literal":"p"}, {"literal":"s"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXTRA", "symbols": ["EXTRA$string$2", "_", "NUM", "_", "EXTRA$string$3", "_", "SYRUP"]},
    {"name": "EXTRA$string$4", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"n"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXTRA", "symbols": ["EXTRA$string$4", "_", "INGREDIENTS"]},
    {"name": "EXTRA$string$5", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXTRA$string$6", "symbols": [{"literal":"c"}, {"literal":"u"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXTRA", "symbols": ["EXTRA$string$5", "_", "SIZE", "_", "EXTRA$string$6"]},
    {"name": "EXTRA$string$7", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":" "}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXTRA", "symbols": ["EXTRA$string$7", "_", "INGREDIENTS"]},
    {"name": "EXTRA$string$8", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXTRA$string$9", "symbols": [{"literal":"p"}, {"literal":"u"}, {"literal":"m"}, {"literal":"p"}, {"literal":"s"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXTRA$string$10", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "EXTRA", "symbols": ["EXTRA$string$8", "_", "NUM", "_", "EXTRA$string$9", "_", "SYRUP", "_", "EXTRA$string$10", "_", "INGREDIENTS"]},
    {"name": "SIZE$string$1", "symbols": [{"literal":"t"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SIZE", "symbols": ["SIZE$string$1"]},
    {"name": "SIZE$string$2", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SIZE", "symbols": ["SIZE$string$2"]},
    {"name": "SIZE$string$3", "symbols": [{"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SIZE", "symbols": ["SIZE$string$3"]},
    {"name": "SIZE$string$4", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SIZE", "symbols": ["SIZE$string$4"]},
    {"name": "NUM$string$1", "symbols": [{"literal":"t"}, {"literal":"w"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUM", "symbols": ["NUM$string$1"]},
    {"name": "NUM$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUM", "symbols": ["NUM$string$2"]},
    {"name": "NUM$string$3", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUM", "symbols": ["NUM$string$3"]},
    {"name": "NUM$string$4", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUM", "symbols": ["NUM$string$4"]},
    {"name": "NUM$string$5", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUM", "symbols": ["NUM$string$5"]},
    {"name": "NUM$string$6", "symbols": [{"literal":"t"}, {"literal":"w"}, {"literal":"o"}, {"literal":" "}, {"literal":"h"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NUM", "symbols": ["NUM$string$6"]},
    {"name": "SYRUP$string$1", "symbols": [{"literal":"c"}, {"literal":"l"}, {"literal":"a"}, {"literal":"s"}, {"literal":"s"}, {"literal":"i"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SYRUP", "symbols": ["SYRUP$string$1"]},
    {"name": "SYRUP$string$2", "symbols": [{"literal":"p"}, {"literal":"u"}, {"literal":"m"}, {"literal":"p"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SYRUP", "symbols": ["SYRUP$string$2"]},
    {"name": "SYRUP$string$3", "symbols": [{"literal":"r"}, {"literal":"a"}, {"literal":"s"}, {"literal":"p"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SYRUP", "symbols": ["SYRUP$string$3"]},
    {"name": "SYRUP$string$4", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SYRUP", "symbols": ["SYRUP$string$4"]},
    {"name": "SYRUP$string$5", "symbols": [{"literal":"s"}, {"literal":"u"}, {"literal":"g"}, {"literal":"a"}, {"literal":"r"}, {"literal":"-"}, {"literal":"f"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":" "}, {"literal":"v"}, {"literal":"a"}, {"literal":"n"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SYRUP", "symbols": ["SYRUP$string$5"]},
    {"name": "SYRUP$string$6", "symbols": [{"literal":"v"}, {"literal":"a"}, {"literal":"n"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SYRUP", "symbols": ["SYRUP$string$6"]},
    {"name": "INGREDIENTS$string$1", "symbols": [{"literal":"p"}, {"literal":"u"}, {"literal":"m"}, {"literal":"p"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"f"}, {"literal":"o"}, {"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INGREDIENTS", "symbols": ["INGREDIENTS$string$1"]},
    {"name": "INGREDIENTS$string$2", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"l"}, {"literal":" "}, {"literal":"d"}, {"literal":"r"}, {"literal":"i"}, {"literal":"z"}, {"literal":"z"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INGREDIENTS", "symbols": ["INGREDIENTS$string$2"]},
    {"name": "INGREDIENTS$string$3", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"k"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INGREDIENTS", "symbols": ["INGREDIENTS$string$3"]},
    {"name": "INGREDIENTS$string$4", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"p"}, {"literal":"p"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"c"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INGREDIENTS", "symbols": ["INGREDIENTS$string$4"]},
    {"name": "INGREDIENTS$string$5", "symbols": [{"literal":"s"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INGREDIENTS", "symbols": ["INGREDIENTS$string$5"]},
    {"name": "INGREDIENTS$string$6", "symbols": [{"literal":"e"}, {"literal":"x"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":" "}, {"literal":"e"}, {"literal":"s"}, {"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INGREDIENTS", "symbols": ["INGREDIENTS$string$6"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
