// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "main", "symbols": ["single", {"literal":".","pos":6}]},
    {"name": "main", "symbols": ["multiple", {"literal":".","pos":12}]},
    {"name": "single", "symbols": ["person", "_", "acts", "_", "additives"]},
    {"name": "multiple", "symbols": ["people", "_", "act", "_", "additives"]},
    {"name": "person$string$1", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"k"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "person", "symbols": ["person$string$1"]},
    {"name": "person$string$2", "symbols": [{"literal":"M"}, {"literal":"a"}, {"literal":"m"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "person", "symbols": ["person$string$2"]},
    {"name": "people$string$1", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"B"}, {"literal":"r"}, {"literal":"o"}, {"literal":"k"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"D"}, {"literal":"a"}, {"literal":"m"}, {"literal":"n"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "people", "symbols": ["people$string$1"]},
    {"name": "people$string$2", "symbols": [{"literal":"K"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"j"}, {"literal":"o"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "people", "symbols": ["people$string$2"]},
    {"name": "people$string$3", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "people", "symbols": ["people$string$3"]},
    {"name": "people$string$4", "symbols": [{"literal":"T"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"g"}, {"literal":"i"}, {"literal":"r"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "people", "symbols": ["people$string$4"]},
    {"name": "people$string$5", "symbols": [{"literal":"T"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "people", "symbols": ["people$string$5"]},
    {"name": "acts$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "acts", "symbols": ["acts$string$1"]},
    {"name": "acts$string$2", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "acts", "symbols": ["acts$string$2"]},
    {"name": "acts$string$3", "symbols": [{"literal":"c"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "acts", "symbols": ["acts$string$3"]},
    {"name": "acts$string$4", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"k"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"o"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "acts", "symbols": ["acts$string$4"]},
    {"name": "act$string$1", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "act", "symbols": ["act$string$1", "_", "inplace"]},
    {"name": "act$string$2", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"l"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"s"}, {"literal":"h"}, {"literal":"*"}, {"literal":"*"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}, {"literal":" "}, {"literal":"o"}, {"literal":"f"}, {"literal":" "}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "act", "symbols": ["act$string$2"]},
    {"name": "act$string$3", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "act", "symbols": ["act$string$3"]},
    {"name": "act$string$4", "symbols": [{"literal":"b"}, {"literal":"l"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"r"}, {"literal":" "}, {"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "act", "symbols": ["act$string$4"]},
    {"name": "act$string$5", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "act", "symbols": ["act$string$5"]},
    {"name": "acting$string$1", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "acting", "symbols": ["acting$string$1"]},
    {"name": "acting$string$2", "symbols": [{"literal":"a"}, {"literal":"s"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"'"}, {"literal":"w"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"w"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"w"}, {"literal":"r"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}, {"literal":"?"}, {"literal":"'"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "acting", "symbols": ["acting$string$2"]},
    {"name": "additives$string$1", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "additives", "symbols": ["additives$string$1", "_", "inplace"]},
    {"name": "additives$string$2", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"t"}, {"literal":" "}, {"literal":"I"}, {"literal":"'"}, {"literal":"m"}, {"literal":" "}, {"literal":"d"}, {"literal":"i"}, {"literal":"s"}, {"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "additives", "symbols": ["additives$string$2", "_", "single"]},
    {"name": "additives$string$3", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "additives", "symbols": ["additives$string$3", "_", "multiple"]},
    {"name": "additives$string$4", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "additives", "symbols": ["additives$string$4", "_", "acting"]},
    {"name": "thing$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":" "}, {"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "thing", "symbols": ["thing$string$1"]},
    {"name": "thing$string$2", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":" "}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "thing", "symbols": ["thing$string$2"]},
    {"name": "things$string$1", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "things", "symbols": ["things$string$1"]},
    {"name": "things$string$2", "symbols": [{"literal":"d"}, {"literal":"a"}, {"literal":"g"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "things", "symbols": ["things$string$2"]},
    {"name": "things$string$3", "symbols": [{"literal":"c"}, {"literal":"l"}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "things", "symbols": ["things$string$3"]},
    {"name": "things$string$4", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "things", "symbols": ["things$string$4"]},
    {"name": "things$string$5", "symbols": [{"literal":"q"}, {"literal":"u"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "things", "symbols": ["things$string$5"]},
    {"name": "things$string$6", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "things", "symbols": ["things$string$6"]},
    {"name": "inplace$string$1", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "inplace", "symbols": ["inplace$string$1"]},
    {"name": "inplace$string$2", "symbols": [{"literal":"a"}, {"literal":" "}, {"literal":"h"}, {"literal":"o"}, {"literal":"s"}, {"literal":"p"}, {"literal":"i"}, {"literal":"t"}, {"literal":"a"}, {"literal":"l"}, {"literal":" "}, {"literal":"r"}, {"literal":"o"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "inplace", "symbols": ["inplace$string$2"]},
    {"name": "inplace$string$3", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "inplace", "symbols": ["inplace$string$3"]},
    {"name": "inplace$string$4", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":" "}, {"literal":"g"}, {"literal":"r"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "inplace", "symbols": ["inplace$string$4"]},
    {"name": "_", "symbols": [{"literal":" ","pos":220}]}
]
  , ParserStart: "main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
