// Generated automatically by nearley, version undefined
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "MAIN", "symbols": ["SPONGEBOB_THOUGHTS", {"literal":".","pos":6}]},
    {"name": "MAIN", "symbols": ["SPONGEBOB_WONDERS", {"literal":"?","pos":12}]},
    {"name": "_", "symbols": [{"literal":" ","pos":18}]},
    {"name": "SPONGEBOB_WONDERS$string$1", "symbols": [{"literal":"H"}, {"literal":"o"}, {"literal":"w"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"S"}, {"literal":"q"}, {"literal":"u"}, {"literal":"i"}, {"literal":"d"}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}, {"literal":" "}, {"literal":"d"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SPONGEBOB_WONDERS", "symbols": ["SPONGEBOB_WONDERS$string$1", "_", "PLACES"]},
    {"name": "SPONGEBOB_WONDERS$string$2", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"n"}, {"literal":" "}, {"literal":"P"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}, {"literal":"t"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SPONGEBOB_WONDERS$string$3", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"a"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SPONGEBOB_WONDERS", "symbols": ["SPONGEBOB_WONDERS$string$2", "_", "ENTITY", "_", "SPONGEBOB_WONDERS$string$3"]},
    {"name": "SPONGEBOB_WONDERS$string$4", "symbols": [{"literal":"W"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}, {"literal":" "}, {"literal":"i"}, {"literal":"s"}, {"literal":" "}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"h"}, {"literal":"y"}, {"literal":"p"}, {"literal":"e"}, {"literal":" "}, {"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SPONGEBOB_WONDERS", "symbols": ["SPONGEBOB_WONDERS$string$4", "_", "ENTITY"]},
    {"name": "SPONGEBOB_THOUGHTS", "symbols": ["CATCHPHRASE", "_", "SUBJECT", "_", "ADVERB", "_", "VERB", "_", "PREPOSITION"]},
    {"name": "SUBJECT", "symbols": [{"literal":"I","pos":76}]},
    {"name": "SUBJECT$string$1", "symbols": [{"literal":"Y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUBJECT", "symbols": ["SUBJECT$string$1"]},
    {"name": "SUBJECT", "symbols": ["CHARACTER"]},
    {"name": "CATCHPHRASE$string$1", "symbols": [{"literal":"A"}, {"literal":"y"}, {"literal":"e"}, {"literal":","}, {"literal":" "}, {"literal":"A"}, {"literal":"y"}, {"literal":"e"}, {"literal":" "}, {"literal":"C"}, {"literal":"a"}, {"literal":"p"}, {"literal":"t"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CATCHPHRASE", "symbols": ["CATCHPHRASE$string$1"]},
    {"name": "CATCHPHRASE$string$2", "symbols": [{"literal":"O"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":","}, {"literal":" "}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":","}, {"literal":" "}, {"literal":"z"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"y"}, {"literal":"e"}, {"literal":"a"}, {"literal":"r"}, {"literal":"s"}, {"literal":" "}, {"literal":"l"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":","}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CATCHPHRASE", "symbols": ["CATCHPHRASE$string$2"]},
    {"name": "CATCHPHRASE$string$3", "symbols": [{"literal":"B"}, {"literal":"a"}, {"literal":"r"}, {"literal":"n"}, {"literal":"a"}, {"literal":"c"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CATCHPHRASE", "symbols": ["CATCHPHRASE$string$3"]},
    {"name": "CATCHPHRASE$string$4", "symbols": [{"literal":"M"}, {"literal":"e"}, {"literal":" "}, {"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"y"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CATCHPHRASE", "symbols": ["CATCHPHRASE$string$4"]},
    {"name": "CATCHPHRASE$string$5", "symbols": [{"literal":"O"}, {"literal":"r"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"u"}, {"literal":"p"}, {"literal":"!"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CATCHPHRASE", "symbols": ["CATCHPHRASE$string$5"]},
    {"name": "CATCHPHRASE$string$6", "symbols": [{"literal":"O"}, {"literal":"h"}, {"literal":" "}, {"literal":"b"}, {"literal":"o"}, {"literal":"y"}, {"literal":"."}, {"literal":"."}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CATCHPHRASE", "symbols": ["CATCHPHRASE$string$6"]},
    {"name": "CHARACTER$string$1", "symbols": [{"literal":"S"}, {"literal":"p"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"b"}, {"literal":"o"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$1"]},
    {"name": "CHARACTER$string$2", "symbols": [{"literal":"S"}, {"literal":"q"}, {"literal":"u"}, {"literal":"i"}, {"literal":"d"}, {"literal":"w"}, {"literal":"a"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$2"]},
    {"name": "CHARACTER$string$3", "symbols": [{"literal":"M"}, {"literal":"r"}, {"literal":"."}, {"literal":" "}, {"literal":"K"}, {"literal":"r"}, {"literal":"a"}, {"literal":"b"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$3"]},
    {"name": "CHARACTER$string$4", "symbols": [{"literal":"P"}, {"literal":"a"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$4"]},
    {"name": "CHARACTER$string$5", "symbols": [{"literal":"P"}, {"literal":"l"}, {"literal":"a"}, {"literal":"n"}, {"literal":"k"}, {"literal":"t"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$5"]},
    {"name": "CHARACTER$string$6", "symbols": [{"literal":"G"}, {"literal":"a"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$6"]},
    {"name": "CHARACTER$string$7", "symbols": [{"literal":"S"}, {"literal":"a"}, {"literal":"n"}, {"literal":"d"}, {"literal":"y"}, {"literal":" "}, {"literal":"C"}, {"literal":"h"}, {"literal":"e"}, {"literal":"e"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$7"]},
    {"name": "CHARACTER$string$8", "symbols": [{"literal":"K"}, {"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$8"]},
    {"name": "CHARACTER$string$9", "symbols": [{"literal":"M"}, {"literal":"r"}, {"literal":"s"}, {"literal":"."}, {"literal":" "}, {"literal":"P"}, {"literal":"u"}, {"literal":"f"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$9"]},
    {"name": "CHARACTER$string$10", "symbols": [{"literal":"L"}, {"literal":"a"}, {"literal":"r"}, {"literal":"r"}, {"literal":"y"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"L"}, {"literal":"o"}, {"literal":"b"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$10"]},
    {"name": "CHARACTER$string$11", "symbols": [{"literal":"K"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"N"}, {"literal":"e"}, {"literal":"p"}, {"literal":"t"}, {"literal":"u"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CHARACTER", "symbols": ["CHARACTER$string$11"]},
    {"name": "VERB$string$1", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"b"}, {"literal":"b"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$1"]},
    {"name": "VERB$string$2", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$2"]},
    {"name": "VERB$string$3", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$3"]},
    {"name": "VERB$string$4", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$4"]},
    {"name": "VERB$string$5", "symbols": [{"literal":"d"}, {"literal":"a"}, {"literal":"n"}, {"literal":"c"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$5"]},
    {"name": "VERB$string$6", "symbols": [{"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VERB", "symbols": ["VERB$string$6"]},
    {"name": "ADVERB$string$1", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"s"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$1"]},
    {"name": "ADVERB$string$2", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"r"}, {"literal":"i"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$2"]},
    {"name": "ADVERB$string$3", "symbols": [{"literal":"b"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$3"]},
    {"name": "ADVERB$string$4", "symbols": [{"literal":"e"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$4"]},
    {"name": "ADVERB$string$5", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"r"}, {"literal":"e"}, {"literal":"t"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$5"]},
    {"name": "ADVERB$string$6", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"w"}, {"literal":"a"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$6", "_", "ADVERB"]},
    {"name": "ADVERB$string$7", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"l"}, {"literal":"m"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$7"]},
    {"name": "ADVERB$string$8", "symbols": [{"literal":"m"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":"a"}, {"literal":"n"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ADVERB", "symbols": ["ADVERB$string$8"]},
    {"name": "PREPOSITION$string$1", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$1", "_", "THINGS"]},
    {"name": "PREPOSITION$string$2", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"w"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$2", "_", "CHARACTER"]},
    {"name": "PREPOSITION$string$3", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$3", "_", "PLACES"]},
    {"name": "PREPOSITION$string$4", "symbols": [{"literal":"d"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$4", "_", "ENTITY"]},
    {"name": "PREPOSITION$string$5", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$5", "_", "THINGS"]},
    {"name": "PREPOSITION$string$6", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}, {"literal":" "}, {"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$6", "_", "PLACES"]},
    {"name": "PREPOSITION$string$7", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PREPOSITION", "symbols": ["PREPOSITION$string$7", "_", "CHARACTER"]},
    {"name": "ENTITY", "symbols": ["PLACES"]},
    {"name": "ENTITY", "symbols": ["THINGS"]},
    {"name": "PLACES$string$1", "symbols": [{"literal":"B"}, {"literal":"i"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"i"}, {"literal":" "}, {"literal":"B"}, {"literal":"o"}, {"literal":"t"}, {"literal":"t"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$1"]},
    {"name": "PLACES$string$2", "symbols": [{"literal":"K"}, {"literal":"r"}, {"literal":"u"}, {"literal":"s"}, {"literal":"t"}, {"literal":"y"}, {"literal":" "}, {"literal":"K"}, {"literal":"r"}, {"literal":"a"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$2"]},
    {"name": "PLACES$string$3", "symbols": [{"literal":"P"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"t"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$3"]},
    {"name": "PLACES$string$4", "symbols": [{"literal":"R"}, {"literal":"o"}, {"literal":"c"}, {"literal":"k"}, {"literal":" "}, {"literal":"B"}, {"literal":"o"}, {"literal":"t"}, {"literal":"t"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$4"]},
    {"name": "PLACES$string$5", "symbols": [{"literal":"T"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"a"}, {"literal":"c"}, {"literal":"l"}, {"literal":"e"}, {"literal":" "}, {"literal":"A"}, {"literal":"c"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$5"]},
    {"name": "PLACES$string$6", "symbols": [{"literal":"N"}, {"literal":"e"}, {"literal":"w"}, {"literal":" "}, {"literal":"K"}, {"literal":"e"}, {"literal":"l"}, {"literal":"p"}, {"literal":" "}, {"literal":"C"}, {"literal":"i"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$6"]},
    {"name": "PLACES$string$7", "symbols": [{"literal":"B"}, {"literal":"a"}, {"literal":"s"}, {"literal":"s"}, {"literal":" "}, {"literal":"V"}, {"literal":"e"}, {"literal":"g"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$7"]},
    {"name": "PLACES$string$8", "symbols": [{"literal":"D"}, {"literal":"u"}, {"literal":"l"}, {"literal":"l"}, {"literal":"s"}, {"literal":"v"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$8"]},
    {"name": "PLACES$string$9", "symbols": [{"literal":"B"}, {"literal":"o"}, {"literal":"t"}, {"literal":"t"}, {"literal":"o"}, {"literal":"m"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"U"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$9"]},
    {"name": "PLACES$string$10", "symbols": [{"literal":"F"}, {"literal":"a"}, {"literal":"r"}, {"literal":"-"}, {"literal":"O"}, {"literal":"u"}, {"literal":"t"}, {"literal":"-"}, {"literal":"V"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$10"]},
    {"name": "PLACES$string$11", "symbols": [{"literal":"B"}, {"literal":"u"}, {"literal":"b"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}, {"literal":"t"}, {"literal":"o"}, {"literal":"w"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLACES", "symbols": ["PLACES$string$11"]},
    {"name": "THINGS$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"K"}, {"literal":"r"}, {"literal":"a"}, {"literal":"b"}, {"literal":"b"}, {"literal":"y"}, {"literal":" "}, {"literal":"P"}, {"literal":"a"}, {"literal":"t"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$1"]},
    {"name": "THINGS$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":" "}, {"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"r"}, {"literal":"e"}, {"literal":"t"}, {"literal":" "}, {"literal":"r"}, {"literal":"e"}, {"literal":"c"}, {"literal":"i"}, {"literal":"p"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$2"]},
    {"name": "THINGS$string$3", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THINGS", "symbols": ["THINGS$string$3"]}
]
  , ParserStart: "MAIN"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
